### ISSUE TITLE
Is Sandbox optional?

### ISSUE THREAD

**Issue by lehors** [ossf/tac#105]
Changes brought in with PR #103 imply that projects get to Incubating stage by moving from the Sandbox stage, which effectively makes the Sandbox stage a mandatory first step:

> Incubating Projects are required to undergo technical due diligence as a part of the process to move from Sandbox to Incubation.

However, I'm not sure this change was intended and the [project stages diagram](../blob/7d463ba74c3b930e5b8a863fc0b555ade36dcc8a/process/project-stages.png) still says otherwise, allowing for projects to start in Incubating stage.

Which way should it be?

**Comment by dlorenc** [comment]
IMO optional makes more sense.

**Comment by gkunz** [comment]
Considering that OpenSSF wants to be open to include projects which have already achieved some level of maturity (e.g., sigstore), making the sandbox stage an optional one would be reasonable.

**Comment by lehors** [comment]
Sandbox is Optional, see https://github.com/ossf/tac/blob/main/process/project-lifecycle.md#project-process-sandbox-to-incubation-and-direct-entry-to-incubation
