### ISSUE TITLE
Run an election for the TAC Chair

### ISSUE THREAD

**Issue by caniszczyk** [ossf/tac#12]
"annually electing a chairperson to preside over meetings, set the agenda for meetings, ensure meeting minutes are taken, and who will also serve on the Governing Board as the TAC’s representative (the “TAC Representative”)"

**Comment by LindsayLF** [comment]
TAC Chair Election process has been initiated:
- Self Nominations Due: by 5:00p PST, Friday, Aug 28
- Voting Opens: Monday, Aug 31
- Voting Closes: 5:00p PST, Friday, Sept 4
- TAC Chair Announced: Tues, Sept 8 (Mon, Sept 7 is a US Holiday)

**Comment by caniszczyk** [comment]
@LindsayLF how are self nominations posted? here on github?

**Comment by LindsayLF** [comment]
@caniszczyk Sent to Public TAC list in groups.io

OSSF TAC Chair Self-Nomination [~5 minutes]
> The OSSF TAC Chair Self-Nomination will close on Friday, Aug 28, at 5:00 PST.  The voting process and details will be shared Monday, Aug 31.  The OSSF TAC Chair Self-Nomination Form can be found here: https://forms.gle/2VuqPcK7HymvqPMS8.  Note, only current members of the Technical Advisory Council can be nominated. See current members listed here: https://openssf.org/about/tac/

**Comment by dlorenc** [comment]
@LindsayLF - the form is currently locked down: 
![image](https://user-images.githubusercontent.com/1714486/91325866-4c02a900-e789-11ea-914c-352d0a89d607.png)

**Comment by LindsayLF** [comment]
@dlorenc Fixed, apologies! https://forms.gle/Tf1HtE8n2g7LknwJ9

**Comment by dlorenc** [comment]
This is done now! Congrats @rhaning !
