### ISSUE TITLE
Processes/docs needed for project resource requests

### ISSUE THREAD

**Issue by annabellegoth2boss** [ossf/tac#121]
Per the [request ](https://github.com/ossf/tac/pull/112/files#r917479211)in #112 to temporarily pull out processes for project resource requests, capturing what was removed and needs to be written:

- [ ] Process for submitting to the OpenSSF blog, and clarifying when/how TAC reviews blogs to ensure consistent, external technical vision
- [ ] Process for submitting to OpenSSF email blasts
- [ ] Process for requesting funding (includes swag, infrastructure, maintainer stipends, security audits)
- [ ] Process for OpenSSF Projects to raise funds for specific needs (eg infrastructure) to augment general funding
- [ ] Reinsert vulnerability disclosure section from /request_resources. There seemed to be no objections to this content, but without the above MD it has no home. 
- [ ] Reinsert code of conduct support. Were no objections to content, but without above MD it has no home.

**Comment by annabellegoth2boss** [comment]
Re TAC review of blogs, [5-0 vote at 8/23 TAC meeting](https://docs.google.com/document/d/18BJlokTeG5e5ARD1VFDl5bIP75OFPCtzf77lfadQ4f0/edit) in favor of TAC reserving the option to review technical blogs and statements made on behalf of the OpenSSF

**Comment by SecurityCRob** [comment]
pr was merged 11dec2023
