### ISSUE TITLE
Create lifecycle for WGs + maturity levels

### ISSUE THREAD

**Issue by caniszczyk** [ossf/tac#13]

**Comment by dlorenc** [comment]
I thought through this a little bit more. Here's what I think we should be trying to achieve/prevent with this process.

The TAC exists to provide oversight of initiatives. What I think we want to avoid is a bunch of working groups taking part in overlapping, potentially conflicting activities that result in unclear guidance. So, to address this, I propose we basically have two tiers of Technical Initiatives:

### Incubating

This includes all existing WGs, and new proposed ones.
To form a new incubating Initiative, we probably want some of the following:

- 1-2 TAC sponsors
- Rough idea for goals/scope
- Enough evidence of interest (multiple companies, 5+ people committed to attend)
- Participate in quarterly reviews

These initiatives:

- May operate as part of the OSSF
- Have access to community resources (Zooms, Youtube channels, GitHub, Slack channels, etc.)
- Can request funding/other resources (subject to TAC/GB approval)
- Can publish things under the OSSF banner, with further TAC approval. The TAC will review all formal publications, launched services, etc. to ensure they fit in with the rest of the OSSF efforts, and represent the technical vision of the TAC.

#### Graduated Initiatives

These meet all the criteria of an incubating Initiative, plus:

- A formal charter reviewed by the TAC annually
- Formal governance, with multiple organizations represented

These can:

- Publish things and launch services without further TAC review, provided these are within the scope of the approved charter.

**Comment by kaywilliams** [comment]
I have a couple items to consider adding. Notes - 1) I am keen on the idea of asking initiatives (both incubating and graduated) to set quarterly goals and provide quarterly progress summaries so that for the OpenSSF overall we can demonstrate momentum and celebrate success. 2) I would like to guide initiatives to have consistency across readme and governance documents.  This helps people who want to participate know where and how to get involved.  I am open to thoughts from others.

Incubating
* Draft readme.md and governance/charter.md for approval by TAC.
* Establish quarterly goals and provide quarterly progress summary to support OpenSSF communications (quarterly press releases)

Requirement for Graduated
* Establish quarterly goals and provide quarterly progress summary to support OpenSSF communications (quarterly press releases)

**Comment by dlorenc** [comment]
This sounds great!

**Comment by dlorenc** [comment]
At second thought, and after looking at some other OSS projects I've been involved in, quarterly goals seem a little too granular. Something like six months or even a year is more realistic for goals.

Quarterly status updates and updates to those goals still make sense though.

**Comment by mayakacz** [comment]
Thanks for these proposals @dlorenc and @kaywilliams ! Piling on.

> The TAC exists to provide oversight of initiatives. What I think we want to avoid a few things:
> * A bunch of working groups taking part in overlapping, potentially conflicting activities that result in unclear guidance and confusion.
> * WGs publishing artifacts or otherwise conducting activities that could potentially harm the reputation of the OSSF as a whole. Obviously everyone here has good intentions, but security often results in engineering tradeoffs that require conscious discussion and agreement.

:100:

> Draft readme.md and governance/charter.md for approval by TAC.

Agreed this should be `incubating` not `graduated`.

> At second thought, and after looking at some other OSS projects I've been involved in, quarterly goals seem a little too granular. Something like six months or even a year is more realistic for goals.

Agreed.

---

So I think pulling together a few of the above threads, and adding a few more ideas,

To **become** `incubating`:
* 1 TAC sponsor, and goes to TAC vote for inclusion
  + I'm not opposed to making this 2, but 1-2 is not clear.
  + Should we define sponsorship? e.g., provides guidance, supports goals of project, etc.
* Draft readme.md and governance/charter.md for review by TAC
  + This is to help ensure limited overlap with existing WG
* Have met at least twice
* Have at least 5 interested individuals from at least 3 different organizations

Once `incubating`:
* Part of quarterly TAC reviews
* readme.md and governance/charter.md approved by WG and by TAC
* Meet on a regular cadence. Meetings are public, recorded, and on the calendar
* May operate as part of the OSSF
* Have access to community resources (Zooms, Youtube channels, GitHub, Slack channels, etc.)
* Can request funding/other resources (subject to TAC/GB approval)

To **become** `graduated`:
* TAC vote
* Have met at least X times
  * What should this be?
* Have at least X members
  * What should this be? Should this be a requirement?
* Have created X artifacts? e.g., services, whitepapers, notable improvements, etc. This is hard to define.

Once `graduated`:
(same as `incubating`, plus)
* Have at least annual goals and metrics for success

I'm not sure on the ability to publish things without TAC review. We don't want to slow groups down, but also want to sign off on big announcements (but not every single item).

We should also discuss: Are there only two stages? Is `graduated` the right term for a working group (vs. a project say)? Can working groups be demoted or removed?

---

**Comment by dlorenc** [comment]
> I'm not sure on the ability to publish things without TAC review. We don't want to slow groups down, but also want to sign off on big announcements (but not every single item).

My idea here was that the "graduated" ones would have well-defined enough scopes/roadmaps/charters that there would be no surprises in the the things they're doing/publishing, and would hopefully have enough TAC involvement through the sponsor that any concerns could be raised early. 

> * Have at least 5 interested individuals from at least 3 different organizations

+1. Maybe we could check this based on regular meeting attendance? The groups all seem to have a sign-in section in the agendas.


> * Have met at least twice

Having been in almost all the meetings, this seems like a low bar :) The first one is basically just intros.

> * Have at least X members
>   
>   * What should this be? Should this be a requirement?

Some of the groups seem to have a membership process, but I'm not sure how this works or what it really means. I've listened in to as many meetings as I can so far, but don't really intend to actively participate. Does that make me a member?

**Comment by dlorenc** [comment]
> 1 TAC sponsor, and goes to TAC vote for inclusion
> * I'm not opposed to making this 2, but 1-2 is not clear.

Ah yes! Good catch. I meant that as a question for discussion, either 1 or 2. Not a range :)

**Comment by dcmiddle** [comment]
One optimization on the process as defined so far would be to drop the charter docs. The boilerplate CHARTER.md from the LF is largely about governance process, whereas the discussion here seems mostly about clarity of scope.
The README.md proposal (https://github.com/ossf/project-template/pull/1) captures the mission/scope/deliverable considerations well. I believe that will be sufficient to setup a working group for success without getting bogged down in processes that may not ever become relevant.
Should a working group ever grow so large and complex as to warrant its own governance policies it could certainly establishes those at that point.

**Comment by mayakacz** [comment]
> The boilerplate CHARTER.md from the LF is largely about governance process, whereas the discussion here seems mostly about clarity of scope.

Agreed. I'm looking for clarity of scope primarily.

I know the charter discussion is still ongoing, so makes sense to drop that until it lands (or wait until it does?).

**Comment by mayakacz** [comment]
Summarizing the latest comments, I would propose:


---

To **become** `incubating`:
* 1 TAC sponsor, and goes to TAC vote for inclusion
  + TAC sponsor agrees to attend WG meetings regularly
  + TAC sponsor does *not* need to have a formal role in WG, e.g., chair
* Proposal of scope for review by TAC
  + This is to help ensure limited overlap with existing WG
* Have met at least 5 times
  + For these, meeting notes (or ideally recordings) are public
* Have at least 5 interested individuals from at least 3 different organizations attending regularly

Once `incubating`:
* Part of quarterly TAC reviews
* [readme.md](https://github.com/ossf/project-template/blob/main/README.md) completed and approved by WG and by TAC
* Meets on a regular cadence. Meetings are public, recorded, and on the calendar
* May operate as part of the OSSF
* Has a clear [governance model and license](https://github.com/ossf/project-template)
* Has access to community resources (Zooms, YouTube channels, GitHub, Slack channels, etc.)
* Can request funding/other resources (subject to TAC/GB approval)

To **become** `graduated`:
* TAC vote
* Have met at least 20 times
* Have at least 10 regular members

Once `graduated`:
(same as `incubating`, plus)
* Have at least annual goals and metrics for success

---

Still to be determined/discussed (please weigh in!):
* How do we want to define membership of WGs consistently? (Can we use meeting attendance, e.g., maybe attended at least once in last quarter?)
* I put in tentative numbers for number of meetings and members above. Are these too high? Too low?
* Are there only two stages? Is `graduated` the right term for a working group (vs. a project say)? Can working groups be demoted or removed?

**Comment by dlorenc** [comment]
This looks good overall, the only one I'm not sure about is the # of meetings for incubating. How would a potential incubating WG have meetings before it gets access to the calendar, zoom, etc.?

**Comment by dcmiddle** [comment]
I think @mayakacz has a good summary. Maybe the next step forward here is a PR codifying it into e.g. `working-group-lifecycle.md`. Then we can iterate as necessary to refine and eventually commit the PR.

In parallel we should also add some sort of `end-of-life` / `inactive` stage, but I don't think that gates the initial commit.
