### ISSUE TITLE
[Proposed Initiative] OpenSSF OSS-SIRT Mobilization Plan Review

### ISSUE THREAD

**Issue by SecurityCRob** [ossf/tac#131]
The OSS-SIRT SIG(1) has completed revisions of the OpenSSf's Mobilization Plan Stream 5(2) and is now ready for TAC to review the plan(3) provide comments, and ultimately present the plan to the Governing Board for funding approval.  TAC feedback is critical to collect and react to any observed gaps so that they can be addressed,and also to ensure alignment with the overall technical direction and goals of the foundation.  

The SIG welcomes questions, comments, and feedback to help make the plan as robust and comprehensive as possible.  Issues(4) can be files against the plan in the SIG's repo or PRs(5) filed directly against the plan's contents themselves.  We would like to have all TAC feedback prior to 30Dec2022 to prepare to present for funding review in January 2023.

(1) - https://github.com/ossf/SIRT
(2) - https://openssf.org/oss-security-mobilization-plan/
(3) - https://github.com/ossf/SIRT/tree/main/plan 
(4) - https://github.com/ossf/SIRT/issues
(5) - https://github.com/ossf/SIRT/pulls

**Comment by brianbehlendorf** [comment]
Also +1 from Luke: https://lists.openssf.org/g/openssf-tac/message/655

**Comment by SecurityCRob** [comment]
This has been reviewed.  Closing this issue.
