### ISSUE TITLE
[Funding Request] - OSS-Security mailing lists ecosystem and support vulnerability disclosure

### ISSUE THREAD

**Issue by SecurityCRob** [ossf/tac#132]
We are seeking TAC review, comments, and ideally future approval for the OpenSSF to provide funding and support for a series of mailing lists and infrastructure(1) that is vital for open source coordinated vulnerability disclosure for maintainers and downstream software consumers.  These lists have served the community since 2008, and now seek to be re-homed to improve the resiliency and stability of those services to the larger open source ecosystem.  Questions and comments are welcome as we talk through and refine this proposal.  

(1) - https://docs.google.com/document/d/16r3IPnkVF6JteXNO5pmQ56hXMnlsZERihjCX6hHLvv8/edit#

**Comment by SecurityCRob** [comment]
Proposed email to GB (TAC review/feedback desired):

OpenSSF Governing Board – 
The TAC has reviewed and recommends funding for the following request:
•	OSS-Security Mailing Lists (1)
The public and private mailing lists currently housed in the Russian Federation by Openwall have supported the Linux and broader open source community since 2008, and have challenges continuing operations in the current geo-political climate.  The request(2) proposes that the OpenSSF funds new equipment, connectivity, transition to a more neutral location, and continued ongoing administration of the oss-security and distros mailing lists.  The proposal also outlines options for future expansion of services and support for more projects if desired.
In the proposal, OpenSSF/LF would not have any additional administrative overhead, as the system would be housed and supported in a third-party datacenter by SolarDesigner, the this is purely a request for support through funding the continuation and rehousing of these critical services.

(1)	- https://github.com/ossf/tac/issues/132
(2)	- https://drive.google.com/file/d/1xA8Iim7fUGR2IDie_KsIHUMehlknWFNY/

**Comment by joshbressers** [comment]
I would make this language stronger
"supported the Linux and broader open source community since 2008"

I think it's way bigger than that.

These lists have been used to coordinate many of the most critical vulnerabilities of the last decade. They are critical infrastructure for open source security.

**Comment by dlorenc** [comment]
Hey!

While I agree with many of the concerns discussed in the TAC call around this not being the best long term solution, this proposal does significantly improve the current state of the world.

I support this!

**Comment by SecurityCRob** [comment]
to address @joshbressers feedback, rewording to:

The public and private mailing lists currently housed in the Russian Federation by Openwall have supported the Linux and broader open source community since 2008, and have challenges continuing operations in the current geo-political climate.  Every major open source vulnerability in the last decade has been privately coordinated with maintainers through these lists, and once fixes were developed and tested, downstream consumers were publicly disclosed so they could take action.

**Comment by inferno-chromium** [comment]
I am supportive of this effort if we move this to a secure public cloud infrastructure, rather than hard-to-maintain/hard-to-secure physical infra in a random location. Happy to run this for free on Google cloud, similar to efforts like https://blog.llvm.org/posts/2021-11-02-apt.llvm.org-moving-from-physical-server-to-the-cloud/

**Comment by jhutchings1** [comment]
Restating the objection that I made during the TAC call where we discussed this: it's a terrible use of funds to stand up physical infrastructure to handle email in a world where we can easily use one of several SaaS services to do the same. I appreciate the sensitivity of the content on these mailing lists, but I do not think this is a problem that the OpenSSF should solve with our members' dues.

**Comment by david-a-wheeler** [comment]
Regarding this proposed change:

> Every major open source vulnerability

Don't say that, "every" is overly strong. Change "Every" to "Many" or similar.

**Comment by joshbressers** [comment]
Every is accurate in this context

**Comment by mrutkows** [comment]
It should be noted that many eventual CVEs are self-reported (and self-verified by the publishing org. via https://www.cve.org/ResourcesSupport/ReportRequest); for example, many CVEs have been reported directly from "open source" projects such as OSS Fuzz. which are governed by corporate (private) orgs. and their partners.

**Comment by joshbressers** [comment]
@mrutkows This is not my experience with the major vulnerabilities. They quite literally all end up on the distros-list for cooperation and coordination

I would gladly change my view here with some data

**Comment by SecurityCRob** [comment]
Vote Summary from email/mailing list - https://lists.openssf.org/g/openssf-tac/topic/96811001 , https://lists.openssf.org/g/openssf-tac/topic/96818564
Abhishek Arya 8feb2023 : +1 
Josh Bressers 7feb2023 : Yes
Dan Lorenc 7feb2023 : Yes
CRob - 7 Feb2023 : Yes
Aeva Black 7Feb2023 : Yes
Luke Hinds 7feb2023 : Yes
Bob Callaway 8Feb2023 : No

6 vote FOR, 1 votes AGAINST 
All TAC members participated in teh vote.

**Comment by hythloda** [comment]
I wanted to add a follow up that we are still working on the details of this but there is forward motion.

**Comment by hythloda** [comment]
This has been approved by all parties.

**Comment by SecurityCRob** [comment]
This issue has been resolved (funded).  I'm closing the ticket.  Thanks to everyone involved in review and commentary.
