### ISSUE TITLE
[Project contribution] IP policy and license review for Repository Service for TUF

### ISSUE THREAD

**Issue by joshuagl** [ossf/tac#136]
VMware would like to contribute [Repository Service for TUF](https://repository-service-tuf.readthedocs.io/en/latest/) to the OpenSSF as a sandbox project. The Securing Software Repos WG will sponsor the contribution.

As part of the submission we need "a one-time IP policy and license review with The Linux Foundation"[[1]](https://github.com/ossf/tac/blob/main/process/project-lifecycle.md#ip-policy-and-license-review), which this issue is created to track.

**Comment by znewman01** [comment]
CC @SecurityCRob can I nag you to ask what next steps are for this? I think @joshuagl can connect you to VMWare lawyers if needed.

**Comment by david-a-wheeler** [comment]
@joshuagl - thank you SO MUCH for the offer! I don't personally know the exact process, but I'll let OpenSSF operations know & they will know what the next step is for the policy/license review.

**Comment by SecurityCRob** [comment]
Here is the workflow:
https://github.com/ossf/tac/blob/main/process/incubation-process.png
The WG will need to craft a short presentation for the TAC to review and then everyone will get to talk to the nice folks with LF legal: https://github.com/ossf/tac/blob/main/process/project-lifecycle.md

**Comment by david-a-wheeler** [comment]
@joshuagl - Can you please send an email to me < dwheeler AT linuxfoundation DOT com > and Jory Burson < jburson AT linuxfoundation DOT org > ? We want to connect you to the right people.

A couple of questions:

1. COPYRIGHT: How is the project currently licensed? If it already has an acceptable OSS license, then great!! If not, what license(s) currently apply to the project, is the copyright holder willing/able to re-license under an OSS licence? My understanding is that this is <https://github.com/vmware/repository-service-tuf> and under MIT license (a clear OSS license!), so this is probably great, but we'd want to make sure.
2. TRADEMARK: Has the project been made available/used/released to the public under its current name? If so, is the trademark holder interested in transferring the mark to the LF? If yes, we probably need to execute some paperwork. If not, I suspect we need to have a discussion with the trademark owner and the board about renaming or sublicensing the mark.
3. Is it a spec? Documentation? Licenses other than an OSS License may apply.  I get the impression this is code.
4. Are there domain names involved?

Thanks!

**Comment by joshuagl** [comment]
Hi folks, thanks for the support here. I should have mentioned that we (@kairoaraujo and myself) also opened #137 (currently marked as Draft) at the same time as this issue by following the steps in the project lifecycle document. 

PR #137 adds a project lifecycle document for repository-service-for-tuf which includes project mission, current maintainers, and several project references.

@david-a-wheeler I will mail you and Jory ASAP. To your questions. 

> COPYRIGHT: How is the project currently licensed? If it already has an acceptable OSS license, then great!! If not, what license(s) currently apply to the project, is the copyright holder willing/able to re-license under an OSS licence? My understanding is that this is https://github.com/vmware/repository-service-tuf and under MIT license (a clear OSS license!), so this is probably great, but we'd want to make sure.

Yes, the project (url you mentioned and three sub-modules) is all MIT licensed.

> TRADEMARK: Has the project been made available/used/released to the public under its current name? If so, is the trademark holder interested in transferring the mark to the LF? If yes, we probably need to execute some paperwork. If not, I suspect we need to have a discussion with the trademark owner and the board about renaming or sublicensing the mark.

It is released to the public under its current name. I believe we are able to transfer the mark to the LF.

> Is it a spec? Documentation? Licenses other than an OSS License may apply. I get the impression this is code.
> Are there domain names involved?

This is code. The only domain currently involved is a readthedocs.io subdomain for documentation https://repository-service-tuf.readthedocs.io/en/latest/

**Comment by bobcallaway** [comment]
@david-a-wheeler any status update on this? If we're clear on the legal review I want to get this on the TAC calendar for discussion. Thanks!

**Comment by david-a-wheeler** [comment]
> On Feb 24, 2023, at 10:12 AM, Bob Callaway ***@***.***> wrote:
> @david-a-wheeler any status update on this? If we're clear on the legal review I want to get this on the TAC calendar for discussion. Thanks!

Per an email from Jory (below), for the purposes of the OpenSSF TAC incubation/project approval process, we're done with this step for now. Once the TAC has approved the project, we will initiate the transfer with the legal team.

My sincere thanks to all!

--- David A. Wheeler

**Comment by afmarcum** [comment]
@hythloda Is this complete?

**Comment by hythloda** [comment]
The process was completed and RSTUF is a project
