### ISSUE TITLE
update README with how to engage

### ISSUE THREAD

**Issue by christo4ferris** [ossf/tac#14]
Should update the README to make clear:
- TAC meetings open to anyone
- Use GH Issues to request/discuss agenda items
- link to calendar and indicate recurring meeting time/zoom link

**Comment by LindsayLF** [comment]
@christo4ferris I've completed the pull request to make these updates.

**Comment by estesp** [comment]
seems like this issue is complete? @christo4ferris

**Comment by rhaning** [comment]
TAC agreed that this is complete now. Closing issue.
