### ISSUE TITLE
VOTE - Vulnerability Disclosure working group sandbox project adoption

### ISSUE THREAD

**Issue by SecurityCRob** [ossf/tac#146]
TAC - The Vulnerability Disclosure group today ratified the member vote affirming our desire to adopt the OpenVEX spec and software as a software project and a SIG underneath our working group.  The majority of members participating in the vote approved the proposal (1): 11 affirming and 5 declining.  Additionally, 14 non-members expressed support in favour of adopting and 4 non-members voted against.  The latter opinions were not eligible to be formally inclusion in the working group vote. 

We have created a PR(2) for legal review & IP-transfer.  Pending that review, the working group is officially requesting the TAC to vote to confirm our desired course forward.

(1) - https://github.com/ossf/wg-vulnerability-disclosures/issues/125
(2) - https://github.com/ossf/tac/pull/145

**Comment by dlorenc** [comment]
+1, binding

**Comment by SecurityCRob** [comment]
+1

**Comment by inferno-chromium** [comment]
+1

**Comment by bobcallaway** [comment]
+1

**Comment by SecurityCRob** [comment]
The TAC voted 4 in favour of adoption with 3 members abstaining.  With the majority of members participating, this SIG was adopted by the Vuln Disclosure WG.
