### ISSUE TITLE
[For Review]: Open Source Security Foundation Vulnerability Disclosure Policy

### ISSUE THREAD

**Issue by JLLeitschuh** [ossf/tac#149]
The Vulnerability Disclosure WG has developed a proposal for an OpenSSF Vulnerability Disclosure Policy. This policy is for **outgoing** vulnerabilities, not incoming vulnerabilities. This is particularly relevant to the Alpha Omega project as it defines the policy under which vulnerabilities A-O finds are disclosed to maintainers.

At this time we are requesting both TAC and LF legal review of the policy. We are seeking approval to make this an official OpenSSF policy. This policy will define how all OpenSSF discovered vulnerabilities are disclosed to maintainers.

https://docs.google.com/document/d/1W2Xfw9i5pSA-0XbIw3a4kcW2o4PByxDbjcnWe9mlQwA/edit

Relevant Vulnerability Disclosures WG issue: https://github.com/ossf/wg-vulnerability-disclosures/issues/122

I'd like to also get on the agenda for the soonest TAC meeting to discuss this proposal.

**Comment by SecurityCRob** [comment]
This has been actively collaborated with the Vuln Disc WG.  Jonathan has sought a lot of input to date to get us here.

**Comment by dlorenc** [comment]
+1 on this, it's a great start!

**Comment by JLLeitschuh** [comment]
Now that this policy has been ratified by the TAC, where should it live? @SecurityCRob has proposed within this repository directly. Do others have other suggestions or opinions?

**Comment by steiza** [comment]
I think it'd be nice to make it available from openssf.org.

Where exactly, I'm not quite sure. Most of the existing policies (privacy policy, terms of use, antitrust policy) point back at Linux Foundation pages.

Maybe either as an FAQ item on https://openssf.org/about/, or as its own page linked off the "About" menu in the header?

**Comment by di** [comment]
Maybe at https://openssf.org/policies/vulnerability-disclosure-policy/?

**Comment by lehors** [comment]
Wouldn't it make sense to put it under https://openssf.org/resources?

**Comment by steiza** [comment]
I'm not sure if the TAC needs to own the decision of where exactly on the website this lands (maybe @JLLeitschuh can use his best judgement and work with LF staff on that) - but it at least sounds like we're aligned that the vuln disclosure policy should live somewhere on https://openssf.org/?

**Comment by JLLeitschuh** [comment]
There are two questions at play here I think. Where does the source live, and where is the published version hosted?

For the source version, which is what I'm more concerned about in the short term, I'm wondering what repository it should live in under the OSSF GitHub org.

**Comment by lehors** [comment]
Shouldn't the source be in the Vulnerability Disclosures WG repo?

**Comment by JLLeitschuh** [comment]
> Shouldn't the source be in the Vulnerability Disclosures WG repo?

Maybe? The counter argument to this is that, since this is an organization-level-policy, that has been ratified by the TAC, is that still the appropriate location for it to live?

**Comment by steiza** [comment]
> or the source version, which is what I'm more concerned about in the short term, I'm wondering what repository it should live in under the OSSF GitHub org.

Ah, thanks for this clarification!

I don't think this belongs in the TAC repo, just because the TAC reviewed / approved it. There's lots of stuff the TAC reviews / approves that aren't in the TAC repo.

I think https://github.com/ossf/foundation makes the most sense. In fact, that's the current home of the OpenSSF Content Policy.

**Comment by JLLeitschuh** [comment]
Any arguments for https://github.com/ossf/.github vs https://github.com/ossf/foundation ? Should all of the foundation docs be moved to the `.github` repo? Should the `.github` just be a mirror of the https://github.com/ossf/foundation repository?

**Comment by ljharb** [comment]
Yes, community health files all belong in the org's .github repo so that they can be the defaults for every repo.

However, things that aren't supported by github can go anywhere - although that's a reasonable place to put them.

**Comment by lehors** [comment]
> Shouldn't the source be in the Vulnerability Disclosures WG repo?
> 
> Maybe? The counter argument to this is that, since this is an organization-level-policy, that has been ratified by the TAC, is that still the appropriate location for it to live?

For what it's worth I think it would have made sense for it to go through the Vulnerability Disclosures WG first, before being brought up to the TAC. So I still think it would make sense to have the source/model file there.
The actual policy the TAC approved and we want to advertise can be on openssf.org possibly as link pointing to the foundation repo or https://github.com/ossf/.github if that makes more sense.

**Comment by JLLeitschuh** [comment]
> For what it's worth I think it would have made sense for it to go through the Vulnerability Disclosures WG first, before being brought up to the TAC.

This is the process that was followed

**Comment by lehors** [comment]
> > For what it's worth I think it would have made sense for it to go through the Vulnerability Disclosures WG first, before being brought up to the TAC.
> 
> This is the process that was followed

Oh righ, I took part in it. I should know! I'm getting old...
Ok but so to me, again, this primarily belongs to that WG so that's where it should be stored. This is the WG that where revisions would be discussed, right?

**Comment by znewman01** [comment]
Was that supposed to be @steiza assigned instead of me?

**Comment by bobcallaway** [comment]
> Was that supposed to be @steiza assigned instead of me?

yup

**Comment by hythloda** [comment]
[about](https://openssf.org/about/)
<img width="1088" alt="Screenshot 2023-06-02 at 9 42 48 AM" src="https://github.com/ossf/tac/assets/51727488/2d4e50aa-f861-4a72-8b68-6e72191062b6">

[Vul Disc](https://openssf.org/about/vulnerability-disclosure-policy/)

**Comment by hythloda** [comment]
Please let me know if anything needs changing on the website. I have direct access so it is very easy to change.

**Comment by SecurityCRob** [comment]
Derp.  Sorry about that!

Cheers,

CRob
Director of Security Communications
Intel Product Assurance and Security

**Comment by steiza** [comment]
Website content looks great; thanks @hythloda!

In terms of what repository this policy should live in, I still think https://github.com/ossf/foundation makes the most sense.

Really, the only purpose of https://github.com/ossf/.github should be for the public README on https://github.com/ossf. If we want to have a [template repository](https://docs.github.com/en/repositories/creating-and-managing-repositories/creating-a-template-repository), we could, but that should probably be separate from `ossf/.github`. But I'm also not sure that we **should** have policies in a template repository, unless we anticipate individual repos having their own versions of a policy. 

If the policy is OpenSSF wide, it seems like it should live somewhere like https://github.com/ossf/foundation.

**Comment by hythloda** [comment]
We like? https://github.com/ossf/foundation/pull/31

**Comment by SecurityCRob** [comment]
@bobcallaway @AevaOnline @lehors @dlorenc   please weigh in on your thoughts on placement for this so we can close this.

**Comment by lehors** [comment]
I feel like the main policy should go in the foundation repo and the template in the Vuln WG repo. But as I said on https://github.com/ossf/foundation/pull/31 "it seems that this is turning into a bikeshedding topic so feel free to ignore my preference if that helps getting to closure." :-)

**Comment by bobcallaway** [comment]
+1, we've spent more time talking about it instead of just merging it

**Comment by SecurityCRob** [comment]
@JLLeitschuh please follow Arnaud's suggestion and get the template located within the vuln wg's repo, and we'll post the text up at the foundation level, as per https://github.com/ossf/foundation/pull/31 then we can close this out.

**Comment by david-a-wheeler** [comment]
Here's a quick clarification to prevent confusion:

This issue is *only* for an *outgoing* vulnerability disclosure policy.

The Vulnerability disclosures WG has ALSO separately drafted an *INCOMING* vulnerability disclosure policy, that is, on how to report vulnerabilities to the OpenSSF (and how the OpenSSF should handle them). You can see the discussion & content of the draft INCOMING vulnerability disclosure policy here: <https://github.com/ossf/wg-vulnerability-disclosures/issues/128>. I'd like to see that work eventually come to fruition, but it's separate & don't want them confused with each other :-).

**Comment by SecurityCRob** [comment]
@hythloda are we good to close this?  the link exists on the foundation webpage, correct?
