### ISSUE TITLE
Proposal: Ensure all OpenSSF GitHub repos have private security vulnerability reporting enabled

### ISSUE THREAD

**Issue by david-a-wheeler** [ossf/tac#150]
I propose that OpenSSF enable private security vulnerability reporting on *all* GitHub repositories in its main GitHub organization (ossf). This would make it easy for security researchers/finders to privately report their findings.

The OpenSSF Vulnerability Disclosures WG agreed earlier today to recommend doing this as part of their guide:
https://github.com/ossf/oss-vulnerability-guide/pull/47

The OpenSSF Best Practices badge project already does this, and other OpenSSF projects may do this as well. However, it's possible to change the OpenSSF organizational setting to do this on both (1) all new repositories and (2) all existing projects. I think we should do that, because then it's easy for anyone to report problems, AND we'll set a good example.

Thanks!

**Comment by ljharb** [comment]
Seems like a no-brainer - any objection to me just unilaterally doing it? We can always turn it off later.

**Comment by joshuagl** [comment]
Agree, this should be the default for all OSSF repos.

**Comment by SecurityCRob** [comment]
+1

Cheers,

CRob
Director of Security Communications
Intel Product Assurance and Security

**Comment by ljharb** [comment]
I'll go ahead and enable it for everything now, as well as for new repos.

Please comment or reopen if there's any issue with this :-)
