### ISSUE TITLE
TAC question: where should ossf github org policies/tools live?

### ISSUE THREAD

**Issue by ljharb** [ossf/tac#153]
Hi folks!

I asked this on Slack but figured here would be better for the long term.

I'm going to be writing up some repo management policies (via PR, seeking TAC approval, ofc) and am trying to figure out the best place for them to live. A top-level dir in this repo seems appropriate?

Also, I've written a very rough tool in the (currently private, but will be made public once a home is decided) https://github.com/ossf/github-org-access-scraper repo to be able to audit how many repos still have individuals (as opposed to teams) with access - should that also live in this repo, instead of its own?

**Comment by david-a-wheeler** [comment]
It's up to the TAC, but here are my two cents.

I think general technical policies belong in ossf/tac. However, nontrivial tools probably should go into a separate repo, as they would probably be maintained separately. The TAC shouldn't have to approve every code PR, they're already busy :-).

**Comment by ljharb** [comment]
Pending further direction, I've opened #155 to add initial policies, and I'll leave the tool in a separate repo.
