### ISSUE TITLE
Add settings.yml to TAC repo .github

### ISSUE THREAD

**Issue by caniszczyk** [ossf/tac#16]

**Comment by dcmiddle** [comment]
see also #28

**Comment by SecurityCRob** [comment]
Hello.  As part of 2022 backlog grooming, each open TAC issue is being reviewed for applicability/completeness.  Has this request been completed?  If so, can that be noted in a comment please.  If we do not here back from you within two weeks, this issue will be closed (23March2022).  Thank you.

**Comment by lehors** [comment]
@SecurityCRob this file still doesn't exist so that issue has clearly not been completed.

**Comment by steiza** [comment]
See https://github.com/ossf/tac/issues/28
