### ISSUE TITLE
Update SIG processes and ensure consistency & alignment with WG & project processes

### ISSUE THREAD

**Issue by SecurityCRob** [ossf/tac#161]
TAC has good documentation around new project creation & lifecycle & working group lifecycle- https://github.com/ossf/tac/blob/main/process/project-lifecycle.md , https://github.com/ossf/tac/blob/main/process/working-group-lifecycle.md

Comparability, SIG documentation is lacking -  https://github.com/ossf/tac/blob/main/process/sig-lifecycle.md

No documentation exists today for Special Interest Funds (SIFs) or Affiliated Projects (APs)

The TAC should ensure clearly documented processes exist that describe:
- Special interest Groups(SIG) have an adoption and lifecycle process that describes stages from beginning to possible eventual retirement of these groups
- gives/gets for each level of the SIG lifecycle should be 
- Document who evaluates and votes upon creation/retirement/modification of these groups - TAC, WG, other?
- SIFs and APs should be clearly documented for proposal, adoption, and lifecycle processes
- documentation/language updated in WG/SIG charters, readme's, & security.md's that accurately describes desired processes for membership criteria, membership ladders/rewarding contributions, documentation how group votes are conducted and eligibility requirements

**Comment by SecurityCRob** [comment]
The guidance does not need to be heavy, but should inform folks any required steps or things to care about so they can run with it and go do great things.

**Comment by steiza** [comment]
We might need to update https://github.com/ossf/tac/blob/main/organizational-structure-overview.md as part of this work.

Currently that document describes SIGs as reporting to a WG, not the TAC (although even if we keep that structure, we can of course provide lightweight guidance on adoption criteria and lifecycle process).

**Comment by AevaOnline** [comment]
The existing documentation does not cover SIFs or APs, as my previous attempts to quantify those were post-hoc and encountered organizational challenges.

On the topic of WGs and SIGs, refining the process from last year, and normalizing it across WGs and SIGs, seems entirely appropriate to me. Are there specific areas of friction or fragmentation that folks would like to address?

**Comment by hythloda** [comment]
This was brought up in the TAC with @torgo @ware @bobcallaway @steiza and @hythloda 
Do want a zoom meeting to get this started? Or async?

**Comment by ware** [comment]
I'll defer to others.  I can do either.

**Comment by lehors** [comment]
> We might need to update https://github.com/ossf/tac/blob/main/organizational-structure-overview.md as part of this work.
> 
> Currently that document describes SIGs as reporting to a WG, not the TAC (although even if we keep that structure, we can of course provide lightweight guidance on adoption criteria and lifecycle process).

Are you saying we should allow SIGs to be reporting to the TAC or all SIGs should report to the TAC?
I think the former is fine. This would be consistent with allowing projects to report directly to the TAC. I don't think we want all SIGs to report to the TAC though. That'd be a major change from how things have been done and I'm not sure what the gain would be.
What I think we might want to do is define the process WGs need to follow to create SIGs so that it's done consistently throughout the org.

**Comment by hythloda** [comment]
> This will not be an easy issue to solve, but at the same time we have to start somewhere. To that end I have started [OpenSSF Workstream Taxonomy](https://docs.google.com/document/d/1gwEdJM8WrgLJ3fvKXBfmwSS8G5TzD7rx-3Dwfzuq4I8/edit?usp=sharing) to cover scope, questions, and exit criteria, as well as existing hierarchy and references. Let's start the process by asynchronously collaborating there, and then use that to determine next steps.

This is a great start!  @torgo @ware @bobcallaway did you get a chance to see it?

**Comment by hythloda** [comment]
This is something that really needs some thoughts/ideas/comments. Just today I noticed that we have Alpha-Omega defined twice in our Intro:
<img width="881" alt="Screenshot 2023-06-08 at 4 16 17 PM" src="https://github.com/ossf/tac/assets/51727488/21c407ff-fee5-4c87-a126-cd282f4bd1c6">

**Comment by SecurityCRob** [comment]
I agree, we should figure out what kind of thing it really is and manage it appropriately from there.  I would suggest A-O be considered a “project” under the IDing Sec Threat WG, and it aligns and reports up through them, understanding that the project itself has a special funding/management structure (as a SIF/AP).  This will help streamline and make our reporting and organization more consistent as opposed to spinning up additional work/streams aka “corner cases”, “special snowflakes”, et.al..

Cheers,

CRob
Director of Security Communications
Intel Product Assurance and Security

**Comment by steiza** [comment]
Today I learned about [OpenSSF Associated Projects doc](https://docs.google.com/document/d/1yr_l2KZdH8gZ2kBbVn_AEGNY0_unSB71_2_bO-82Ew4/edit?usp=sharing), which might be helpful after we complete the SIG part of this workstream.

**Comment by david-a-wheeler** [comment]
My understanding was that "project"  was to be used for efforts that focused on code, while SIG was to be used for efforts that didn't focus on code. E.g., the MFA distribution effort would be considered a SIG. I don't think everything should have to report directly to the TAC; the TAC is busy enough & we don't want all things to bottleneck through a few overworked people. Most SIGs are part of WGs; we need to make sure the WGs are monitoring their SIGs, and then the TAC doesn't have to do everything.

If I'm mistaken, or a change in direction is desired, that's okay too, making it clear is the key.

**Comment by lehors** [comment]
Is anyone saying all SIGs should report to the TAC? I think we should make it possible to have SIGs under the TAC but I expect the majority to still report to a WG.

**Comment by SecurityCRob** [comment]
changes have been merged to align all TI-types with consistent stages: Sandbox, Incubation, Graduation, and Archive.  "Gives and Gets" are being discussed as part of the Ops Model work, and will added into TI documentation once agreed upon.
