### ISSUE TITLE
Create a youtube channel for recordings

### ISSUE THREAD

**Issue by kimsterv** [ossf/tac#17]

**Comment by kimsterv** [comment]
Thanks!

**Comment by MarcinHoppe** [comment]
How do request uploading the video to this YouTube channel?

**Comment by LindsayLF** [comment]
Hi @MarcinHoppe! All WG leads have access to upload now, please let me know if you do not receive the invite.  Thanks!

**Comment by MarcinHoppe** [comment]
@LindsayLF I got the invite, thanks!
