### ISSUE TITLE
GUAC Incubation Application

### ISSUE THREAD

**Issue by mlieberman85** [ossf/tac#172]
We would like to go for Incubation, but would be open to Sandbox as well if due diligence determines GUAC is not ready yet. If accepted we would plan to apply to fall under the Supply Chain Integrity WG.

### List of project maintainers
The project must have a minimum of three maintainers with a minimum of two different organizational affiliations.
* "mlieberman85", "Michael Lieberman", "Kusari"
* "mihaimaruseac", "Mihai Maruseac", "Google"
* "lumjjb", "Brandon Lum", "Google"
* "pxp928", "Parth Patel", "Kusari"
* "SantiagoTorres", "Santiago Torres", "Purdue University"
* "rgreinho", "Rémy Greinhofer", "Citi"

### Mission of the project
  * GUAC (Graph for Understanding Artifact Composition) aims to fill in the gaps by ingesting software metadata, like SBOMs, SLSA attestations, and mapping out relationships between software. When you know how one piece of software affects another, you’ll be able to fully understand your software security position and act as needed. GUAC gives you directed, actionable insights into the security of your software supply chain.

### Project adoption
I will include quotes from adopters: 
  * With the growing number of software supply chain security (SSCS) data, tools that allow us to find relevant information are crucial. Guac, providing graph representation of software packages, dependencies, vulnerabilities, attestations, etc. is a great tool for use cases in this domain. With mechanisms to ingest and certify data from various sources and GraphQL API to later query those data, we see it as a good foundation for our current and future SSCS efforts. Being a true open source initiative with a welcoming community is just a plus. -- Dejan Bosanac, Red Hat
  * At Yahoo, we have found immense value and significant efficiency by utilizing the open source project GUAC. GUAC has allowed us to streamline our processes and increase efficiency in a way that was not possible before. It allows us to ingest large number of SBOMs and also provides an interface to visualize the current state of images & packages used at Yahoo in real time. We look forward to continuing to utilize GUAC and contribute to its growth in any way we can. -- Hemil Kadakia, Yahoo
  * As the CTO of ClearAlpha, I can't recommend GUAC enough for companies looking to boost their software security. GUAC's innovative approach to software supply chain security helps uncover hidden gaps and threats as we’re downloading dependencies and building apps, making it a perfect fit for our “solve it earlier” mindset at ClearAlpha. It also lines up with our commitment to transparency, open-source principles, and continuous learning. GUAC works well in teams practicing the rugged software manifesto, focusing on strong coding practices, constant testing, and automated tools to enhance security. Plus, its ability to trace risks back to their source aligns with our proactive risk awareness goals, enabling companies to spot and tackle potential issues early on. GUAC is just a fantastic tool to help any organization improve their software security with principles we all should value. If you're a tech founder, you'll definitely want to have GUAC on your team! -- Sean Terretta, ClearAlpha
  * GUAC came along as an open-source software at the right time helping us pivot away from building a bespoke solution and involving ourselves with the best minds behind the project. The value we see with GUAC is its flexibility and plugin architecture leading up to helping the users achieve compliance at different levels. The biggest benefit of GUAC has been producing it in the open with a widespread community behind it, from Google to Kusari and others. As the industry progresses, the threats to the software supply chain will become more complex, and relying on a tool backed by people with many years of experience in the area would make things easier for Guidewire to consume. -- Anoop Gopalakrishnan, Guidewire Software

### Governance
  * https://github.com/guacsec/guac/blob/main/GOVERNANCE.md

### IP policy and licensing due dilligence
  * TAC docs make this process unclear. We will work with LF on any due diligence, just point us in the right direction.

### Project References

| Reference          | URL |
|--------------------|-----|
| Repo               |  https://github.com/guacsec/guac   |
| Website            |  https://guac.sh   |
| Contributing guide |  https://github.com/guacsec/guac/blob/main/CONTRIBUTING.md   |
| Roadmap            |   https://github.com/guacsec/guac/blob/main/ROADMAP.md  |
| Demos              |  https://youtu.be/mkZJcIkOF8Q    |
| Other              |   https://docs.guac.sh  |

**Comment by SecurityCRob** [comment]
Can the group come prepared to present this proposal to the 13June TAC call?

**Comment by dlorenc** [comment]
Thanks for the proposal! Looking forward to reviewing and discussing!

**Comment by mlieberman85** [comment]
See: #178  and #179 for the PR and IP release issue.

**Comment by afmarcum** [comment]
Application approved and PR merged.
