### ISSUE TITLE
TAC Meeting Agenda : Prioritization

### ISSUE THREAD

**Issue by omkhar** [ossf/tac#177]
I would like the TAC to review my proposal for [improving prioritization, focus and execution](https://docs.google.com/document/d/1p313ZP2JuiUOr9LRVI_Jmbs5w4lkwhDHQc7cNroq6N0/edit#heading=h.qb6z3tcivry).

Please put this on the agenda for the next TAC (06/27/2023). I will respond to comments in the doc leading up to this meeting. My goal is to Inform the TAC regarding the approach we'll be taking going forward.

**Comment by dlorenc** [comment]
Thanks @omkhar!

**Comment by SecurityCRob** [comment]
I’ve added this to the 27 June Agenda.

@TAC please review and provide feedback.  Thanks.

Cheers,

CRob
Director of Security Communications
Intel Product Assurance and Security


From: Omkhar Arasaratnam ***@***.***>
Sent: Thursday, June 15, 2023 6:36 PM
To: ossf/tac ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ossf/tac] TAC Meeting Agenda : Prioritization (Issue #177)


I would like the TAC to review my proposal for improving prioritization, focus and execution<https://docs.google.com/document/d/1p313ZP2JuiUOr9LRVI_Jmbs5w4lkwhDHQc7cNroq6N0/edit#heading=h.qb6z3tcivry>.

Please put this on the agenda for the next TAC (06/27/2023). I will respond to comments in the doc leading up to this meeting. My goal is to Inform the TAC regarding the approach we'll be taking going forward.

**Comment by steiza** [comment]
@omkhar we talked about this at the past TAC meeting and you got feedback on the doc - can we close this, or is there anything else you need here?

**Comment by omkhar** [comment]
I had committed to returning to the TAC on 11/25 with a project plan, including proposed updates. Should I create another issue for that or should we hold this issue open?

**Comment by steiza** [comment]
Reusing this issue is fine, thanks!

**Comment by SecurityCRob** [comment]
No, we can just continue to comment on Issue 177.  I noted your imminent return for the 25th in our agenda.

Cheers,

CRob
Director of Security Communications
Intel Product Assurance and Security

**Comment by afmarcum** [comment]
Can this issue be closed based on Omkhar's Oct 3 update?

- Original governance work proposed is being executed by the tool belt and ops model. And that future updates can come from them.
- Most of that work has been taken on by the toolbelt group, thank you for that!
- Sarah Evans etc. has been picking up MVSR work.
- Look for future results in those areas.

**Comment by SecurityCRob** [comment]
Per 3Oct2023 TAC call, future updates will be given via the Toolbelt initiative and the Operation Model group
