### ISSUE TITLE
Inform TAC on EUWG - Open Source Software Consumption Manifesto 

### ISSUE THREAD

**Issue by thiswayman** [ossf/tac#180]
tl;dr The EUWG has developed a set of 15 principles in the spirit of the Agile Manifesto that we are putting forward as a foundational commitment to improving software supply chain security through open source consumption best practices. The intent of the manifesto is not to be prescriptive but to provide high-level guidance to aid organizational thinking of open consumption.

You can view the manifesto here: https://github.com/ossf/wg-endusers/tree/main/MANIFESTO

**Comment by di** [comment]
Hi @thiswayman, thanks for sharing. I'm not sure what's being asked here, are you looking for a review/endorsement by the TAC, or do you just want to make us aware this exists?
