### ISSUE TITLE
OpenSSF Strategic Alignment "summit"

### ISSUE THREAD

**Issue by SecurityCRob** [ossf/tac#186]
To ensure alignment and to highlight areas to jointly collaborate across the OpenSSF, we propose to hold an extended meeting to assemble the TAC, WG & project leads, along with other key contributors across the OpenSSF to discuss our objectives and strategic plans for the upcoming year.  We will review the OpenSSF's prioritized goals and seek to align our work along those lines.  A Doodle poll will be setup seeking to meet the week of 21Aug for the TAC, WG & projects leads to find an agreeable time to start this discuss.  Any community members interested are welcome to join, listen, and contribute.  Based on the initial meeting, we also could physically meet to real-time collab at events such as the upcoming OSS-EU conference.

Topics to collaborate on:
- understanding current priorities/direction for the OpenSSF
- understanding current WG/SIG/project activities and how those can be aligned to the OpenSSF goals
- identify areas of wg/sig collaboration
- begin work on MVSRs for each WG

Thanks everyone, we're looking forward to meeting and jointly  moving us all forward!

**Comment by ran-dall** [comment]
I really like the initiative. Count me in.

**Comment by scovetta** [comment]
Love it! Yes!

**Comment by joshuagl** [comment]
This sounds great!

**Comment by xcorail** [comment]
I am interested - I am traveling the week of the 21, but if I can attend I will!

**Comment by caabernathy** [comment]
Yes, much needed. +1

**Comment by hythloda** [comment]
We have a [template/guide for the MVSR ](https://docs.google.com/document/d/1p6hOlE4eH1xvQ9pP7swCH2tmIJJ-6G3vnYI8MDzSCQk/edit)to help get WG started on this process. The term might be new so we have divided it into simple questions. Let me know if the template needs to be changed and feel free to add comments.  We can iterate on the doc until the process is clear, easy and useful!

**Comment by mlieberman85** [comment]
+1

**Comment by sevansdell** [comment]
Interested!

**Comment by camaleon2016** [comment]
+1

**Comment by balteravishay** [comment]
Great idea! Looking forward to it.

**Comment by gkunz** [comment]
+1

**Comment by SecurityCRob** [comment]
It looks like our meeting will be Aug 23, 2023 from 2-4p ET.  I'll get the poll wrapped up and send out homework/pre-reads we'd like everyone to do/review prior to the call.  Thanks all for participating.  Looking forward to getting together and collaborating.  We also have availability of a room at OSS-EU we can physically meet to whiteboard out anything amd/or work on IRL: Room 5G is reserved for OpenSSF on Wednesday, September 20th from 12:30pm - 2:30pm.

**Comment by robservatory** [comment]
This is brilliant - and proof that I get way to much email and so sometimes
things fall through the cracks.  I am sure no one else here can relate.  ;-)

Would love to be a part if not too late.  Assuming this is virtual?  And
that the reference to a room at OSS-EU is talking about the Summit in
Bilbao Spain Sept 19-21?

-Rob

**Comment by SecurityCRob** [comment]
Meeting time has been selected and calendar entry created.  Please join us on 28Aug from 2-4pm ET to talk about all the awesomeness that goes on around the OpenSSF.

**Comment by SecurityCRob** [comment]
Recap email sent to participants "[RFC] OpenSSF Strategic Alignment Summit" on 1Sept 9:34a et.  Thank you to everyone that participated and expressed interest in this effort.

**Comment by hythloda** [comment]
Any interest in a follow up?

**Comment by jkjell** [comment]
I feel like we barely scratched the surface. ☺️ Was there an in person follow up at OSS EU?

**Comment by SecurityCRob** [comment]
Strategic Summit II will be on 13Nov from 3-5pm ET.  
Doodle poll results - https://doodle.com/meeting/organize/id/epznrnQb
Agenda & meeting invite to follow

**Comment by SecurityCRob** [comment]
> I feel like we barely scratched the surface. ☺️ Was there an in person follow up at OSS EU?

Sadly, it did not work out to have a F2F in Bilbao.  We did just schedule a 2nd meeting for 13Nov that you are welcome to join us in!

**Comment by SecurityCRob** [comment]
Here is the recap email text sent out to the group on 16Nov2023.  Closing this issue and am looking forward to the new periodical call to collaborate. 

First off, let me thank everyone for taking the time to show up and participate in our second “summit”.  I appreciate all of your feedback and contributions in helping make us a more effective group!  We focused out time speaking to 4 Questions:

1.	Where do you see overlap in our Technical Initiatives (Tis aka our WGs, SIGs, Projects, etc.)?
2.	What do you propose we do about overlap areas?
3.	How can we collaborate better together and help each other across the TIs to fulfill our MVSR?
4.	How can we get better awareness around our TIs/projects to drive up adoption?

My Notes/Key take-aways
•	Will now morph into a monthly WG Lead call (yay) - @CRob to work with Staff to get doodle out to find reoccurring time, build out agenda, etc.  Looking for someone to act as facilitator/lead of this
•	Commitment to form “Tiger Team” [It’ll be GREAT!] to see how all 4 “risk dashboards” might be streamlined/better coordinate/collaborate/dedupe (potential merging of efforts into an “Observability/Metrics WG” that houses all the efforts - Looking for someone to help lead/facilitate this analysis
•	Request to have R&R publicly documented for all “types” of folks within the org (TAC, GB, Committee, assorted staff roles) so members can understand who people are, what they do/should be doing, and how to reach out for assistance - @CRob for WG & TAC R&R, @Staff for staff R&R
•	Universal lament at the quality of onboarding/explanatory materials around the foundation and its groups (for new or old participants).  We all should probably make this a priority on how to solve (not sure if it is a new committee, or some kind of sig somewhere attached to existing effort) – Looking for someone to help lead/facilitate working with Staff & DevRel Committee
•	There is a need for a foundation-wide taxonomy/dictionary/persons/etc. – Looking for someone to lead/facilitate this
•	Playing off one of Dana’s ideas, perhaps we have a quarterly/bi-annual “theme” that we showcase and encourage additional effort on (other stuff can continue as normal, but themed-things get special handling or whatever, a cookie or sticker)
•	Group desired to create a curated conference list to present OSSF things “outside the bubble” to devs, sec, .govs, etc.
•	We’d like to  create a “WG_Updates”/”HONK!” slack channel to drop “tweet-like” meeting updates post-calls to help share what’s going on near-realtime @CRob to work with staff + leads to create channel and notification process & share to community for awareness
•	There were some great observations and suggestions on the “Now, Next, Future” board the group should consider as we work together in the future.

Keep the good thoughts coming, ideally we can start to directly work on these and other ideas the group has as we shift to the new monthly calls!  The link to find a new time is listed below(4).  Patches, comments, and feedback are ALWAYS welcome!  Thanks again Fam!


(1)	– Meeting Notes -  https://docs.google.com/document/d/1-_88dj0IbPFY1Nttd2kiSTF_DstVz3UUcF9lqyjzKT4/edit 
(2)	– Now, Next, Future board - https://metroretro.io/BOADAGUU2YR7
(3)	– Meeting Recording - https://zoom.us/rec/share/RAYqSnJi4A-pORcE_kKZvblXO2W6XNd1muUzIo1_tC_HWmmkHMtdVkBlRN4qljRy.uvLrOILe_6AsVs1Y
(4)	– New WG Leads Meeting doodle poll - https://doodle.com/meeting/participate/id/dJPkP2ga
