### ISSUE TITLE
Governance work update

### ISSUE THREAD

**Issue by afmarcum** [ossf/tac#187]
Please review the summary of governance work completed since the last governing board as an update from OpenSSF staff.  https://docs.google.com/document/d/1k3t7h9jazMms_P3aIX3VJUsrX-vcXwmrxxSikiZKF9E/edit?usp=sharing

**Comment by SecurityCRob** [comment]
Thanks for the summarized update @afmarcum .  Are there any additional actions you'd like the TAC to take on this beyond reviewing (which we did on the 8aug TAC call)?

**Comment by afmarcum** [comment]
No additional actions. Thanks for reviewing!
