### ISSUE TITLE
LF AI & DATA | ML  security committee + OpenSSF proposal

### ISSUE THREAD

**Issue by therealnb** [ossf/tac#188]
As part of the TAC review of the proposed AI / ML Working Group (see https://github.com/ossf/tac/issues/175) we decided to make sure we are not reinventing the wheel and to collaborate with the LF AI & DATA / ML security committee (see https://wiki.lfaidata.foundation/display/DL/ML+Security+Committee).

After several meetings with Alejandro, we have this proposal:
https://docs.google.com/document/d/1eMp5jksdNxWDtg_aQ2yoc6jYUAczhx_KPPuDrCiS8lQ/edit#heading=h.zbq51mx0m2ci

We are discussing this further in the LF AI & DATA / ML security monthly meeting. The aim is for good communications across orgs and to share resources.

The purpose of this ticket is for information only. There is no action required of the TAC at this time. The current plan is for https://github.com/ossf/tac/issues/175 to be revisited in a few months time.

**Comment by SecurityCRob** [comment]
Will the group be ready to come back and talk to the TAC on 5Sept?

**Comment by therealnb** [comment]
I believe so.

We have a collaboration in progress with LF AI & DATA | ML security committee. We continue to have the occasional interesting meeting.

We have some work in (slow-ish) progress.

The biggest blocker seems to be the nebulous state of the group. The TAC needs to decide if there is a place for the volunteers in the openssf, or whether we should wind up the group and go elsewhere. 

I'll mention this to the others. Thanks!

**Comment by therealnb** [comment]
@SecurityCRob do you want to discuss this ticket, https://github.com/ossf/tac/issues/175 or both?

**Comment by SecurityCRob** [comment]
The AI/ML working group was accepted by the TAC in our 5Sept2023 call.  Welcome aboard!  Dan A & staff will assist in getting you setup and on the path to collabing!

**Comment by david-a-wheeler** [comment]
FYI: I put a quick README stub in the new working group's repo here: https://github.com/ossf/ai-ml-security

I'm sure it needs improving, but I thought it'd best easier to have *something* to edit.

Welcome aboard, our new WG!!
