### ISSUE TITLE
TAC meeting agenda: Secure Software Guiding Principles

### ISSUE THREAD

**Issue by jkmarz** [ossf/tac#193]
Requesting slot on 5 September TAC agenda to bring finalized Secure Software Guiding Principles (SSGP) for TAC vote (pending outcome of BEST WG discussion on 29 August).   

[https://github.com/ossf/wg-best-practices-os-developers/blob/main/docs/SecureSoftwareGuidingPrinciples.md](https://github.com/ossf/wg-best-practices-os-developers/blob/main/docs/SecureSoftwareGuidingPrinciples.md)

**Comment by SecurityCRob** [comment]
Can do!

**Comment by SecurityCRob** [comment]
The WG updated the SSGP to v1.0 and is ready to share with the GB.  We're requesting TAC review and hopefully to recommend to the GB for their feedback:  https://github.com/ossf/wg-best-practices-os-developers/blob/main/docs/SecureSoftwareGuidingPrinciples.md

**Comment by bobcallaway** [comment]
I won't make the TAC meeting today, but I'm supportive of this.

**Comment by david-a-wheeler** [comment]
The TAC unanimously voted to approve the principles and send them to the GB for ratification.
