### ISSUE TITLE
Confirm that the documented Archive Process been approved and ready for use

### ISSUE THREAD

**Issue by afmarcum** [ossf/tac#197]
I would like to help facilitate the implementation and adherence to the [project lifecycle](https://github.com/ossf/tac/blob/main/process/project-lifecycle.md) process documented by the TAC, starting with moving dormant or complete projects through the Archive Process. 

Please review and confirm that this process is approved for use so that I can begin submitting PRs for applicable projects.

Follow-up question: does this Archive Process apply to WGs (End-of-Life) and SIGs (Inactive) because there is not a process currently outlined for either?

**Archived**
Open source projects have a lifecycle and there are times when projects become inactive due to a variety of reasons. There are also cases where a project may no longer want to be supported by the OpenSSF, or the OpenSSF TAC may no longer wish to recommend the use of a project. Archiving happens through a vote of the TAC, and can be requested by the corresponding project's lead(s) or a TAC member.

**Archiving Considerations**
When voting on a proposal to archive a project, TAC members may consider:

- If the project has consistently met the Project Requirements.
- If the project still supports the OpenSSF mission.
- If the project's inactivity or inconsistent maintenance presents a user security risk.
- If the project's design or approach is no longer a recommended best practice.

**Archive Process**
Archived projects are no longer in active development and are only archived after a TAC vote.
What does archiving for an OpenSSF project mean?

- OpenSSF will no longer provide budgetary, event, or marketing support for the project.
- Trademarks and domain names of archived projects are still hosted by the OpenSSF and the Linux Foundation.
- Project maintainers may request trademark transfers from the OpenSSF and the Linux Foundation.
- OpenSSF can provide services such as documentation updates to help transition users.

**To archive a project:**

- A proposal must be made to the TAC or WG repo.
- The TAC or parent WG will inform the project maintainers, OpenSSF end user community and wider community of all archiving proposals.
- The proposal must remain open for at least 2 weeks of discussion after the maintainers are informed.
- A vote must be finalized with 2/3 approval from the TAC or parent WG.

See [Submission Process](https://github.com/ossf/tac/blob/main/process/project-lifecycle.md#submission-process) below and the [Archive application](https://github.com/ossf/tac/blob/main/process/templates/PROJECT_NAME_archived_stage.md).

**Submission Process**
**Project creation or change of lifecycle stage**
For initiating the creation of a new project or for requesting a change of a project's lifecycle stage, an application must be submitted to the TAC. To this end, a maintainer of the project (or anyone in the case of Archived projects) creates a PR in this repository with the following changes:

- A new file in the project-lifecycle-documents directory containing all information requested for a project creation or a lifecycle change review. This file must be based on the template for the respective lifecycle stage in the templates directory. The PROJECT_NAME_ prefix of the template must be replaced by the project name.
- Modification of the table listing all projects in the [README](https://github.com/ossf/tac/blob/main/README.md) of this repository by either updating the status field of the project in the table to the intended new lifecycle stage or by adding the project to the table in case of a project creation request.

The TAC members review the PR and upon approval according to voting criteria defined in the [OpenSSF charter](https://cdn.platform.linuxfoundation.org/agreements/openssf.pdf), the PR can be merged. The new project has been created and the new lifecycle stage is in effect after the PR is merged.

**Application for archiving of a project**
**Reasons for archiving**
Projects may become inactive over time or do not want to be supported by OpenSSF any longer.

- "description of why this project should be archived"

**Comment by lehors** [comment]
Yes, this is indeed the current process we are supposed to be following. It was approved by the TAC on 09/01/22: https://lists.openssf.org/g/openssf-tac/message/580 and the merge of PR #112.

Your help implementing it is very welcomed!

**Comment by afmarcum** [comment]
> Follow-up question: does this Archive Process apply to WGs (End-of-Life) and SIGs (Inactive) because there is not a process currently outlined for either?

@lehors I want to call attention to the additional question that was hidden within the larger issue (quoted above). There is similar discussion happening about the initiation phase.

**Comment by afmarcum** [comment]
If there is no other feedback, I am good to close this issue.

**Comment by SecurityCRob** [comment]
+1
