### ISSUE TITLE
Specification development structure

### ISSUE THREAD

**Issue by lehors** [ossf/tac#204]
Several specification development efforts are already underway within OpenSSF (e.g., SLSA and S2C2F) and more are being proposed.

Because the charter defines "Projects" as a Technical Initiative that is "software focused" it's been assumed that specification development don't belong in a Project and therefore ought to be in a WG or SIG. However, the lifecycle of a SIG or WG doesn't fit well with spec development which is closer to software development.

With that in mind I had a look at the project lifecycle with a focus on what it would take to make suitable for specification development and actually very little need to be changed. I'd like to propose that we consider extending the definition of a Project (which we can get endorsed by the GB with a modification of the charter) and will submit a PR to update the project lifecycle definition accordingly.

**Comment by lehors** [comment]
> "Project" is defined by the OpenSSF charter, so technically I think you'd need to get a charter change approved by the governing board. This seems like something easily agreed to, it would just need to be formally proposed.

You apparently missed that part: "extending the definition of a Project (which we can get endorsed by the GB with a modification of the charter)" :-)

**Comment by david-a-wheeler** [comment]
You're right; you even stated it so clearly that no one could have possibly missed it (!?).

Thanks for thinking of that ahead-of-time, it sounds good.

**Comment by SecurityCRob** [comment]
+1

**Comment by SecurityCRob** [comment]
We've merge the spec-language into projects.  Thanks Arnaud!
