### ISSUE TITLE
The WG lifecycle should have a Sandbox stage

### ISSUE THREAD

**Issue by lehors** [ossf/tac#206]
The current WG lifecycle starts at the Incubation stage with the requirement that the group has already "met at least 5 times". This makes it different from the project lifecycle which starts with the Sandbox stage and it implies that the group must start in an undefined manner outside the realm of OpenSSF.

I think it would be better to define a Sandbox stage with a very low barrier of entry, similar to what we have for projects, allowing for WGs wannabe to be recognized from the start, having calls that are properly published on the community calendar, a README file with a minimal description of what the group is about with links to the minutes of the calls from the very beginning.

This would provide more consistency in how we operate across technical initiatives and remove the cloak around forming groups.

**Comment by SecurityCRob** [comment]
+1, can you perhaps give us a quick write up of some text for us to review?
