### ISSUE TITLE
DRAFT WG Lead Roles & Responsibilities

### ISSUE THREAD

**Issue by afmarcum** [ossf/tac#208]
WG Lead Roles & Responsibilities

- Facilitate WG meetings including agendas, calls for topics, and capturing and following up on action items
- Drive progress on WG efforts whether specifications, code, or other contributions
- Provide technical guidance and sponsorships for sub-projects and arbitrate technical disputes
- Present WG updates to TAC
- Facilitate WG voting as needed
- Accountable for GitHub Repo management including edits/updates, issue and PR backlog management, and delegating responsibility to a separate volunteer, if applicable
- Time commitment: 1-2 hours per week

For review at the next TAC meeting to be available as a template/starting point for each WG.

**Comment by di** [comment]
+1, I think this accurately captures the current responsibilities of a WG lead.

**Comment by lehors** [comment]
I think that's a very good list. Although one could argue that it is embedded in the driving progress on WG efforts I think it would be worth adding something about coordinating with the related Projects and SIGs.

**Comment by hepwori** [comment]
Great list!

I'd add: making the work of the working group visible and legible to the rest of OpenSSF — not just the TAC. Here (https://openssf.slack.com/archives/C01A1MA7A1K/p1697121905562069) is an example of what we're trying in SCI: just a quick summary of each meeting posted in Slack for folks to follow along with.

**Comment by torgo** [comment]
Think it should be 2-3 hours, but other than that, great.

**Comment by afmarcum** [comment]
Updated bullets 3, 4, and 7 to include feedback. Let me know if any missed the mark.

WG Lead Roles & Responsibilities

- Facilitate WG meetings including agendas, calls for topics, and capturing and following up on action items
- Drive progress on WG efforts whether specifications, code, or other contributions
- Provide technical guidance and sponsorships for sub-projects, coordinate with related Projects and SIGs, and arbitrate technical disputes as needed
- Present quarterly WG updates to the TAC and regularly make the work of the WG visible throughout OpenSSF
- Facilitate WG voting as needed
- Accountable for GitHub Repo management including edits/updates, issue and PR backlog management, and delegating responsibility to a separate volunteer, if applicable
- Time commitment: 2-3 hours per week

**Comment by lehors** [comment]
LGTM. Thanks!

**Comment by SecurityCRob** [comment]
@afmarcum can I ask you to create a PR and stage this as an md file in our repo under "process"?

**Comment by SecurityCRob** [comment]
we can do the same for other R&Rs, like the TAC there too

**Comment by SecurityCRob** [comment]
This was merged today.  Please see the final text here: https://github.com/ossf/tac/blob/main/process/wg-lead-R%26Rs.md
