### ISSUE TITLE
Inviting new WG members to the ossf GitHub org

### ISSUE THREAD

**Issue by MarcinHoppe** [ossf/tac#21]
We have recently had several new members joining the vulnerability disclosures WG.

How can I invite them to this GitHub org?

**Comment by rhaning** [comment]
@MarcinHoppe I can add them, just send me their GitHub IDs. We'll figure out a more streamlined approach for the future.

**Comment by MarcinHoppe** [comment]
Thanks! I will send a few IDs on Slack.

**Comment by dcmiddle** [comment]
@MarcinHoppe Is this issue done?

**Comment by MarcinHoppe** [comment]
If "ping @rhaning" is the final process we have for adding people to this GitHub org, then yes.

Even if that is going to be the process going forward, I'd love to see it documented somewhere before closing this issue.

**Comment by dcmiddle** [comment]
TAC discussion 2020-10-20: 
1. create a template issue for adding individuals 
2. LF staff to add member companies as teams to the ossf org. and then owners from those members can self manage their team.
