### ISSUE TITLE
Wordpress to GitHub pages migration

### ISSUE THREAD

**Issue by hythloda** [ossf/tac#210]
Hello,

We have been thinking about migrating from WordPress for a while now and realized we should consult the tac and then this [new vulnerability](https://arstechnica.com/security/2023/10/thousands-of-wordpress-sites-have-been-hacked-through-tagdiv-plugin-vulnerability/?utm_source=newsletter&utm_medium=email&utm_campaign=newsletter_axioscodebook&stream=top) came out. This does NOT affect the OpenSSF website; however it shows that Wordpress is not the best place to house our security website as sometimes the "medium is the message," and we should be showing some best practices with our website.

We got a bid from LF IT of about 26k to migrate to GitHub Pages. 

Thoughts or concerns?

**Comment by SecurityCRob** [comment]
Wordpress—

I’d be on board with considering a migration if we had the budget to.

Cheers,

CRob
Director of Security Communications
Intel Product Assurance and Security


From: Amanda L Martin ***@***.***>
Sent: Tuesday, October 10, 2023 3:34 PM
To: ossf/tac ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ossf/tac] Wordpress to GitHub pages migration (Issue #210)


Hello,

We have been thinking about migrating from WordPress for a while now and realized we should consult the tac and then this new vulnerability<https://arstechnica.com/security/2023/10/thousands-of-wordpress-sites-have-been-hacked-through-tagdiv-plugin-vulnerability/?utm_source=newsletter&utm_medium=email&utm_campaign=newsletter_axioscodebook&stream=top> came out. This does NOT affect the OpenSSF website; however it shows that Wordpress is not the best place to house our security website as sometimes the "medium is the message," and we should be showing some best practices with our website.

We got a bid from LF IT of about 26k to migrate to GitHub Pages.

Thoughts or concerns?

**Comment by steiza** [comment]
I don't feel equipped to answer the budget part of the question, but I'm definitely a fan of GitHub Pages over WordPress

**Comment by lehors** [comment]
How many pages are we talking about? I'm easily shocked by the price everything costs so maybe it's just me but isn't 26k a lot for this?...

**Comment by SecurityCRob** [comment]
Like my partners who have chimed in earlier, I agree with the idea behind the migration, but the migration costs seems to be a bit high in my experience/perspective.  I personally wouldn’t prioritize this (based on the cost) over other things that may add more value.

Cheers,

CRob
Director of Security Communications
Intel Product Assurance and Security


From: Amanda L Martin ***@***.***>
Sent: Tuesday, October 10, 2023 3:34 PM
To: ossf/tac ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ossf/tac] Wordpress to GitHub pages migration (Issue #210)


Hello,

We have been thinking about migrating from WordPress for a while now and realized we should consult the tac and then this new vulnerability<https://arstechnica.com/security/2023/10/thousands-of-wordpress-sites-have-been-hacked-through-tagdiv-plugin-vulnerability/?utm_source=newsletter&utm_medium=email&utm_campaign=newsletter_axioscodebook&stream=top> came out. This does NOT affect the OpenSSF website; however it shows that Wordpress is not the best place to house our security website as sometimes the "medium is the message," and we should be showing some best practices with our website.

We got a bid from LF IT of about 26k to migrate to GitHub Pages.

Thoughts or concerns?

**Comment by hythloda** [comment]
Thanks for the feedback! we are going to think on it some more
