### ISSUE TITLE
[RFC] Updates to OSSF Charter re: TAC size & elections

### ISSUE THREAD

**Issue by SecurityCRob** [ossf/tac#213]
The Governance Committee review a proposal from the TAC to adjust the size and election guidance in the OpenSSF's Charter - https://openssf.org/about/charter/

Below reflects what was discussed and agreed upon with the addition to adding clarity around the roles & responsibilities of a TAC member.

6) Technical Advisory Council (TAC)
a) The TAC will be composed of six (6)representatives elected annually by all active contributors to Technical Initiatives and three (3) representatives appointed by the Governing Board. The terms of the 3 representatives appointed by the Governing Board are for 1 year. The terms of the 6 elected representatives are for 2 years, in 2 groups staggered so that each year 3 terms expire. For that purpose, on the first year (2024), 3 members will be randomly selected to serve for a single year.  Appointed Governing Board positions are for one year terms.  If any TAC elected representative seat is vacant, the Governing Board may fill such vacancy by appointing the candidate with the next highest vote total in the most recent election to serve the remainder of the term.If a Governing Board-appointed position comes open, the Governing Board will convene to appoint a new candidate at the next Governing Board meeting.
b) OpenSSF Members that are part of a group of Related Companies (as defined in Section 8) may have no more than two voting representatives on the TAC.
c) The role of the TAC is to structure and facilitate collaboration among the Technical Initiatives. The TAC will be responsible for:
i) developing an overall technical vision for the community;
ii) establishing, structuring, organizing, and archiving Technical Initiatives, including the approval of the Technical Initiative charter;
iii) creating, maintaining and amending project lifecycle states, review procedures and processes;
iv) working with the Technical Initiatives to identify any resource or funding requirements and prioritizing recommendations to the Governing Board;
v) facilitating crowdfunding opportunities in support of OpenSSF Technical Initiatives;
vi) annually electing a chairperson to preside over meetings, set the agenda for meetings, ensure meeting minutes are taken, and who will also serve on the Governing Board as the TAC’s representative (the “TAC Representative”); and
vii) coordinating such other technical community matters related to the success of Technical Initiatives and the mission of the OpenSSF.

TAC members are expected to fulfill the following duties during their tenure
viiI) remain technology neutral as technical initiatives and other endeavours are evaluated, and seek to provide a broad, agnostic benefit through our collective work to the broader community.
vix) attend the bi-weekly TAC calls and any ad-hoc meetings to conduct the business of the Foundation's technical initiatives.
x) provide sponsorship and guidance to new technical initiatives that petition to join the foundation.
xi) participate regularly in the Technical Initiatives within the Foundation.  Provide assistance in guidance to ensure alignment with the Technical Vision and MVSR of the Foundation. 
xii) TAC members should expect to spend an average of approximately 5 hours per week across the Technical Initiatives, committees, and business of the TAC (reports, -pre-reads, group discussions, backlog comments/triage, etc.).
d) TAC and Technical Initiative (including, but not exclusive to Working Group (WG), Special Interest Group (SIG), Project, or Task Force) meetings shall be open, public meetings. For special circumstances, the TAC may hold meetings limited to the TAC voting representatives, invited guests, and LF staff.

**Comment by SecurityCRob** [comment]
TL/DR it is proposed the TAC grows in size from 7 to 9 members, and the elected-seats will have 2yrs terms that will be staggered going forward so that 3 seats will "age out" each year.

**Comment by SecurityCRob** [comment]
Related to https://github.com/ossf/Governance-Committee/issues/14

**Comment by SecurityCRob** [comment]
Related issues/prs that will be updated or closed as this issue is resolved:
(1) - https://github.com/ossf/tac/issues/65 (TAC election & seats) - Open
(2) - https://github.com/ossf/tac/issues/69 (TAC election officials) - Closed
(3) - https://github.com/ossf/tac/issues/68 (Number of TAC seats) - Closed
(4) - https://github.com/ossf/tac/issues/67 (TAC election process & tools) - Closed
(5) - https://github.com/ossf/Governance-Committee/issues/10 (Expand TAC from 7 to 9 seats) - Open

**Comment by jkjell** [comment]
The website's charter is already updated to the "proposed" text. Has the change already been approved? My main question was with respect to the previous/current composition of the TAC. [The charter document here](https://github.com/ossf/foundation) states that it is/was 7 members (3 selected by the GB). 

Given the increasing scope and activity across OpenSSF, these sounds like reasonable changes.
