### ISSUE TITLE
Visual material for stages used in annoucement of projects without logos

### ISSUE THREAD

**Issue by hythloda** [ossf/tac#217]
We have these generic badges for the stages of each project to accompany the blog posts for announcements.  We find it difficult to announce projects without visual materials like logos, so these materials will be used when projects are announced and do not have logos yet (such as sandbox projects coming into OpenSSF). 
Below are the designs and we would love feedback before we start using them. 

![OpenSSF_StagesBadges_v1](https://github.com/ossf/tac/assets/51727488/712fc5ca-162b-4d7e-b4b5-d5a473c82904)

An alternative solution would be to provide logos to all incoming projects via the operating model that is in the works. However, that is a larger discussion beyond the scope of this issue.

**Comment by SecurityCRob** [comment]
Even though the incubating neck isn’t in the right spot, I like these!

Cheers,

CRob
Director of Security Communications
Intel Product Assurance and Security


From: Amanda L Martin ***@***.***>
Sent: Wednesday, November 15, 2023 12:36 PM
To: ossf/tac ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ossf/tac] Visual material for stages used in annoucement of projects without logos (Issue #217)


We have these generic badges for the stages of each project to accompany the blog posts for announcements. We find it difficult to announce projects without visual materials like logos, so these materials will be used when projects are announced and do not have logos yet (such as sandbox projects coming into OpenSSF).
Below are the designs and we would love feedback before we start using them.

[OpenSSF_StagesBadges_v1]<https://user-images.githubusercontent.com/51727488/283200191-712fc5ca-162b-4d7e-b4b5-d5a473c82904.png>

An alternative solution would be to provide logos to all incoming projects via the operating model that is in the works. However, that is a larger discussion beyond the scope of this issue.

**Comment by ljharb** [comment]
The bottom of the incubating eggshell should probably line up with the bottom of the sandbox eggshell

**Comment by SecurityCRob** [comment]
Also, "Project" is used for software/code efforts and now specifications/specs.  Do we want to broaden the graphics to reflect "Technical Initiative" or "TI" so that it would be applicable to WGs, SIGs, and Projects?

**Comment by lehors** [comment]
I think these graphics are great! I agree with CRob's point that it'd be good to broaden the scope, unless we can have variants for WGs and SIGs?

**Comment by lehors** [comment]
> I suggest re-naming the second category to "Hatching" and moving "Incubating" to replace sandbox! Best to not mix metaphors!

You have a point but sandbox and incubating are already commonly used across LF.

**Comment by jennbly** [comment]
Revision back from creative with the edits that have been discussed (excpet for the naming conventions for project stages, I think we are locked in there for now - but happy to revise the graphics if/when a decision is made to depart from the standard LF usage). Ready to call these final? 

![OpenSSF_StagesBadges_120423](https://github.com/ossf/tac/assets/106337516/cce0e6b3-ecfa-4f6e-9324-7e3a60bcc81e)

**Comment by lehors** [comment]
Looks great. Thank you!

**Comment by SecurityCRob** [comment]
I've uploaded these as individual files (thanks @hythloda ) for use: https://github.com/ossf/tac/tree/main/files/images
