### ISSUE TITLE
Fill GB Security Community Individual Representative Seat

### ISSUE THREAD

**Issue by kaywilliams** [ossf/tac#22]
The OpenSSF [charter](https://docs.google.com/document/d/1WVyKpP88IWSL_PeyNNei5a_l7O0_G_Gy7tTLB7zOEdo/edit?usp=sharing) calls for one Governing Board member who is a Security Community Individual Representative elected by contributors to Technical Initiatives.

This issue is to request that the TAC identify how this person shall be nominated and elected, and the timeframe for doing so.

**Comment by mayakacz** [comment]
Thanks for opening this! *I think it is worthwhile to propose some options ahead of time so that we can discuss any contentious issues live. This also helps make sure anyone who wants to provide an opinion async has a chance to* 😄 

The charter reads
> one Security Community Individual Representative elected by contributors to Technical Initiatives.

I would propose that:
* Technical Initiatives refer to anything that rolls up to the TAC, including WGs, but also any projects, reports, etc. that are developed. That is, someone does not need to contribute code in order to be considered a contributor but they should already be involved in OpenSSF in some capacity
* They must self-identify as a member of the security community, but there are no strict requirements on what that means. That could be contributions to an open source security project, to the security of an open source security project, education about open source security, or any number of alternatives
* We should not require a nomination process, to allow anyone to self-nominate and get a wider range of candidates

I think 'who' can vote will be much harder. Ideally, it's all members of the OpenSSF, but that's hard to define today iirc. A proxy might be one per organization, or one per TAC member, or one per GB member. However, I would really really prefer that everyone in OpenSSF can vote if we can agree on how to define that.

Questions:
* Are there any restrictions on this individual's organizational affiliation, even if they are not participating in that capacity?

Meta question: should this be moved to an issue for the GB? Or is it the TAC's responsibility to decide this? Do we think we are because of the "Technical Initiatives" component? Seems legit, just checking.

**Comment by dlorenc** [comment]
> * Technical Initiatives refer to anything that rolls up to the TAC, including WGs, but also any projects, reports, etc. that are developed. That is, someone does not need to contribute code in order to be considered a contributor but they should already be involved in OpenSSF in some capacity

Huge +1 on not requiring contributions to be code. But I'm unclear what things other than WGs would count as technical initiatives. Everything under https://github.com/ossf/ rolls up under a WG today. Do you have any examples of other things that we should include?


> * We should not require a nomination process, to allow anyone to self-nominate and get a wider range of candidates

Self nominations sound good, but we still need *some* amount of process to know who has been nominated, right? This could be as simple as opening an issue/PR or emailing a list.


> * Are there any restrictions on this individual's organizational affiliation, even if they are not participating in that capacity?

I **think** the only restrictions are around the max # of voting members from one group of organizations.

> Meta question: should this be moved to an issue for the GB? Or is it the TAC's responsibility to decide this? Do we think we are because of the "Technical Initiatives" component? Seems legit, just checking.

I think it probably makes the most sense for the TAC to define the criteria on who is a "contributor to technical initiatives", and the GB should manage/define any other candidate criteria/nomination and election process.

**Comment by kaywilliams** [comment]
What do folks think of this proposal?

- Anyone who has subscribed to at least one of the OpenSSF mailing lists can self-nominate
- Anyone who has subscribed to at least one of the OpenSSF mailing lists can vote

It is not perfect - a self-nominee can 'stack the vote' by having many 'friends' join an OpenSSF mailing list, even if they aren't contributors, and cast a vote in their favor.  That said, it seems like a reasonable starting point, and we can try, learn and improve as time goes on.  Other ideas welcome.

**Comment by dlorenc** [comment]
I can't think of anything better, given the short timeframe. We should be able to come up with better criteria next time around.

The only thing I'd add is that we should publish the full list somewhere with enough time for people to examine it and make sure it looks correct, and to request inclusion if they were missed by accident. (Maybe one week?)

**Comment by mayakacz** [comment]
> > Technical Initiatives refer to anything that rolls up to the TAC, including WGs, but also any projects, reports, etc. that are developed. That is, someone does not need to contribute code in order to be considered a contributor but they should already be involved in OpenSSF in some capacity

> Huge +1 on not requiring contributions to be code. But I'm unclear what things other than WGs would count as technical initiatives. Everything under https://github.com/ossf/ rolls up under a WG today. Do you have any examples of other things that we should include?

I suspect that some projects (that belong to WGs) will have members who work on the project, but aren't part of the WG. So someone who works on the developer learning platform, for example, but isn't part of the Security Best Practices WG could still be a contributor.

>> We should not require a nomination process, to allow anyone to self-nominate and get a wider range of candidates 

> Self nominations sound good, but we still need some amount of process to know who has been nominated, right? This could be as simple as opening an issue/PR or emailing a list.

Agreed. I meant like, not requiring a TAC member, a WG member, etc. to nominate someone. (We can encourage them though!)

---

Agreed with @kaywilliams and @dlorenc 's proposal. So there would be a cut-off day for qualification (probably before the candidates are announced?), published, and those who think they should be included can appeal. Self-nomination could probably most easily happen by filling out an issue template.

This works for me.

**Comment by dlorenc** [comment]
Working backwards from the press release date, we should probably have the person chosen by 10/22 to give a week for a quote in the press release. If we can get the announcement out by Friday (9/25), we'll have a voting period of a little under two weeks. Every day we slip after that comes out of the voting period.

10/29 - press release
10/22 - representative chosen
10/9 - lock voter list after reviewing initial set, start vote
10/2 - check email lists to generate initial set
9/25 - send out announcement with plan to all lists
9/22 - today! - review and accept proposal

**Comment by mayakacz** [comment]
SGTM!

**Comment by dlorenc** [comment]
Status update: Ryan sent the announcement 9/28: https://lists.openssf.org/g/openssf-announcements/message/1

**Comment by kaywilliams** [comment]
So far, we don't have any nominations.  I wonder if we might want to delay the process a bit and announce the open position in our 10/29 press release.  This will provide greater visibility. We can also create a blog post describing the motivation and responsibilities for the role.  This is something @rhaning, Jennifer and I have been discussing offline.

**Comment by LindsayLF** [comment]
I'm open to what the groups thinks would be best here! 
_*following and will add to Press Release if needed_

**Comment by mayakacz** [comment]
I think it might make sense to re-advertise and describe in more details the responsibilities of the role. I still think we should aim to have this role filled prior to the announcement.

**Comment by dcmiddle** [comment]
> So far, we don't have any nominations. I wonder if we might want to delay the process a bit and announce the open position in our 10/29 press release. This will provide greater visibility. We can also create a blog post describing the motivation and responsibilities for the role. This is something @rhaning, Jennifer and I have been discussing offline.

+1  
I think the main idea of this is to get a voice who is engaged in the community but that doesn't come from a member company. There hasn't been much time for independent parties to get engaged yet so I think it makes sense to let that develop.

**Comment by itaysk** [comment]
Hello 👋, as someone who considered it, perhaps it would help to share my perspective:
1. The announcements included a detailed description of the motivation for why the GB want this and the required qualification, which I thought suited me, but none was said about the GB work, or the role of this candidate in practice. It's like applying to a job without seeing the job description or the team you are joining.
2. So I went researching on what the GB is about, and didn't find much. Only after coincidentally listening to the recent TAC meeting, I noticed that it was asked and answered there. I don't expect many people to have discovered that insight.
3. That comment about the GB role described the GB is mostly about budgeting, planning and delegation, so it became less appealing for me personally.
4. Is it possible that the pool of candidates meeting the profile that you have published, and the pool of candidates that are interested with the GB charter (as I understood it) doesn't overlap?
Perhaps I misunderstood some things so please correct me if I got anything wrong

**Comment by jenniferfernick** [comment]
Thank you for sharing your perspective @itaysk! This is very useful to us. To your first 2 points, we're currently preparing a blog post that will explain the details of the role and what we're looking for, which will hopefully be helpful to us in finding a great candidate for the role. I think this should be published today or tomorrow. 

To your point #3 - yes, it is a typical board governance sort of role, but there are many other places in openSSF to make technical contributions so let me/us know if we can help you find a way to get involved that you will enjoy! :)

**Comment by kaywilliams** [comment]
Agree, @itaysk, thank you for sharing your thoughts. This feedback is valuable as we think about the role, and perhaps evolve our thinking in the future.

**Comment by jenniferfernick** [comment]
In terms of submitting nominations and voting, here is what's going into the blog post, please let us know if anything should be added/modified: 

"
<p><strong><span class="has-inline-color has-vivid-cyan-blue-color">Submit your nomination</span></strong><br><strong>Nominations for the Security Community Individual Representative seat will be open until October 23 2020, and voting will take place until November 5 2020</strong>. See nomination instructions below. Once the nomination period closes, voting will be open to members of the <a href="mailto:openssf-announcements@lists.openssf.org" target="_blank" rel="noreferrer noopener">openssf-announcements@lists.openssf.org</a> mailing list. </p>


<p><strong>Nominations (including self-nomination) can be submitted to the form below (Due October 23rd 2020):</strong> <br><a href="https://docs.google.com/forms/d/e/1FAIpQLSd61bqfR_siMDvWlCC4s3jKxaVAVbOIIrt9_EwDqZ23VPmMlQ/viewform">https://docs.google.com/forms/d/e/1FAIpQLSd61bqfR_siMDvWlCC4s3jKxaVAVbOIIrt9_EwDqZ23VPmMlQ/viewform</a></p>
"

**Comment by jenniferfernick** [comment]
The blog post is now available here, feel free to share widely: 
https://openssf.org/blog/2020/10/07/openssf-seeks-security-community-individual-representative-for-governing-board/

**Comment by LindsayLF** [comment]
The election for Security Community Individual Representative Seat will close on 11/5; SCIR to be announced at the 11/9 OpenSSF Town Hall.

**Comment by dlorenc** [comment]
This is finished!
