### ISSUE TITLE
[Proposal] Showcase OpenSSF projects in various stages

### ISSUE THREAD

**Issue by pxp928** [ossf/tac#222]
**Problem**

Currently, on the [openssf.org ](https://openssf.org/) there is no projects page (similar to https://www.cncf.io/projects/) where a new user or member can go to determine which projects are OpenSSF projects (at various stages of the project lifecycle). A projects page would allow the OpenSSF to showcase their projects and make them more discoverable for contributors or end users alike. This would also highlight the commitment that the openSSF has made to enhance open source security.

**Solution**

Add a page similar to https://www.cncf.io/projects/ to showcase the various projects that fall within OpenSSF to highlight their importance and the work that is being done.

**Comment by hythloda** [comment]
I look at that page longingly every week with desire for us to have one. Know anyone with the time and talent?

**Comment by lehors** [comment]
There are two parts to this problem:
1. having the information about which TI exists and which stage it's in.
2. creating a page rendering this nicely on the openssf.org website.

I think we're still working on 1. Once it's done, we should be able to tackle 2 more easily. Hopefully we can leverage some of the great tools the LF team has already developed to make this automatic.

**Comment by hythloda** [comment]
Agree with @lehors 

For 2 we are also on hold with choosing a platform and funding and such.

**Comment by SecurityCRob** [comment]
Staff worked with Graphics and we now have badging for TIs at the various lifecycle stages and this is being embedded into the TI repos.
