### ISSUE TITLE
Clarify Community Voter Eligibility documentation and requirements and submit suggestions to the Governance Committee

### ISSUE THREAD

**Issue by SecurityCRob** [ossf/tac#235]
The current TAC & SCIR voting process is documented here(1) and has served the OpenSSF since the origination of the foundation.  It is desirable to have better definition and enable some of the voter eligibility tasks through automation and data collection from our assorted platforms (Slack, GitHub, LFX, mailing lists, etc.).  This issue has been created to help shepherd that conversation and suggestions and will be paired with a subsequent PR to adjust the existing process documentation. 

It is desirable that this work is completed the 1st half of 2024 so that the materials are updated and ready for the 2025 election cycle which will kick off in ~Nov2024.

(1) - https://github.com/ossf/tac/blob/main/elections/tac-and-scir-election-process.md

**Comment by sevansdell** [comment]
@lehors in the last GC meeting, you mentioned some great process improvements around the TAC voting process. Are there still open items that need documented for this issue? How can I help?

**Comment by lehors** [comment]
PR #334 was merged and improved the overall TAC and SIR election and nomination process. However, it didn't address this particular issue which I believe is about improving the voter eligibility section: https://github.com/ossf/tac/blob/main/elections/tac-and-scir-election-process.md#voter-eligibility-electorate-and-self-nomination-process

To make progress on this we would need to list what specific issues exist with that section. Do we know of specific situations that arose during last year's election cycle that our current documentation didn't address? I personally don't know. @SecurityCRob ? @hythloda ?

**Comment by hythloda** [comment]
When collecting the electorate, there were a number of people that only answered "yes" to the question "How have you contributed to OpenSSF projects or working groups over the last year?"
If I didn't know of their contributor directly (about 10%) I looked up their GitHub records, slack records and activity in Google Drive. If I could not confirm their participation then I emailed them individually (and slacked them if available) for their methods of participation. All were able to be verified but about 1%. With another 1% decided we decided together they did not have enough "consistent participation" to know the nominees enough to do a knowledgeable vote. 

I think this is captured enough in the documentation and those edge cases were happy with the process. Perhaps it would be nice to add the process taken for consistency?

**Comment by sevansdell** [comment]
> When collecting the electorate, there were a number of people that only answered "yes" to the question "How have you contributed to OpenSSF projects or working groups over the last year?" If I didn't know of their contributor directly (about 10%) I looked up their GitHub records, slack records and activity in Google Drive. If I could not confirm their participation then I emailed them individually (and slacked them if available) for their methods of participation. All were able to be verified but about 1%. With another 1% decided we decided together they did not have enough "consistent participation" to know the nominees enough to do a knowledgeable vote.
> 
> I think this is captured enough in the documentation and those edge cases were happy with the process. Perhaps it would be nice to add the process taken for consistency?

I think adding the process for consistency and transparency is ideal! Would you be willing to start a PR with your proposed text here please? Once that is approved we can link it to this issue and close this out.

**Comment by SecurityCRob** [comment]
has there been any progress on this?

**Comment by sevansdell** [comment]
since the TAC election process is live now, and PRs are in place for new process language, I am closing out this Issue. Kudos to @Naomi-Wash
