### ISSUE TITLE
WGs to provide more metadata?

### ISSUE THREAD

**Issue by iamamoose** [ossf/tac#24]
As part of https://github.com/ossf/gb-strategy-committee/issues/7 we want the main OSSF site to give a list of the current working groups as well as links to mailing lists, calendars, and other useful resources.  But we don't want to be editing this information by hand.   We could certainly collate a lot of this from the existing github settings.yml

This issue is to figure out if that's enough or if there is a use in having WGs provide more metadata we could collate so everything can be automated and never ends up out of date.

From the Strategy WG proposal:

> - list of working groups, description, link to repos

We can get this from all the settings.yml

> - WG:   Meetings. <link to Google calendar(s), and information about how to add to your own calendar>

All these should be in the main OSSF calendar.  Perhaps as that calendar gets large and if WG's end up with meetings for sub-projects then having some way to find them on a per-sub-project basis (and/or outside of having to use a google calendar)

>   Mailing lists. 

All these should already be here already https://lists.openssf.org/g/main/subgroups but perhaps a list with longer description will be useful if projects end up with multiple lists.

>   Slack. <information for subscribing to slack>

Perhaps a list of the channels/rooms (again it's kind of obvious until we have many wg's with sub-projects)

>   Google Drive folders <link to folder tree>
>   Recorded meeting videos <link to meeting videos here>

Current WG's do have a mix of location of agendas and minutes and recordings, so collating these links would be useful.

>   Blog posts

I've not seen how blog posts will work yet to if this is needed or will be obvious.

(I brought this up on a strategy call as The Apache Software Foundation does this by having projects publish information in DOAP with a master list of the locations of these files, https://svn.apache.org/repos/asf/comdev/projects.apache.org/trunk/data/projects.xml and here is a good example of a specific DOAP RDF file: http://svn.apache.org/repos/asf/tomcat/site/trunk/docs/doap_Tomcat.rdf and all this ends up used all over the site for project listings etc.  But I'm not proposing using this legacy solution given we can just collect things in a yml file (and probably needing a separate file to not overload/confuse the bot that parses settings.yml))

**Comment by SecurityCRob** [comment]
Hello.  As part of 2022 backlog grooming, each open TAC issue is being reviewed for applicability/completeness.  Has this request been completed?  If so, can that be noted in a comment please.  If not, what actions need taken to continue moving this issue to completion? If we do not here back from you within two weeks, this issue will be closed (23March2022).  Thank you.

**Comment by lehors** [comment]
@SecurityCRob I see no evidence of this having be done, yet it seems worthwhile pursuing. However, it would need a concrete proposal to be put before the TAC for approval and then recorded as part of the TAC's documentation so that all existing and future groups can be directed to it.

**Comment by SecurityCRob** [comment]
Discussed yesterday in TAC call.  On hold, pending standardization updates to WGs.  Will revisit in 90 days (13June2022)

**Comment by steiza** [comment]
https://openssf.org/getinvolved/ lists out the working groups. https://github.com/ossf/tac/issues/162 will ensure the working group repository READMEs contain the needed information.
