### ISSUE TITLE
OpenSSF Webinar Series

### ISSUE THREAD

**Issue by mlieberman85** [ossf/tac#251]
This is a tracking issue for the webinar series that @jennbly is organizing.

See: https://docs.google.com/document/d/1r3hRI4TQacR_di_lKRjroMvenifTMA9Ulpwoz-BV6DE/edit for tentative proposed schedule.

We need input on general goals of webinar series (some goals are in the doc already):
- Intended audience
- Intended takeaways

The TAC needs to come to consensus on requirements for a TI participating in the webinars like:
- Process for submitting topic for consideration
- Maturity level of TI participating.

The goals and requirements are linked in many ways. Understanding the goals like intended audience will help us understand what level of maturity a TI should be before submitting a topic. For example, if the goal is to educate the broader community on how to achieve a security goal it might be best suited for incubating and graduated TIs to participate. If the goal is to highlight a problem area being explored by OpenSSF sandbox might also be relevant.

Feel free to add additional goals, or requirements you think are relevant as comments in the doc.

**Comment by marcelamelara** [comment]
+1 to converging on a set of requirements and steps to select webinar topics.

One additional requirement/goal I wanted to suggest is ensuring a balance between the more tool- or spec-focused TIs and the more educational/practices-centric TIs. The current proposed tech talk schedule primarily features spec- and tool-centric TIs, even though I'd argue that TIs in WGs like End User, Best Practices and DEI are equally as important.

The May, June and Dec topics do begin to address these concerns, and I also want to make sure that our eligibility framework ensures that different types of TIs are represented proportionally in the webinar series.

**Comment by SecurityCRob** [comment]
Has there been any further developments around this?  Is someone interested in working with staff & the community to maybe help identify and cultivate this technical series of webinars?  @ossf/tac

**Comment by CoS-Harry** [comment]
I think this one is OBE, as we are already conducting the tech talk series.

**Comment by sevansdell** [comment]
> I think this one is OBE, as we are already conducting the tech talk series.

Can this issue be closed with an ask to have a review period prior to next year's tech talk series?

Also, what does OBE stand for....a quick google search only showed me Order of the British Empire... ;)

**Comment by CoS-Harry** [comment]
Please close this issue. This will be reviewed with the TAC prior to execution in 2025. OBE means overtaken by events.
