### ISSUE TITLE
Migrate from branch protection to rulesets?

### ISSUE THREAD

**Issue by marcelamelara** [ossf/tac#255]
We're currently using branch protection settings for PRs, but we could also consider migrating from branch protection to rulesets (https://github.com/ossf/tac/settings/rules).

_Originally posted by @steiza in https://github.com/ossf/tac/pull/252#pullrequestreview-1844136802_

**Comment by steiza** [comment]
I may have been too hasty! At some point in the future, GitHub should have a "click here to move your branch protection settings to rulesets" button. Unless someone wants to pick this up sooner than later, I think it'll be less work if we wait for the button.

**Comment by sevansdell** [comment]
Is this a duplicate of 333 and can be closed out in this issue?

**Comment by david-a-wheeler** [comment]
One problem is that branch protection is easily verified, and Scorecard does this. Rulesets aren't. I didn't see an argument for the switch - why should we switch?

**Comment by sevansdell** [comment]
Notes from TAC call where this was discussed: 

- Marcela, Mike and Crob will work this asynchronous
- David: tools may need updated to reflect rulesets and branch protection. Currently, scorecard only recognizes branch protection, as an example
- Mike: Sometimes, rulesets applied at the company level aren’t easily visible on projects via API. He’s dealing with this at his own company.

**Comment by sevansdell** [comment]
@marcelamelara , @mlieberman85  and @SecurityCRob  status update please!

**Comment by marcelamelara** [comment]
Thanks for the ping Sarah! This completely fell off my radar. 

FWIW, here is the discussion on the rulesets vs branch protection: https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-rulesets/about-rulesets#about-rulesets-and-protected-branches

We may ultimately decide to shelf this and keep things as they are. But I think we have an opportunity here to revisit this and align with the security baseline as well. @SecurityCRob and @mlieberman85 wdyt?

**Comment by mlieberman85** [comment]
I think either or is easy. I think setting up rulesets is most powerful at the org level though. Given that our stuff is fairly straight forward as far as branches go, I don't think we would have much benefit here over normal branch protection.

**Comment by marcelamelara** [comment]
> I think setting up rulesets is most powerful at the org level though

Maybe this is something we can follow up on with @SecurityCRob then.

Barring any objections. I'm going to close this issue by EOW.

**Comment by lehors** [comment]
For what it's worth, I'm no expert in the matter so I may be missing something here but, I'm not convinced we really have a problem that needs fixing. I support closing this as is.

**Comment by steiza** [comment]
There's no urgent need for us to move off of branch protection - I'm fine with us closing out this issue.

**Comment by marcelamelara** [comment]
Thank you everyone for your feedback!
