### ISSUE TITLE
Business case for fund application

### ISSUE THREAD

**Issue by sevansdell** [ossf/tac#257]
I would like to  partner with staff to develop a business case for TIs requesting funds. My timeline is by the Feb 20 TAC meeting to have a draft ready to review.

**Comment by SecurityCRob** [comment]
Mike gave us a proposal last week we'd like everyone to review and provide feedback:  https://docs.google.com/document/d/1ZKvMUc52-7EllSajc7nPKfmlmjo6etEn7ANMEbM_zl8/  (business case template link embedded within)

**Comment by sevansdell** [comment]
I support this proposal form and process document. I would like to see the TAC provide comments by end of week. I am also seeking GC comments in parallel. Potentially if we can get the form finalized by Friday, in our Tuesday March 5 TAC meeting we can announce the CFP.

**Comment by CoS-Harry** [comment]
I have commented on the google doc. The GH form needs to be updated. The board here: https://github.com/orgs/ossf/projects/25/views/1 needs to be revised. The TAC does not "approve" funding.

**Comment by lehors** [comment]
> I have commented on the google doc. The GH form needs to be updated. The board here: https://github.com/orgs/ossf/projects/25/views/1 needs to be revised. The TAC does not "approve" funding.

I agree. I actually made that clear on the TAC call this week and updated the meeting record accordingly. The TAC merely expresses support for the request for funding.

**Comment by hythloda** [comment]
Can we close this out with the PR #272 ?

**Comment by SecurityCRob** [comment]
Today on 14March2024, the GC reviewed and approved of this new process.
