### ISSUE TITLE
License/CLA policies

### ISSUE THREAD

**Issue by dlorenc** [ossf/tac#26]
Some of the WGs are getting started on code and specifications. We should figure out what we need to do for CLAs and licensing across the OSSF.

**Comment by david-a-wheeler** [comment]
The default licensing requirements are listed in the [Technical Charter for Open Source Security Foundation section 6](https://github.com/ossf/project-template/blob/main/CHARTER.md). The template has Apache 2.0 and CC-SA. A working group can specify a different license, that would be approved by the TAC.

I recommend against using a CLA as the hurdle for people to get that signed is too much and cause risks to the project due to lack of participation.

**Comment by dlorenc** [comment]
The charter linked above is basically a boilerplate document for governance within each WG. These can be deleted/renamed/changed at will by the WGs. 

I think we may want to discuss on a default license for code across all WGs, and define a process for WGs to get exceptions made by the TAC.

**Comment by dcmiddle** [comment]
@dlorenc mentioned the OpenSSF Charter is here (as opposed to the WG templates):
https://github.com/ossf/foundation/blob/main/Review%20Copy%20Only%20-%20Not%20for%20Execution_OpenSSF%20Participation%20Agreement%20and%20Charter%20(rev.%202020%2009%2011).pdf

I don't see mention of default license so this may be a GB issue?

See also https://www.hyperledger.org/about/charter section 12 for example text.

**Comment by kaywilliams** [comment]
We discussed intellectual property during OpenSSF creation and decided to handle via the Technical Charter rather than the OpenSSF Charter. Specifically, IIRC, the agreement was to place the Technical Charter template (https://github.com/ossf/project-template/blob/main/CHARTER.md) in each new repo, and have each WG fill it out.

**Comment by dcmiddle** [comment]
Per discussion in TAC 2020-10-20 the policy is Apache 2.0 and the the use of charter templates with the Apache 2 verbiage was meant to document that policy.
However, since the discussion is open about using the entirety of those templates we still have an open about how to communicate the license policy independent of the templates.
One suggestion was to list it in the TAC repo along with related process/policy around creating a working group.
See also https://github.com/ossf/tac/issues/9 and https://github.com/ossf/tac/issues/13 for charter discussions.

**Comment by dlorenc** [comment]
+1 on keeping it simple. So to summarize my understanding:

- The GB is actually in charge of licensing policies
- The TAC might have to deal with questions on them.

Let's document those policies somewhere in the TAC repo, and explain how to deal with exceptions through the GB.

**Comment by jenniferfernick** [comment]
Proposed workflow (I welcome your tweaks/feedback): 

1. **WG Leader raises license question in TAC**: Have WG leaders raise within regular TAC meeting any proposed licensing exemptions/changes. This would let other working group leaders know of forthcoming license changes in case there may be unintended consequences for considerations for their own projects and repos, and enable TAC rep to clarify any open questions/ambiguities. This would include a written specification of: 
   - project/repo in scope 
   - proposed license
   - rationale for non-Apache 2.0 license
   - likely consequences (positive and negative) of proposed license 

2. **TAC Rep raises license question to GB via email**: TAC rep could forward to GB members in advance the written proposal, so we'd be immediately ready to vote/decide at the next GB meeting. 

3. **GB discussion and voting during GB meeting**: TAC representative can raise the license question in the next GB meeting following the TAC meeting in which they were raised, and having done the pre-reading can aim to decide on the spot.

**Comment by mayakacz** [comment]
I think there (may?) be a distinction between any policies governing WG and policies governing projects.

For WGs, what @dlorenc said is my understanding. It sounds like(?) all the WGs are under Apache 2.0.

> I don't see mention of default license so this may be a GB issue?

It sounds like it should be documented that the default/assumed license is Apache 2.0.

It also sounds like projects are assumed to be under Apache 2.0 as well, but may have a reason not to be. For projects that have a reason not to be, @jenniferfernick 's suggested workflow works for me.

**Comment by kaywilliams** [comment]
The default license, as well as the process to request an alternate license is described in the [Charter](https://github.com/ossf/project-template/blob/main/CHARTER.md) template (section 6, copied below for convenience)

-------------

6. Intellectual Property Policy
a. Collaborators acknowledge that the copyright in all new contributions will be retained by the copyright holder as independent works of authorship and that no contributor or copyright holder will be required to assign copyrights to the Technical Initiative.

b. Except as described in Section 6.c., all contributions to the Technical Initiative are subject to the following:

i. All new inbound code contributions to the Technical Initiative must be made using the Apache License, Version 2.0, available at https://www.apache.org/licenses/LICENSE-2.0 (the "Technical Initiative License").

ii. All new inbound code contributions must also be accompanied by a Developer Certificate of Origin (http://developercertificate.org) sign-off in the source code system that is submitted through a TSC-approved contribution process which will bind the authorized contributor and, if not self-employed, their employer to the applicable license;

iii. All outbound code will be made available under the Technical Initiative License.

iv. Documentation will be received and made available by the Technical Initiative under the Creative Commons Attribution 4.0 International License, available at http://creativecommons.org/licenses/by/4.0/.

v. To the extent a contribution includes or consists of data, any rights in such data shall be made available under the CDLA-Permissive 1.0 License.

vi. The Technical Initiative may seek to integrate and contribute back to other open source projects ("Upstream Projects"). In such cases, the Technical Initiative will conform to all license requirements of the Upstream Projects, including dependencies, leveraged by the Technical Initiative. Upstream Project code contributions not stored within the Technical Initiative’s main code repository will comply with the contribution process and license terms for the applicable Upstream Project.

c. The TSC may approve the use of an alternative license or licenses for inbound or outbound contributions on an exception basis. To request an exception, please describe the contribution, the alternative open source license(s), and the justification for using an alternative open source license for the Technical Initiative. License exceptions must be approved by a two-thirds vote of the entire Governing Board.

d. Contributed files should contain license information, such as SPDX short form identifiers, indicating the open source license or licenses pertaining to the file

**Comment by mayakacz** [comment]
@kaywilliams If I read that correctly, it says Apache 2.0 is the default, and
> The TSC may approve the use of an alternative license or licenses for inbound or outbound contributions on an exception basis. 

I think what we need is the process for that step.

**Comment by dcmiddle** [comment]
I read TAC when I first read that blurb @mayakacz, but now I see the TSC there refers to the governing body of the project / working group. In the unlikely event that they need a different license, that group brings the request to the board. I imagine we can operate without additional process for this kind of exceptional event.

I think @dlorenc had a good summary of this issue, i.e. the TAC repo should state license policy because it's uncertain whether we will use the Technical Initiative Charter templates as written (they are heavy weight.. see other issues linked above).
Ideally this policy would be part of a broader document but the TAC is chartered through the Foundation's Charter and licensing is not defined there.

**Comment by mayakacz** [comment]
> I think @dlorenc had a good summary of this issue, i.e. the TAC repo should state license policy because it's uncertain whether we will use the Technical Initiative Charter templates as written (they are heavy weight.. see other issues linked above).

I agree.

I think it's not unreasonable that a *project* (not a WG) in the future may want a different license for some reason. Of course, we could also simplify by just waiting until that happens!

**Comment by david-a-wheeler** [comment]
I think we (techniically?) have an instance: [CVE-Benchmark](https://github.com/ossf-cve-benchmark) [issue 35](https://github.com/ossf/tac/issues/35) intends to use the [MIT License](https://github.com/ossf-cve-benchmark/ossf-cve-benchmark/blob/main/LICENSE) for its tools. I personally think that's a perfectly reasonable alternative, but since it's different, perhaps that should be raised up.

**Comment by kaywilliams** [comment]
Agree. @sj any concerns with changing the CVE-Benchmark license to Apache 2?  If you would prefer MIT, we should raise to the Governing Board for discussion.  MIT license may be fine. It's just that this hasn't been discussed yet. The CVE-Benchmark project would be our first trial.

**Comment by sj** [comment]
> Agree. @sj any concerns with changing the CVE-Benchmark license to Apache 2?

Let me ask some colleagues internally and get back to you. I don't think we need to decide on this before we submit our conference talk recording on 16 November, so I suggest we briefly discuss this topic during the TAC meeting on the 17th.

**Comment by sj** [comment]
One of my colleagues just pointed out the following on https://openssf.org/#faq:

![image](https://user-images.githubusercontent.com/5082246/99412751-fd2e6080-28ec-11eb-9f7d-082c018ae77c.png)

We should probably take that into consideration (or correct the FAQ)

**Comment by david-a-wheeler** [comment]
I don't think that accurately captures things. I'll draft up a proposal. Then the kibitzing & voting can being.

I think this is actually a GB issue, not just a TAC issue. But I'm sure everyone will comment no matter what :-).

**Comment by dlorenc** [comment]
I've added a discussion topic on this for the next board meeting as well. We currently have projects under MIT and need a policy ASAP.

**Comment by david-a-wheeler** [comment]
There's another: The CII Best Practices badge, which uses the MIT license and has since its inception. I'll create a proposal for exception (assuming "Apache 2.0 is the default").

**Comment by david-a-wheeler** [comment]
I think @jenniferfernick 's overall workflow makes sense, but I worry about bottlenecks. May I suggest that it also allow a fully email-based approach, so you don't *have* to wait for a meeting to vote? Also, I think *any* GB member, including the TAC rep, should be able to raise these to the GB; normally that'd be the TAC rep, but if the TAC rep is sick I wouldn't want the whole process to get stuck. Finally, I think we should separate "workflow" from "defaults" so the workflow doesn't need to change if the defaults change.

Proposed tweaked workflow:

1. WG Leader raises any proposed licensing exemptions/changes to the TAC (via a TAC meeting or TAC mailing list). This would let other working group leaders know of forthcoming license changes in case there may be unintended consequences for considerations for their own projects and repos, and enable the TAC rep to clarify any open questions/ambiguities. This would include a written specification of the (1) project/repo in scope, (2) proposed license, (3) rationale for different license,  and (4) likely consequences (positive and negative) of proposed license.
2. License question raised to the GB via email: A GB member, normally the TAC rep, forwards to GB members in advance the written proposal, so the GB is can vote/decide (e.g., at the next GB meeting).
3. GB discussion and voting (via GB meeting or vote via GB mailing list): The license questions are raised (typically by the TAC rep) in the next GB meeting following the TAC meeting in which they were raised, and having done the pre-reading the GB can decide on the spot. Alternatively, the questions may be raised and the GB can decide electronically.

Please note this is merely a proposal; all of *you* decide what the workflow is :-).

**Comment by david-a-wheeler** [comment]
@kaywilliams noted the licensing text from the Charter here: https://github.com/ossf/tac/issues/26#issuecomment-721311790 . Perhaps that full text should simply be the statement about OpenSSF licensing. It covers lots of issues ahead-of-time. I think requiring 2/3rds majority for the MIT licensing is perhaps an overly strong requirement; the GB could even allow the TAC to allow use of the MIT license with a TAC vote, but I think that's the GB's decision to make.

In any case, I think the GB needs to set the licensing policy (I suggest copying from the charter), and then make that the FAQ entry instead.

**Comment by jenniferfernick** [comment]
I am on board with your proposed changes @david-a-wheeler - you make a good point about it not necessarily needing to be voted on in a meeting. The main thing I was trying to achieve was not having it span the time between 2 or more meetings by being raised in meeting n and then voted on in meeting n+1 or later. Your proposed direction would work well and deals with the same thing I had in mind: efficiency and avoiding bottlenecks.

At the risk of oversimplification, I also would ask the group: Shall we maintain a list of acceptable licenses, such that by approving use of a non-default license once, it becomes approved for all future use cases? For example, MIT is spiritually similar to Apache as far as we'd care, so we're likely to say yes to that. Once we do, is it necessary to us that projects raise all future MIT licenses to us, or do we already know where we stand and can make it a default-to-approved choice also?

**Comment by dlorenc** [comment]
> At the risk of oversimplification, I also would ask the group: Shall we maintain a list of acceptable licenses, such that by approving use of a non-default license once, it becomes approved for all future use cases? For example, MIT is spiritually similar to Apache as far as we'd care, so we're likely to say yes to that.

I'm +1 on adding MIT to the list of approved licenses, and not needing exceptions for that one going forward. I think we probably want a way to get an exception for a specific project though, where we're not making a blanket exception.

**Comment by dlorenc** [comment]
> The main thing I was trying to achieve was not having it span the time between 2 or more meetings by being raised in meeting n and then voted on in meeting n+1 or later.

Also, big +1 on this. I think the unfortunate part is that the Governing Board is a closed group and doesn't actually have a mechanism for questions like this to be raised directly for approval, and it's the role of the TAC representative to raise these on behalf of the community.

I'd like to see if we can think through a way to short-circuit the TAC here to avoid the N+1 meetings thing.

**Comment by sj** [comment]
Thanks, @dlorenc and everyone else who chipped in; this all sounds great. I hope that others here (and in the GB?) are also OK with MIT, so that we can continue to launch the CVE benchmark under the MIT license at Black Hat next week on Wednesday.

If the MIT license is not OK, then it'd be really great if we could have confirmation of this by this coming Wednesday. In the absence of any objections, we'll go ahead as planned!

Thanks again!

**Comment by david-a-wheeler** [comment]
For now, I expect that the CVE Benchmarking & CII Best Practices badge projects will forward an exception request to the TAC & GB so they're not held back by licensing questions. The GB may choose to create a committee to resolve licensing questions in general.

There’s obviously a lot of confusion about licensing. The OpenSSF FAQ says that any OSS license is fine for OpenSSF projects. The WG template in contrast has specific licensing requirements: <https://github.com/ossf/project-template/blob/main/CHARTER.md#6-intellectual-property-policy> as pointed out by Kay Williams above: <https://github.com/ossf/tac/issues/26#issuecomment-721311790>. That template implies that the GB must approve changes, yet the template is at the WG level & WGs appear to be free to change that (making it moot). I think the OpenSSF has leeway in its decision, & I'm happy to help however I can.

The OpenSSF may decide to clearly impose specific OSS licensing requirements and use the WG template section 6 as a starting point: <https://github.com/ossf/project-template/blob/main/CHARTER.md#6-intellectual-property-policy> If so, have some proposed tweaks that I'll post here so "everything is here":

First, I think many (as noted above) are fine with the MIT license, & don't want to go through a complicated dance for the MIT license. That suggests that the OpenSSF GB should have a pre-approved set of licenses, and then require approval for an exception. I would suggest that Apache-2.0, MIT, and its combo "(APACHE-2.0 OR MIT)" all be allowed. One way to do that would be to change this text:

> i. All new inbound code contributions to the Technical Initiative must be made using the Apache License, Version 2.0, available at https://www.apache.org/licenses/LICENSE-2.0 (the "Technical Initiative License").

to this:

> i. All new inbound code contributions to the Technical Initiative must be made using its license. That license must be in the Governing Board (GB) Pre-approved License List when the Technical Initiative become part of OpenSSF or a license reviewed by the TAC and approved by the GB for that Technical Initiative. The initial GB Pre-approved License List is the Apache License, Version 2.0, available at <https://www.apache.org/licenses/LICENSE-2.0> (the "Technical Initiative License"), the MIT license <https://opensource.org/licenses/MIT>, or the combination "(APACHE-2.0 OR MIT)".

Second, its clause “c” requires licensing exceptions to be approved by a 2/3 vote of the GB. I suspect that’s excessive for single projects, though that may be appropriate for pre-approved license list changes. Here is its current text:

> c. The TSC may approve the use of an alternative license or licenses for inbound or outbound contributions on an exception basis. To request an exception, please describe the contribution, the alternative open source license(s), and the justification for using an alternative open source license for the Technical Initiative. License exceptions must be approved by a majority of the Governing Board. The Governing Board may also change its Pre-approved License List; such changes must be approved by a two-thirds vote of the Governing Board.

I haven't had a chance to ask Mike Dolan to review this, but this is more food for thought anyway. It's only worth reviewing if the OpenSSF is thinking of doing it :-). Anyway, I hope this is helpful.

**Comment by jenniferfernick** [comment]
I commented a version of this in our email thread, and am just posting it here so it doesn't get lost:

_My thoughts (& I’m open to being totally wrong on this and taking a different approach btw) are –_
 
_A lot of the WG governance stuff feels like bureaucratic overkill to me. Does a single project need a whole charter and technical steering committee? In my personal view, it does not. Maybe each WG needs only ‘the basics’ and everything else is inherited from governance/decisions made within the TAC and/or GB. I think simplification could help make it easier to do more technical work and less email threads._ 

_What could this look like in practice?_

- _Per @dlorenc – removal of individual charters/TSCs and just solve this once generically for OpenSSF_

- _Inclusion, per project, of ‘the basics’ (Who leads it; How to get involved and receive communications; Where the repo/docs live)_

- _IP stuff to be radically simplified, which could look like: One single, simply-stated IP policy for all of OpenSSF; Maintain a list of “approved default” licenses that any project can use; Clearly-defined, lightweight, request-and-approval process for exceptions by TAC+GB on approved licenses requested for a given project (ie: for licenses not already approved defaults); We could use some version of the workflow proposed in https://github.com/ossf/tac/issues/26_
 

_Keen to hear everyone else’s views as well._
 
_We should be clear on audiences also – I feel like I’m seeing discussion on this in both the gb and the tac threads which means not everyone is seeing the whole thing._ 

_Over all, I would like to reduce the amount of bureaucracy in OpenSSF. Things feel (to me) too complicated for some reason, and I’d love to distill things down by means of well-defined processes that mainly exist OpenSSF-wide, clearly-documented defaults, and less subcommittees._

**Comment by christo4ferris** [comment]
I believe that the intention of the template was to permit something to grow into an Apache-like structure where there are multiple distinct things going on that had their own governance. I agree that the template seems heavy-weight and said so during the formation phase. I think a project has maintainers unless it too grows to the point that it takes on a life of its own and needs the likes of a TSC to cat herd the various sub-projects. 

I tend to think that the WGs could provide the function of a TSC for an initiative/project(s) but that is not what they ended up as, and we have apparently taken on independent projects that relate to one or more WG. 

As for the IP policy, that should apply across the board and be a part of the overall OpenSSF charter and be subject to change by the GB as needed. I am fine if we establish a list of permitted licenses, and have no objection to accepting MIT. I would however prefer if NEWLY CREATED works use Apache2.0 for its protections for the IP claims of contributors.

**Comment by sj** [comment]
For the record: the governing board just voted in favour of allowing license exceptions for both the CVE Benchmark project and the Best Practices badge.

**Comment by mayakacz** [comment]
It seems we now have a [default Apache 2.0 license in the project template](https://github.com/ossf/project-template/blob/main/LICENSE), and a license in each WG.

I'd also propose (at least) the following list of pre-approved licenses, if projects/WGs want to use an alternative:
* Apache 2
* MIT
* Common Creative Attribution

**Comment by SecurityCRob** [comment]
Hello.  As part of 2022 backlog grooming, each open TAC issue is being reviewed for applicability/completeness.  Has this request been completed?  If so, can that be noted in a comment please.  If not, what actions need taken to continue moving this issue to completion? If we do not here back from you within two weeks, this issue will be closed (23March2022).  Thank you.

**Comment by lehors** [comment]
@SecurityCRob I believe this issue needs more work. For one thing, with WGs getting into the business of developing specifications we ought to specify that in such cases the WG should use the [Community Specification License](https://github.com/CommunitySpecification/1.0/blob/V1.0/1._Community_Specification_License-v1.md). Open source licenses aren't suitable for specification development.

To clarify, we need 3 *types* of licenses:
1. for code: Apache 2 (preferred), MIT, anything else ??
2. for documentation: CCA
3. for specification: CSL

**Comment by david-a-wheeler** [comment]
Section 5 of the [OpenSSF charter](https://charter.openssf.org/) specifically states the default license requirements. You can request an exception from the governing board.

**Comment by lehors** [comment]
@david-a-wheeler Thanks, LGTM. It'd be good to update this PDF which has a big watermark reading "Review Copy - Not For Execution". :-)
So I think this fully covers the issue at hand. We should simply update the project template to reflect this policy.

**Comment by lehors** [comment]
To help us move forward on this I submitted a PR to the project-template. I hope this helps.

**Comment by SecurityCRob** [comment]
Is there additional actions needed to be taken before we close this Issue, or has David answered sufficiently?

**Comment by steiza** [comment]
With the OpenSSF charter plus https://github.com/ossf/project-template/blob/main/README.md?plain=1#L67C3-L67C3, this looks done to me!
