### ISSUE TITLE
TI Lifecycle Checklist

### ISSUE THREAD

**Issue by SecurityCRob** [ossf/tac#270]
While working on getting the BEST and Vuln WGs in shape I created a quick checklist that others may use(1).  I'd love to get the TAC's feedback on the content/arrangement.  If we would like to use it, perhaps it could be turned into a template of some sort (or at least a file that people could copy & edit) as we go through our lifecycle reviews.  Patches and feedback welcome.

(1) - https://docs.google.com/spreadsheets/d/1_aKd-S0VkfRfAh9ARIiI09WZVK1roLXqB1f84UXIkl8/

**Comment by SecurityCRob** [comment]
This was sourced from the TI Gives & Gets and the WG lifecycle documentation.

**Comment by steiza** [comment]
I like the checklist! Basically it's a mashup of the Gives / Requirements on https://github.com/ossf/tac/blob/main/process/TI-Gives%2BGets.md and the various lifecycle docs under https://github.com/ossf/tac/tree/main/process?

Is this checklist intended just for evaluating WGs? I think that might make it easier to reason about. Some of the lines (like under "TI Graduated Requirements") reference Projects, which we could then strike if we're focused on WGs. Also if we're focused on WGs we don't have to do the gymnastics of "report to the TAC or your sponsoring WG" to cover SIGs and Projects that don't report to the TAC directly.

**Comment by torgo** [comment]
Largely looks good. I left a suggestion in the doc about requiring a posted code of conduct.

**Comment by SecurityCRob** [comment]
> I like the checklist! Basically it's a mashup of the Gives / Requirements on https://github.com/ossf/tac/blob/main/process/TI-Gives%2BGets.md and the various lifecycle docs under https://github.com/ossf/tac/tree/main/process?
> 
> Is this checklist intended just for evaluating WGs? I think that might make it easier to reason about. Some of the lines (like under "TI Graduated Requirements") reference Projects, which we could then strike if we're focused on WGs. Also if we're focused on WGs we don't have to do the gymnastics of "report to the TAC or your sponsoring WG" to cover SIGs and Projects that don't report to the TAC directly.

Thanks for the feedback.  I'd prefer to have ONE list we all work off for ALL things if possible (less long-term maintenance).  We could adjust the entries that are specific to one TI type or another if that might help.

**Comment by SecurityCRob** [comment]
> Largely looks good. I left a suggestion in the doc about requiring a posted code of conduct.

I added a row that I hope addresses your concern @torgo

**Comment by steiza** [comment]
> I'd prefer to have ONE list we all work off for ALL things if possible (less long-term maintenance).

That's reasonable! I think we might have to go through the doc are reword things slightly for that perspective though.

Like today we have:

> Proposal of scope for review by TAC - This is to help ensure limited overlap with existing WGs

should that be something like:

> Proposal of scope for review by TAC or WG - This is to help ensure limited overlap with existing TIs

Also today there are items that seem to be for WGs explicitly:

> The TAC will add the WG to the list of WGs to its README.

Maybe that should be:

> The TAC will add the TI to the appropriate list on its README.

Does that make sense?

**Comment by SecurityCRob** [comment]
> > I'd prefer to have ONE list we all work off for ALL things if possible (less long-term maintenance).
> 
> That's reasonable! I think we might have to go through the doc are reword things slightly for that perspective though.
> 
> Like today we have:
> 
> > Proposal of scope for review by TAC - This is to help ensure limited overlap with existing WGs
> 
> should that be something like:
> 
> > Proposal of scope for review by TAC or WG - This is to help ensure limited overlap with existing TIs
> 
> Also today there are items that seem to be for WGs explicitly:
> 
> > The TAC will add the WG to the list of WGs to its README.
> 
> Maybe that should be:
> 
> > The TAC will add the TI to the appropriate list on its README.
> 
> Does that make sense?

GREAT suggestions, thanks!  I'll work on getting them integrated!

**Comment by lehors** [comment]
> perhaps it could be turned into a template of some sort (or at least a file that people could copy & edit) as we go through our lifecycle reviews.

So, I fully support the goal but I must admit being a bit confused because we actually already have [templates](https://github.com/ossf/tac/tree/main/process/templates). Shouldn't we just update them to reflect anything missing? Or is this meant to be different?
We could refactor the existing templates if needed.

**Comment by SecurityCRob** [comment]
Well, well, well.  Indeed we DO.  I'll see what needs updated there and file PRs.  Thanks for reminding me!

**Comment by marcelamelara** [comment]
Thanks for getting this started @SecurityCRob ! I think this work will very much help address parts of #268. I left a couple comments in the spreadsheet, and I did notice that some of these requirements may be out of sync with the lifecycle requirements for sandbox/incubating after https://github.com/ossf/tac/pull/262 was merged.

**Comment by SecurityCRob** [comment]
Well, well, well.  Indeed we DO.  I'll see what needs updated there and file PRs.  Thanks for reminding me!

please review this:  https://github.com/ossf/tac/issues/268#issuecomment-1973637882

**Comment by CoS-Harry** [comment]
Hello, as staff we have created a checklist in parallel, it gets into a bit more, procedurally: https://docs.google.com/spreadsheets/d/11om7CbK7sBz57bRUzYNq9i211H-9HA2yIEQL6bHsnqA/edit?usp=sharing

**Comment by SecurityCRob** [comment]
Here is where we will be integrating the checklist (and retiring it after the pr's are merged):
SANDBOX
https://github.com/ossf/tac/pull/274
https://github.com/ossf/tac/pull/282
https://github.com/ossf/tac/pull/275
INCUBATING
https://github.com/ossf/tac/pull/276
https://github.com/ossf/tac/pull/277
https://github.com/ossf/tac/pull/278
GRADUATED
https://github.com/ossf/tac/pull/279
https://github.com/ossf/tac/pull/280
https://github.com/ossf/tac/pull/281

Edits/suggestions and reviews/approvals/nacks welcome please

**Comment by SecurityCRob** [comment]
Almost all the template PRs have been merged (ideally the last two will be done today).  Closing this and retiring the checklist now that we've got things in .md templates.  Thanks all.
