### ISSUE TITLE
Create .github/settings.yml and populate description field

### ISSUE THREAD

**Issue by kaywilliams** [ossf/tac#28]
@rhaning, @dlorenc 

We will be using the description listed in the .github/settings.yml to populate the [OpenSSF website getting started page](https://openssf.org/join/) and include in an upcoming press release. Please create the file and edit the description field to include a short (1-2 sentence) description of the TAC. Due Date - Thursday 10/8/2020

See example here:
https://github.com/ossf/gb-planning-committee/blob/master/.github/settings.yml

**Comment by SecurityCRob** [comment]
Discussed yesterday in TAC call. On hold, pending standardization updates to WGs. Will revisit in 90 days (13June2022)

**Comment by steiza** [comment]
Are we still planning on populating the OpenSSF website from `.github/settings.yml` files in repositories? The page linked in the original comment (https://openssf.org/join/) doesn't have that content, and https://openssf.org/getinvolved/ has links to the working groups already.

**Comment by lehors** [comment]
This is the functionality I was referring to when we talked about getting rid of settings.yml file from WG repos. I had submitted PR #87 to add for this but eventually closed it due to lack of interest. We are clearly not depending on this so I suggest we just close this.
