### ISSUE TITLE
Deprecation Policy for archiving projects, SIGs, WGs

### ISSUE THREAD

**Issue by camaleon2016** [ossf/tac#283]
We may want to consider a deprecation policy for projects, SIGs , or WGs where possible. This would aid in the justification for archiving and allow for a proposed date to officially archive.

**Comment by mlieberman85** [comment]
Agreed. I think we should make sure we record why a project, SIG, etc. gets archived. It will help in the future if someone wants to reintroduce something similar it can help us understand if it will be more successful, or if something new has come up that would mean a group that had "finished" its work should restart on something new.

**Comment by lehors** [comment]
We may need to beef that up but we already have some of this built into the TI lifecycles:

https://github.com/ossf/tac/blob/main/process/working-group-lifecycle.md#to-become-archived
https://github.com/ossf/tac/blob/main/process/project-lifecycle.md#archived
https://github.com/ossf/tac/blob/main/process/sig-lifecycle.md#to-become-archived

**Comment by david-a-wheeler** [comment]
> I think we should make sure we record why a project, SIG, etc. gets archived.

Seems reasonable. I encourage people to allow the answer "no one was found who was willing to maintain it". In such cases, if we *do* later find maintainers, the problem is clearly resolved :-).

**Comment by lehors** [comment]
> > I think we should make sure we record why a project, SIG, etc. gets archived.
> 
> Seems reasonable. I encourage people to allow the answer "no one was found who was willing to maintain it". In such cases, if we _do_ later find maintainers, the problem is clearly resolved :-).

The process to archive a TI involves submitting a PR against the TAC repo with the appropriate template which explicitly requests the reason. See:

https://github.com/ossf/tac/blob/main/process/templates/PROJECT_NAME_archived_stage.md
https://github.com/ossf/tac/blob/main/process/templates/WG_NAME_archived_stage.md
https://github.com/ossf/tac/blob/main/process/templates/SIG_NAME_archived_stage.md

**Comment by SecurityCRob** [comment]
Are the templates @lehors points out sufficient, or so we also need a short process written up so folks understand how to use them?

**Comment by steiza** [comment]
I think between the process doc (e.g. https://github.com/ossf/tac/blob/main/process/working-group-lifecycle.md#to-become-archived) and the template (e.g. https://github.com/ossf/tac/blob/main/process/templates/WG_NAME_archived_stage.md) we have sufficient artifacts.

**Comment by steiza** [comment]
Lets use the process in place (https://github.com/ossf/tac/blob/main/process/working-group-lifecycle.md#to-become-archived), gather feedback, and iterate from there.
