### ISSUE TITLE
Schedule first TAC meeting

### ISSUE THREAD

**Issue by caniszczyk** [ossf/tac#3]
We should setup a simple doodle pool, I believe the third week of August was floated due to people's vacations.

cc: @rhaning @dlorenc

**Comment by dlorenc** [comment]
Doodle poll here: https://doodle.com/poll/yya9ai9txhi55wct

Please fill out if you're interested in attending.

**Comment by caniszczyk** [comment]
It's on the public calendar, it's August 21st

https://calendar.google.com/calendar?cid=czYzdm9lZmhwNWk5cGZsdGI1cTY3bmdwZXNAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ
