### ISSUE TITLE
TAC: Review and approve Security Tooling WG charter

### ISSUE THREAD

**Issue by david-a-wheeler** [ossf/tac#30]

**Comment by mayakacz** [comment]
[Charter](https://github.com/ossf/wg-security-tooling/blob/main/README.md)
* This could use a bit more detail, e.g., what's in scope. There are several projects though!
* CodeQL rules is an empty header

**Comment by joshbressers** [comment]
This group is being reworked a bit, please don't close this issue yet, we need to work on these documents as a working group once things get back off the ground.
