### ISSUE TITLE
Github Enterprise Migration Post Mortem

### ISSUE THREAD

**Issue by Danajoyluck** [ossf/tac#304]
OpenSSF staff member would like to walk through the Github Enterprise Migration Post Mortem during the TAC 4/2 session. 

https://docs.google.com/document/d/1LSL2sejYfkuwzM7mPOleM0UHmENcMhmRgKzhSebzEvk/edit

**Comment by steiza** [comment]
Thank you for walking us through this at the TAC meeting earlier today!
