### ISSUE TITLE
TAC: Review and approve Best Practices WG charter

### ISSUE THREAD

**Issue by david-a-wheeler** [ossf/tac#31]

**Comment by mayakacz** [comment]
[Charter](https://github.com/ossf/wg-best-practices-os-developers/blob/main/README.md)
LGTM
* Suggest removing/filling in blank sections

**Comment by SecurityCRob** [comment]
Best Practices WG will discuss at our next meeting 29March and address outstanding/missing items

**Comment by SecurityCRob** [comment]
This is being managed with https://github.com/ossf/tac/issues/162
