### ISSUE TITLE
[Technical Initiative Funding Request]: Stickers for gittuf

### ISSUE THREAD

**Issue by adityasaky** [ossf/tac#312]
### Problem Statement

We'd like to have stickers for the gittuf project to advertise our work and generally support our other efforts towards community outreach.

### Who does this affect?

gittuf developers, contributors, other interested users and community members.

### Have there been previous attempts to resolve the problem?

No

### Why should it be tackled now and by this TI?

gittuf is part of the OpenSSF sandbox--as I understand it, this is the right place to ask.

### Give an idea of what is required to make the funding initiative happen

Nothing blocks this initiative aside from funds. gittuf has a logo already and we're happy to use whatever vendor is recommended by the OpenSSF for stickers.

### What is going to be needed to deliver this funding initiative?

Approval to print gittuf stickers and some help actually getting them printed via the OpenSSF's default stickers vendor.

### Are there tools or tech that still need to be produced to facilitate the funding initiative?

No

### Give a summary of the requirements that contextualize the costs of the funding initiative

The entire cost here is to get stickers printed (as noted above, other requirements such as having a logo are already fulfilled).

### Who is responsible for doing the work of this funding initiative?

Aditya Sirish A Y

### Who is accountable for doing the work of this funding initiative?

Aditya Sirish A Y

### If the responsible or accountable parties are no longer available, what is the backup contact or plan?

Billy Lynch

### Which technical initiative will this funding initiative be associated with, and will it report to which WG or project?

gittuf

### What license is this funding initiative being used under?

Apache 2.0

### Code of Conduct

- [X] I agree to follow the OpenSSF's Code of Conduct

### List the major milestones by date and identify the overall timeline within which the technical initiative plans to accomplish their goals. Any payments for services, sponsorships, etc., will require LF Legal and Financial review.

We hope to have this approved and stickers printed ASAP, if this is approved. In fact, it'd be great to have this printed ahead of OSS NA next week, though I guess that's a tight turnaround time.

### If this is a request for funding to issue a contract, then OpenSSF will issue that contract. Please provide a Statement of Work (SOW) that we may review. Any contracting action will take 4-6 weeks to issue.

N/A

**Comment by CoS-Harry** [comment]
Generally, marketing material is covered within our existing marketing budget. For OpenSSF projects, we try to design a goose-based logo for the project. Designing the logo and printing such stickers for particular events are both free of charge. We generally offer this service for incubating projects. The TAC can advise us on if this should be offered to Sanbox projects, as well. Please connect with us at operations@openssf.org to begin the request for a logo and marketing material should the TAC approve for sandbox projects.

**Comment by adityasaky** [comment]
@CoS-Harry: gittuf already has a logo, so this is strictly a request for printing that into stickers. :)

**Comment by CoS-Harry** [comment]
Then please send your request to operations@openssf.org. Include the amount, for what event/purpose. We’ll follow-up there. Thanks!
