### ISSUE TITLE
[Technical Initiative Funding Request]: Stickers for RSTUF

### ISSUE THREAD

**Issue by kairoaraujo** [ossf/tac#314]
### Problem Statement

We'd like to have stickers for the RSTUF project to advertise our work and generally support our other efforts towards community outreach.

### Who does this affect?

RSTUF developers, contributors, other interested users and community members.

### Have there been previous attempts to resolve the problem?

No

### Why should it be tackled now and by this TI?

RSTUF is part of the OpenSSF sandbox

### Give an idea of what is required to make the funding initiative happen

Nothing blocks this initiative aside from funds. RSTUF has a logo already and we're happy to use whatever vendor is recommended by the OpenSSF for stickers.

### What is going to be needed to deliver this funding initiative?

Approval to print RSTUF stickers and some help actually getting them printed via the OpenSSF's default stickers vendor.

### Are there tools or tech that still need to be produced to facilitate the funding initiative?

No

### Give a summary of the requirements that contextualize the costs of the funding initiative

The entire cost here is to get stickers printed (as noted above, other requirements such as having a logo are already fulfilled).

### Who is responsible for doing the work of this funding initiative?

Kairo de Araujo (@kairoaraujo)

### Who is accountable for doing the work of this funding initiative?

Kairo de Araujo (@kairoaraujo)

### If the responsible or accountable parties are no longer available, what is the backup contact or plan?

Marting Vrachev (@MVrachev)

### Which technical initiative will this funding initiative be associated with, and will it report to which WG or project?

Securing Software Repositories WG

### What license is this funding initiative being used under?

MIT

### Code of Conduct

- [X] I agree to follow the OpenSSF's Code of Conduct

### List the major milestones by date and identify the overall timeline within which the technical initiative plans to accomplish their goals. Any payments for services, sponsorships, etc., will require LF Legal and Financial review.

We hope to have this approved and stickers printed ASAP, if this is approved.

### If this is a request for funding to issue a contract, then OpenSSF will issue that contract. Please provide a Statement of Work (SOW) that we may review. Any contracting action will take 4-6 weeks to issue.

N/A

**Comment by sevansdell** [comment]
What decision remains to finalize this?

**Comment by hythloda** [comment]
Stickers are shipped
