### ISSUE TITLE
TAC decisioning documentation

### ISSUE THREAD

**Issue by SecurityCRob** [ossf/tac#317]
The TAC shall create documentation describing how decisions are made.  This shall include "small" decisions that do not require the full TAC's review as well as "major" issues that must be formally documented and voted upon by all TAC members.

**Comment by SecurityCRob** [comment]
i created the following PR to address this request - https://github.com/ossf/tac/pull/319

**Comment by sevansdell** [comment]
approved PR. I think it's a great start, and we can iterate on it over time if needed.
