### ISSUE TITLE
[Technical Initiative Funding Request] - S2C2F PAS Submission Funding Request 

### ISSUE THREAD

**Issue by camaleon2016** [ossf/tac#328]
### Problem Statement

S2C2F requires 4k in funding to pay the JDF contracted ISO Editor to help form the correct language in the S2C2F Specification in preparation for ISO PAS submission. 

### Who does this affect?

Without this necessary step the spec will not be in proper form for PAS submission and will not be balloted. 

### Have there been previous attempts to resolve the problem?

No. S2C2F is requesting funding through the OpenSSF for the first time and as a first course of action.

### Why should it be tackled now and by this TI?

S2C2F Project is ready and has been accepted by the JDF to begin the process for PAS submission

### Give an idea of what is required to make the funding initiative happen

Funding will cover the JDF contracted ISO Editors work in total. 

### What is going to be needed to deliver this funding initiative?

The JDF contracted ISO Editor is all that is required. 

### Are there tools or tech that still need to be produced to facilitate the funding initiative?

NO.

### Give a summary of the requirements that contextualize the costs of the funding initiative

4k will cover the JDF contracted ISO Editor requested 3-5k requirement for proper formatting of the S2C2F spec into a ballotable ISO Standard

### Who is responsible for doing the work of this funding initiative?

JDF contracted ISO Editor. Contact in the JDF is Seth Newbury seth@jointdevelopment.org

### Who is accountable for doing the work of this funding initiative?

Jay White, Adrian Diglio, Tom Bedford

### If the responsible or accountable parties are no longer available, what is the backup contact or plan?

JDF - Seth Newbury, Jory Burson

### Which technical initiative will this funding initiative be associated with, and will it report to which WG or project?

S2C2F Project under the SUpply Chain Integrity WG

### What license is this funding initiative being used under?

Community Specification License 1.0

### Code of Conduct

- [X] I agree to follow the OpenSSF's Code of Conduct

### List the major milestones by date and identify the overall timeline within which the technical initiative plans to accomplish their goals. Any payments for services, sponsorships, etc., will require LF Legal and Financial review.

Balloting is currently TBD, but we are anticipating finalizing the process by Jan 2025. 4k in funding will only be used to pay the JDF contracted ISO Editor to prepare the spec for entering the PAS Balloting process.

### If this is a request for funding to issue a contract, then OpenSSF will issue that contract. Please provide a Statement of Work (SOW) that we may review. Any contracting action will take 4-6 weeks to issue.

JDF issues the contract.

**Comment by SecurityCRob** [comment]
The TAC will review this at our next meeting (28May).  I encourage everyone to review & comment beforehand

**Comment by SecurityCRob** [comment]
@camaleon2016 @adriandiglio can you add a bit of context here as to why making s2c2f an IOS standard is beneficial.  What will achieving that enable for the group and consumers of the framework?  If this is NOT funded, what is at risk?

**Comment by camaleon2016** [comment]
We'll add more context today.

Jay

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by torgo** [comment]
This seems like a reasonable use of TAC funding to me and in line with our discussions. 👍🏻

**Comment by steiza** [comment]
I would love for @camaleon2016 / @omkhar to summarize here what they mentioned at today's TAC meeting about how ISO standardization helps with OpenSSF's engagement with EU public sector on the Cyber Resilience Act (and possibly other public / private sector conversations?)

That said, this seems like a good way for the OpenSSF to start exploring turning community specifications into standards, and seeing what opportunities that unlocks. +1 from me.

**Comment by omkhar** [comment]
@steiza sure things!

In standards land, there are broadly two kinds of standards:
( from our good friend [Wikipedia](https://en.wikipedia.org/wiki/De_jure))

> In law and government, de jure (/deɪ ˈdʒʊəri, di -, - ˈjʊər-/, Latin: [deː ˈjuːre]; lit. 'by law') describes practices that are legally recognized, regardless of whether the practice exists in reality.[1] In contrast, de facto ('in fact') describes situations that exist in reality, even if not formally recognized.

De jure standards typically bear a mark or recognition that the standard has been through an official standardization process. Ex: ISO/IEC 27001:2013 went through the JTC1 standardization process. De facto standards (S2C2F as an example) 
don't have a current mark nor has it been through the standardization process, even though it may be used extensively.

The goal of putting a de facto standard through the de jure process is two fold:

1. When recognized as a de jure standard, we can more easily apply it to regulatory or governance standardization efforts like the EU CRA. If the standards body see that S2C2F is an ISO recognized standard, it makes it much easier to adopt.
2. Commercially, when transacting with governments or regulatory agencies, declaring that a particular product/procedure/method is conformant with an international standard allows you to attest conformance with a requirement.

Overall, I think it's a Good Thing (tm) and something which we may wish to consider for other OpenSSF work (ex SLSA) if the TAC should choose.

**Comment by SecurityCRob** [comment]
Is this ask for $4000 or "$3000-$5000"?  or both?

**Comment by camaleon2016** [comment]
3k-5k. 4k was in case the number had to be static.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by sevansdell** [comment]
I will be out for the TAC meeting, but don't have any additional questions, and support this TI funding request. If this comment of support could be counted as a vote if needed, please use it.

**Comment by marcelamelara** [comment]
Having this reviewed this ask, it's not a huge $ amount for an outcome that seems overall beneficial and may pave the trail for other OpenSSF specs. Can @camaleon2016 or @adriandiglio please comment on the impact to the project if the funding request isn't approved in Q2?

**Comment by marcelamelara** [comment]
Since we're getting close to the decision deadline, and I'm still on the fence about supporting this request _in Q2_, my vote is to defer this request.

**Comment by riaankleinhans** [comment]
Gitvote was added as a tool to test for stream lining the TI Funding process.
The members of the GH group "TAC" can vote by commenting with an +1. -1 or eye on the Gitvote block in this issue.
Until the TAC is satisfied with the process the GitVote outcome would not be binding.

Community members can show their support by also voting, however only the "TAC" GH Group's votes will count.

The current passing threshold is 70% and the committee is the [TAG GH group](https://github.com/orgs/ossf/teams/tac).
The vote say open fo 6 week and an announcement is sent on the GH/TAC/Discussion

All these parameters can by fine tuned or changed [here](https://github.com/ossf/tac/blob/main/.gitvote.yml)
Please reach out if you have any questions.

**Comment by lehors** [comment]
This request was actually withdrawn so closing.
/cancel-vote
