### ISSUE TITLE
TAC: Review and approve Digital Identity Attestation WG charter

### ISSUE THREAD

**Issue by david-a-wheeler** [ossf/tac#33]

**Comment by mayakacz** [comment]
[Charter](https://github.com/ossf/wg-digital-identity-attestation/blob/main/README.md)
* the objective and beginning of the motivation seem to be updated to be about provenance, the rest is still very much about user identity. I realize these are related, but this might need a bit of an update still. My understanding of the "goals" is more like "understand where code comes from and who can modify it"
* the example motivation could be more closely tied to the objective

**Comment by SecurityCRob** [comment]
Hello.  As part of 2022 backlog grooming, each open TAC issue is being reviewed for applicability/completeness.  Has this request been completed?  If so, can that be noted in a comment please.  If not, what actions need taken to continue moving this issue to completion? If we do not here back from you within two weeks, this issue will be closed (23March2022).  Thank you.

**Comment by SecurityCRob** [comment]
This is being managed with https://github.com/ossf/tac/issues/162
