### ISSUE TITLE
WG lifecycle update

### ISSUE THREAD

**Issue by sevansdell** [ossf/tac#331]
When a WG is archived, projects and SIGs that reported to the WG need rehomed. What should be the process? After discussion here, update https://github.com/ossf/tac/blob/main/process/working-group-lifecycle.md.

**Comment by SecurityCRob** [comment]
I imagine they only would need a new home if they are still active.  I suppose a process might look like:
1.) Overseeing TI will be moving to "Archived" status
2.) Active subgroups (SIG or project) is still active and desires to continue collaborating
3.) Subgroup reviews active TIs to see if there is alignment of vision and purpose (https://openssf.org/community/openssf-working-groups/)
4.) Subgroup meets with TI leader ad group to discuss adoption
5.) New TI agrees to become new oversight group for subgroup
6.) PRs filed in TI and TAC repos to note change of status
7.) Archiving TI has PR filed noting new status

thoughts?

**Comment by lehors** [comment]
Yeah, I would simply say something like:

Upon archival of a WG, any reporting SIG or project which wants to continue operating needs to look for another WG to report to. Upon agreement from both parties the TIs and TAC repos (e.g., READMEs) should be updated to reflect the change.

The latter actually implies that the TAC gets notified which gives an opportunity for the TAC to intervene if it has any concerns with the move but we could request explicit notification if deemed necessary.

**Comment by SecurityCRob** [comment]
Linking to this: https://github.com/ossf/tac/pull/351

**Comment by SecurityCRob** [comment]
the proposed process has been merged.  closing
