### ISSUE TITLE
TAC: Review and approve Securing Critical Projects WG charter

### ISSUE THREAD

**Issue by david-a-wheeler** [ossf/tac#34]

**Comment by mayakacz** [comment]
[Charter](https://github.com/ossf/wg-securing-critical-projects/blob/main/README.md)
LGTM.
* Suggest filling in or removing empty sections if not needed (do we need all sections of the template filled in?)
* Remove reference to empty governance info

**Comment by SecurityCRob** [comment]
Hello.  As part of 2022 backlog grooming, each open TAC issue is being reviewed for applicability/completeness.  Has this request been completed?  If so, can that be noted in a comment please.  If not, what actions need taken to continue moving this issue to completion? If we do not here back from you within two weeks, this issue will be closed (23March2022).  Thank you.
