### ISSUE TITLE
TAC: Announcement of OWASP SKF's new release

### ISSUE THREAD

**Issue by xcorail** [ossf/tac#36]
There is a new release of OWASP Security Knowledge Framework coming up. This learning platform has been chosen by the OSSF Best Practices working group as part of his strategy, and we'd like to announce this release and mention that it's part of the OSSF effort.

We'd like 
1. The TAC's review and suggestions on the announcement text below 
2. To know if there is an opportunity to include something about SKF in the upcoming OSSF press release

cc @blabla1337 @RiieCco 

> OWASP Security knowledge framework (SKF) has had a major refactor!
>
> Thanks to Google Summer of Code we were able to get in contact
with an awesome UX designer (Akash) that helped us create a new and 
fresh look and feel on the OWASP SKF application!
Not only did the front-end changed a lot, we also added a feature
for our SKF-labs and OWASP-Juice Shop that helps you to deploy your 
favourite labs on the spot trough the SKF UI!
>
> We created a standardized set of Design patterns to go. 
These design patterns make it easier than ever to get started 
with ASVS and get your requirements in your projects. 
>
> ASVS level 1 controls now also have best practices
code examples and automated test cases correlated (OWASP-ZAP, CodeQL …)
to them so you know where to get started for your test automation!
>
> We are also really happy to announce that we have started a 
collaboration with the OSSF to help improve SKF with a dedicated
team of experts to further iterate the platform to the next level.
Trough OSSF, we intend to provide SKF as a SaaS platform so you no
longer have to find a place to host it, making it easier than ever 
before to get started with the SKF, and building applications secure by design!
>
> More information can be found [on GitHub](https://github.com/blabla1337/skf-flask)

**Comment by kaywilliams** [comment]
Hi @xcorail, we can check with @LindsayLF , but I suspect it is too late to include in the 10/29 press release.  The press release is near final and we have been reviewing with with PR contacts from our member companies. We do have the Town Hall meeting on 11/9 and can highlight it there. And we are planning quarterly press releases, so can consider for the next version in late January.

Nice work on the Secure Knowledge Framework (SKF) improvements!

**Comment by david-a-wheeler** [comment]
On Oct 22, 2020, at 3:53 PM, Xavier RENE-CORAIL <notifications@github.com> wrote:
> There is a new release of OWASP Security Knowledge Framework coming up.

Congrats!

I just sent to the OpenSSF GB some draft text about the OpenSSF for the Linux Foundation’s annual report. It’s an easy way to let others know about the OpenSSF.

You’ll be happy to know that I included text about the OWASP SKF.

Below is the draft text, if there comments please let me know.

--- David A. Wheeler


=====


Addressing software supply chain and security challenges: OpenSSF


The Open Source Security Foundation (OpenSSF) was publicly announced on August 3rd. It is a cross-industry collaboration that brings together leaders to improve the security of open source software (OSS) by building a broader community, targeted initiatives, and best practices. The OpenSSF combines multiple open source security initiatives under one foundation to accelerate work through cross-industry support, including the LF’s Core Infrastructure Initiative (CII).

The OpenSSF governing board members are from IBM, GitHub, NCC Group, Microsoft, Google, Red Hat, JPMorgan Chase, and OWASP. It has formed several working groups (WGs) to focus on various issues:
	• Identifying Security Threats - security metrics for open source projects
	• Security Tooling - state of the art, globally accessible security tools
	• Best Practices - awareness and education of security best practices
	• Vulnerability Disclosures - efficient vulnerability reporting and remediation
	• Digital Identity Attestation - ensuring the provenance of open source code
	• Securing Critical Projects - hands-on help for critical open source projects

There are now 35 OpenSSF members: Arduino; AuriStor Inc.; Canonical Group Limited; Debricked; Facebook, Inc.; GitHub, Inc.; GitLab, Inc.; Google; HackerOne; Huawei Technologies Co., Ltd.; iExec Blockchain Tech; Intel Corporation; International Business Machines Corporation (IBM); JPMorgan Chase; Laboratory for Innovation Science at Harvard; Microsoft Corporation; NCC Group; Okta Inc.; Open Source Technology Improvement Fund, Inc.; Open Web Application Security Project; Polyverse Corporation; Purdue University; Red Hat Inc.; Renesas Electronics Corporation; SAFECode; Samsung Electronics Co. Ltd.; Spectral; StackHawk; SUSE LLC; Telefonica; Tencent Holdings Limited; Trail of Bits; Uber Technologies, Inc.; VMware, Inc.; and WhiteSource.

The OpenSSF is just getting started, but has already produced some results. It has released a trio of freely-available courses on EdX on developing secure software fundamentals, along with a professional certificate so developers can show they’ve understood it. It has collaboratively released the OWASP Security Knowledge Framework (SKF), which includes hands-on labs for developers.The CII Best Practices badge continues to grow; over 3,400 projects participate and 340 have earned passing badges. The OpenSSF is also working with Harvard to release a survey of OSS developers, to have an improved  understanding of their OSS project security needs.

To get involved, visit: https://openssf.org/getinvolved/

**Comment by LindsayLF** [comment]
Hi @kaywilliams & @xcorail - Yes, that is correct, we are unfortunately too late to add or make content shifts to the upcoming press release. I agree that this would be a great highlight for the Town Hall.  Thanks!

**Comment by dlorenc** [comment]
Are you still waiting on anything here given that this is too late for the press release? Can this be closed?
