### ISSUE TITLE
Should Scorecard Adoption in project-lifecycle.md besides TI Gives? 

### ISSUE THREAD

**Issue by Danajoyluck** [ossf/tac#366]
[TI Gives/Requirements for TI that develops code](https://github.com/ossf/tac/blob/main/process/TI-Gives%2BGets.md#givesrequirements-1) has "Must use Scorecards". Should this be in the [project-lifecycle.md Incubation Entry Requirements and Considerations](https://github.com/ossf/tac/blob/main/process/project-lifecycle.md#incubation-entry-requirements-and-considerations) as well?

**Comment by lehors** [comment]
This actually shows why it's not a good idea to have the same info in multiple places. That's why for the security baseline requirements I suggested simply adding links. I think we should make sure we have the right info in one place and delete the other - it doesn't really matter to me which one.

**Comment by Danajoyluck** [comment]
Thank you @lehors I think we are good......security baseline for incubating project has reference to TAC requirement.
