### ISSUE TITLE
[IP policy and license review] Bomctl Sandbox Project Entry

### ISSUE THREAD

**Issue by idunbarh** [ossf/tac#368]
[Bomctl](https://github.com/bomctl/bomctl) is seeking Sandbox Project Entry into the OpenSSF under the Security Tools WG.

In following the [Sandbox Process](https://github.com/ossf/tac/blob/main/process/project-lifecycle.md#submission-process) - the bomctl maintainers are requesting the "one-time IP policy and license review with The Linux Foundation" as part of our sandbox application.

Bomctl Links

- https://github.com/bomctl/bomctl

Bomctl is licensed as [apache-2](https://github.com/bomctl/bomctl/blob/main/LICENSE).

CC/ @hythloda @jeffcshapiro

**Comment by hythloda** [comment]
No issues found;

 LICENSE INTAKE SCAN & ANALYSIS:  OpenSSF:  bomctl

- This intake scan is a static analysis of the source code in your repository.  A dependency scan was not performed.  Once a project is added to LFX [https://security.lfx.linuxfoundation.org/], you can use SNYK to view a dependency scan for both licenses and vulnerabilities.

 CODE SCANNED:  [pulled 16–Aug-2024]

- https://github.com/bomctl

 PROJECT LICENSE: Apache-2.0

- Top level project license file found in repo.

SPDX LICENSE IDENTIFIERS:  SPDX license identifiers were found in source file headers.

PERMISSIVE LICENSES:  Apache-2.0

COPYLEFT LICENSES:  None found

SOURCE AVAILABLE LICENSES:  None found

PROPRIETARY LICENSES:  None found

LICENSE CONFLICTS: None found

BINARY / PACKAGE FILES:  None found

THIRD PARTY CODE / DEPENDENCIES:  None found

THIRD PARTY NOTICE FILE:  None found

SUMMARY FINDINGS:  The project is under the Apache-2.0 License.  No license conflicts were found.
