### ISSUE TITLE
Provide Logos to Sandbox Projects

### ISSUE THREAD

**Issue by presidentoor** [ossf/tac#369]
Please vote to allow sandbox projects to obtain a logo. A logo galvanizes individuals and can be a good community building / support.

**Comment by SecurityCRob** [comment]
Is this about using the "generic" logos (https://github.com/ossf/tac/tree/main/files/images) or about asking for creative assistance in creating their own logo?  We already state sandboxes are allowed to use a logo - https://github.com/ossf/tac/blob/main/process/TI-Gives%2BGets.md#getsbenefits

**Comment by CoS-Harry** [comment]
To leverage creative services to create a goose-native logo. We have an issue where if we don't provide a logo to sandbox projects they are free to create their own. It would be more effective from a brand consistency, workflow, and work effort standpoint.

**Comment by SecurityCRob** [comment]
In our Gives & Gets (https://github.com/ossf/tac/blob/main/process/TI-Gives%2BGets.md#incubating-level-gives--gets) we list this as a benefit for Incubating TIs as an encouragement to progress in the lifecycle.  We certainly have the ability to change that if the TAC agrees to the change.

**Comment by lehors** [comment]
The problem with watering down the requirements for this kind of benefits is that it effectively removes some of the incentives to work on moving to the next lifecycle stage. In my experience it is always difficult to strike the right balance. I've seen in other projects logos being changed so I don't know that if they go on and create their own it's necessarily a big deal. They can always get a new one once they get to Incubation.
The entry to sandbox is very simple on the basis that the cost of adding a project at that level is minimal. I assume providing creative services is not free. How much is that? Is it worth spending on a project that may fold in a few months? I can't say that I'm totally opposed but I'm not really in favor for now.

**Comment by CoS-Harry** [comment]
The services are free. I think we can do this on a request basis for sandbox and allow that as an option versus (a) them creating their own which is a headache to unwind from a brand recognition standpoint and (b) this policy of no stickers at sandbox hasn't been historically enforced so we now have a mishmash of projects with and without logos. I would suggest moving forward with this as a vote of the TAC to amend the gives and gets and allow this benefit on a request basis.

**Comment by david-a-wheeler** [comment]
I support adding logos to sandbox projects, as long as there's some *other* advantage/incentive to moving beyond sandbox that projects typically care about. I think the other advantages are enough to meet that condition.

One advantage of giving logos to sandbox projects is that it makes the sandbox project more memorable & might help them get more participants. More participants could help them move up from sandbox faster.

**Comment by sevansdell** [comment]
Recommend use the sandbox BADGE, and when move to incubating stage, get a custom goose LOGO along with the Incubating badge. 

Call for data/ comments from other sandbox lifecycle leaders: would a custom goose LOGO in addition to the cute eggs-in-a-nest sandbox BADGE help drive contributions and gathering contributors to move to incubating? Specifically to bomctl or protobom (who have sandbox logos in the meantime while we sort this out). Did it help your teams?

**Comment by steiza** [comment]
The consensus we reached at the TAC meeting today was that sandbox technical initiatives will get the sandbox badge, and once they are incubating they will be eligible for a custom goose logo.
