### ISSUE TITLE
TAC: OpenSSF Technical Roadmap

### ISSUE THREAD

**Issue by kaywilliams** [ossf/tac#37]
TAC to create OpenSSF 12-month Roadmap in time for announcement at the next quarterly press release (end of January 2021). 

Starter document here: https://docs.google.com/document/d/1yLo713am8_hvU90Lw0YdYBvXhfTjh7Shn4ATXPNX9ic/edit?ts=5f970f6b#heading=h.vpw70bcgenot

Technical Vision is tracked at: #40

**Comment by dlorenc** [comment]
What's the intended relationship between that document and the one shared by Ryan/David?

https://docs.google.com/document/d/1yLo713am8_hvU90Lw0YdYBvXhfTjh7Shn4ATXPNX9ic/edit?ts=5f987cf5#heading=h.vpw70bcgenot

**Comment by kaywilliams** [comment]
Created Technical Roadmap draft document for discussion and comment.

https://docs.google.com/document/d/1wMP_BTmfwC1xBq0cLpwh8gFwAef0QhYmKHNpcAPUJKg/edit#

**Comment by dlorenc** [comment]
As discussed on the TAC call today, my main feedback is that I don't think many WGs will be able to produce accurate/meaningful items here past the next immediate quarter.

I'd suggest starting with a few specific ones to understand what their long term goals are (if they have any), and how they think about planning, then see what type of roadmap these can be formatted into.

For the WGs I'm involved in, I could probably give you one or two items that we're working on right now and a bunch of other ideas people have had, but no sense of timeline.

**Comment by SecurityCRob** [comment]
Hello.  As part of 2022 backlog grooming, each open TAC issue is being reviewed for applicability/completeness.  Has this request been completed?  If so, can that be noted in a comment please.  If not, what actions need taken to continue moving this issue to completion? Is this an item that the TAC needs to address in 2022?  

If we do not here back from you within two weeks, this issue will be closed (23March2022).  Thank you.

**Comment by SecurityCRob** [comment]
Discussed yesterday in TAC call.  @jorydotcom is leading efforts for materials to document and describe foundation's working group, projects, etc.  . Will revisit in 90 days (13June2022)

**Comment by SecurityCRob** [comment]
This is now being managed with https://github.com/ossf/tac/issues/177
