### ISSUE TITLE
[Technical Initiative Funding Request]: Cloud credits for gittuf's GitHub app

### ISSUE THREAD

**Issue by adityasaky** [ossf/tac#378]
### Technical Initiative

gittuf

### Lifecycle Phase

sandbox

### Funding amount

$50 a month

### Problem Statement

We have been working on a GitHub app for gittuf hosted on Google Cloud. We need cloud credits to serve the app for users who want to add it to their repositories.

### Who does this affect?

The solution is for the gittuf developers / maintainers who want to run the app.

### Have there been previous attempts to resolve the problem?

No

### Why should it be tackled now and by this TI?

gittuf is part of the OpenSSF sandbox, and the GitHub app would help repositories adopt gittuf in a user friendly manner.

### Give an idea of what is required to make the funding initiative happen

The cloud credits are approved and gittuf maintainers are given access to Google Cloud via the OpenSSF. Following that, the maintainers (myself, @wlynch, etc.) will operate the GitHub app.

### What is going to be needed to deliver this funding initiative?

Cloud credits or access to a Google Cloud project backed by an OpenSSF controlled billing account.

### Give a summary of the requirements that contextualize the costs of the funding initiative

The estimated cost would cover the cost of pulling together several Google Cloud services (cloud run, KMS, secrets management, etc.) to operate the gittuf GitHub app.

### Who is responsible for doing the work of this funding initiative?

Aditya Sirish A Yelgundhalli (@adityasaky)

### Who is accountable for doing the work of this funding initiative?

Aditya Sirish A Yelgundhalli (@adityasaky)

### If the responsible or accountable parties are no longer available, what is the backup contact or plan?

Billy Lynch (@wlynch)

### What license is this funding initiative being used under?

Apache 2.0

### Code of Conduct

- [X] I agree to follow the OpenSSF's Code of Conduct

### List the major milestones by date and identify the overall timeline within which the technical initiative plans to accomplish their goals. Any payments for services, sponsorships, etc., will require LF Legal and Financial review.

We expect the app to be live and serving repositories that opt in to using it within a month of the funding request being approved.

**Comment by SecurityCRob** [comment]
I suggest we approve this request until the end of 2025, at which time the project can demonstrate progress and reapply.
That would be 15mos x $50/mo = $750 for this request

**Comment by riaankleinhans** [comment]
Gitvote was added as a tool to test for stream lining the TI Funding process.
The members of the GH group "TAC" can vote by commenting with an +1. -1 or eye on the Gitvote block in this issue.
Until the TAC is satisfied with the process the GitVote outcome would not be binding.

Community members can show their support by also voting, however only the "TAC" GH Group's votes will count.

The current passing threshold is 70% and the committee is the [TAG GH group](https://github.com/orgs/ossf/teams/tac).
The vote say open fo 6 week and an announcement is sent on the GH/TAC/Discussion

All these parameters can by fine tuned or changed [here](https://github.com/ossf/tac/blob/main/.gitvote.yml)
Please reach out if you have any questions.

**Comment by SecurityCRob** [comment]
A quorum of the TAC met on 17Sept to discuss Q3 TI Funding Requests.  

Consensus of the group was to approve this funding request.  We'll pass this to staff to manage from this point.

**Comment by sevansdell** [comment]
This vote tool is also cancelled. How are we proceeding instead?

**Comment by steiza** [comment]
> This vote tool is also cancelled. How are we proceeding instead?

Yeah, we got a little over-zealous when trying out the new voting application. This was also approved by a quorum of the TAC on Sept 17th: https://github.com/ossf/tac/issues/378#issuecomment-2371324664.

Coincidentally, this was also the other issue I was asking @riaankleinhans about at the TAC meeting yesterday. On the [funding project board](https://github.com/orgs/ossf/projects/25/views/1) it's sitting in `Funding Approved` but hasn't yet moved to `Funding in Execution`.

**Comment by riaankleinhans** [comment]
I moved this allong on the Project board.
In communication with the project.
@adityasaky do you think we can close this issue?

**Comment by kj-powell** [comment]
Hi all- the TAC has agreed to fund gittuf's cloud credit costs in 2026. Please reach out to me if you have any questions.
