### ISSUE TITLE
Adding Gitvote to TAC repo for TI voting

### ISSUE THREAD

**Issue by riaankleinhans** [ossf/tac#384]
## What:
Install Gitvote on OSSF/TAC repo.
The Application is a CNCF initiative that allow voting in GH.
The eligible voters are managed through GH teams or as individuals via the .gitvote.yml file

## Why:
To make TI funding evaluation, discussion and approval more transparent and simpler to manage.

## How:
The [Gitvote application](https://github.com/cncf/gitvote) is installed through  this [link](https://github.com/apps/git-vote)
The .gitvote.yml file would be submitted though a PR.

## Who:
Agreement should be reach by the OSSF & TAC leadership
The TAC must agree on which GH team / individuals should vote in TI funding initiatives
@riaankleinhans would manage the implementation

## How:
Then an issue for TI funding is created anyone on the TAC repo could add the `/vote` function through a GH comment.
Eligible voters can vote through :+1: , :-1:  or :eyes: 
Anyone can show support by also adding their vote, but only the votes of voters listed in the ./gotvote.yml file are counted.
Once the set vote approval threshold (50%, 70% or any other number agreed by the TAC ) is reached an announcement is publish in the [GH Discussion section](https://github.com/ossf/tac/discussions) of the repo. 

An example can be seen here:
https://github.com/riaankleinhans/tac-gitvote-test/issues/3

And a CNCF closed example here:
https://github.com/cncf/toc/issues/1332

**Comment by SecurityCRob** [comment]
I think this will be a nice approach to help streamline things for the TAC as well as clearly show the results of the polling.

👍
