### ISSUE TITLE
Should all OpenSSF projects/repos have CII badges?

### ISSUE THREAD

**Issue by christo4ferris** [ossf/tac#45]
We should be eating our own cooking, don't you think?

**Comment by david-a-wheeler** [comment]
I would certainly encourage it :-). At least one does - the CII Best Practices badge project earns it own badge :-).

If anyone needs help, I'd be happy to help. Send me an email at dwheeler AT linuxfoundation DOT org, or use the OpenSSF Slack.

**Comment by dlorenc** [comment]
Yes! Big +1 on that.

**Comment by david-a-wheeler** [comment]
@dlorenc - do you want to start the process for [OpenSSF Scorecard](https://github.com/ossf/scorecard)? We could get on a Zoom call together if you'd like, but we always urge project leads to start the process.

**Comment by dlorenc** [comment]
I've done it a few times before, should be fine on that. I think the bigger issue is that we're likely not actually meeting all the requirements there yet!

**Comment by david-a-wheeler** [comment]
@dlorenc - that's okay! I think showing that things are "in progress" is precisely the right message to send.

**Comment by SecurityCRob** [comment]
+1 our own projects getting badges helps on multiple levels:
1.) shameless self-advertising
2.) spreading of security good practices
3.) show we respect and follow our own guidelines
4.) will give Badges project feedback to improve processes and overall quality of earning those badges

**Comment by christo4ferris** [comment]
+100

Chris

**Comment by di** [comment]
It seems like this could be added at some point as an entry requirement to a stage in the [Project Lifecycle document](https://github.com/ossf/tac/blob/main/process/project-lifecycle.md).

**Comment by SecurityCRob** [comment]
This wlll be accounted for as this PR is merged - https://github.com/ossf/tac/pull/226/

**Comment by SecurityCRob** [comment]
pr merged 11dec2023
