### ISSUE TITLE
TAC Election Process: Member makeup

### ISSUE THREAD

**Issue by rhaning** [ossf/tac#52]
**Proposal:**
Keep TAC size at 7 members
- 4 members are elected by the governing board
- 3 members are elected by Technical Initiative contributors. Each TI determines who is a contributor and may vote. 1 vote per person across all Technical Initiatives

**Comment by dlorenc** [comment]
+1 to this! I'm also happy swapping the 3/4 split the other way.

**Comment by dlorenc** [comment]
Closing as the election has been finished and this is actually in the charter itself.
