### ISSUE TITLE
TAC Election Process: Nomination requirements

### ISSUE THREAD

**Issue by rhaning** [ossf/tac#53]
- Who is eligible to be nominated?
- Must they be OpenSSF members?
- May individuals self nominate?

**Comment by dlorenc** [comment]
My thoughts:

- Anyone. Ideally their nomination should include a statement about their previous contributions to the OpenSSF and their planned future contributions on the TAC
- No. But, OpenSSF members do have direct input on the election via the GB-selected seats.
- Yes - see the statement they should include from above.

**Comment by dlorenc** [comment]
Closing as the election has finished!
