### ISSUE TITLE
TAC Election Process: Term limits

### ISSUE THREAD

**Issue by rhaning** [ossf/tac#54]
**Proposal:**

- 2 year staggered terms. Even year, GB vote. Odd year, TI vote.

**Comment by dlorenc** [comment]
The title here is "term limits". Maybe a better title would be "term lengths"? Term limits would indicate restrictions on how many terms a person can run for.

**Comment by jhutchings1** [comment]
> The title here is "term limits". Maybe a better title would be "term lengths"?

Agreed, I don't think there's a practical need for us to limit how many times a person is on the TAC board.

**Comment by rhaning** [comment]
I've renamed the title to be "term lengths", that is more accurate. Thanks.

**Comment by dlorenc** [comment]
Closing as the election has finished!
