### ISSUE TITLE
[Project-Security-Reviews] Change license to CC-BY-4.0

### ISSUE THREAD

**Issue by scovetta** [ossf/tac#56]
We'd like to change the license for the [Project-Security-Reviews](https://github.com/ossf/Project-Security-Reviews) from the current/default (Apache) to CC-BY-4.0. (The repository is not public, so perhaps I should be saying, "we'd like to start with the CC-BY-4.0 license."

Since the overwhelming majority of the content in the repository/project will be user-contributed documentation (security reviews) and as such, we think that requiring attribution in any derivatives is important.

There will be a few other things in the repository (build scripts, validation, templates, etc.) that could be licensed under Apache if needed.

**Comment by david-a-wheeler** [comment]
I should note that the OpenSSF Technical Charter specifically says to use CC-BY for non-code repositories, so I think this is completely consistent with the OpenSSF set. That said, I think it's best to make sure that license discussions are over-communicated :-).

Also, this is a good time to make sure everyone's aware of the Project-Security-Reviews project. The goal is to provide a place to identify security reviews of OSS (either directly, or a summary with link to the detailed review). That way, the security metrics dashboard can point to existing security reviews if they're known.

**Comment by david-a-wheeler** [comment]
For details, see: https://github.com/ossf/Project-Security-Reviews/pull/8

**Comment by scovetta** [comment]
Great, thank you @david-a-wheeler! Cross-posted in the OpenSSF slack/#general, here is some high level information about the project:

Hi All! We've been working on the Security Reviews project, and would like to raise awareness within OpenSSF about it before we go live.
The purpose of the project is to establish a community collection of security reviews performed against open source projects. These will contain opinions of the security quality of a project based on analyzed data (e.g. static analysis, fuzzing, existing reports, etc.). We expect this to be valuable for a few reasons:

- The vast majority of open source projects don't have any indicators of security quality.
- Practically no positive indicators of security quality are available to the public (e.g. "We looked at this, ran tools, and it looks fine.")
- Consumers use thousands or tens of thousands of projects; having a collection of those reviews can make it easier to consume and integrate.
- This isn't "opt in" by the project.

This isn't intended to be a "0-day disclosure" resource - we expect all content to be either publicly known or for severe vulnerabilities, to have already been fixed. All submissions will be reviewed (via a PR), but we still have some things to work out before we launch.

The project is located at [https://github.com/ossf/Project-Security-Reviews](https://github.com/ossf/Project-Security-Reviews) (we're planning to rename it to just 'security-reviews' before we launch). We'd greatly appreciate thoughts/opinions on this.

**Comment by david-a-wheeler** [comment]
FYI, OSTIF has done several reviews of OSS that are publicly available. I've asked them to contribute summaries to this Project-Security-Reviews (security-reviews database, with links to their full reports, and they were willing! That will make it much easier for people to find their security reviews, helping everyone. So we'll start with some security reviews from Microsoft and OSTIF at least (and maybe more!).

**Comment by scovetta** [comment]
That's terrific!!

**Comment by jenniferfernick** [comment]
This is great - to keep it useful at scale can we define a nomenclature for submissions to make them easier to navigate, and maybe a labelling scheme for type of review? I'd be happy to add some of NCC Group's public reports as well

Here are some of the recent ones but our archives go back further:
https://research.nccgroup.com/category/public-report/

**Comment by scovetta** [comment]
Awesome! That sounds great!

I was hoping to avoid one of the [two hard problems](https://martinfowler.com/bliki/TwoHardThings.html) in computer science (hence just going with review-1.md, review-2.md, etc.), and keeping any metadata to the properties section:

```
<!--
publication-state: published
access: public
author: "Microsoft OSS Security Team <oss-security-team@microsoft.com>"
domain: security
methodology-summary: static-analysis;code-review;web-search
opinion: secure
package-urls:
- "pkg:npm/left-pad@1.3.0"
review-date: 2019-04-08
scope: implementation/full
schema-version: 1.0
severity: not-applicable
SPDX-License-Identifier: CC-BY-4.0
-->
```

But we should also have a github.io page, or another "reader-centric" view of the contents, where we can make it look really nice.

**Comment by david-a-wheeler** [comment]
I think that's terrible for humans. I think it'd be better to have names be "something related to the content" and "not already in use". Then the names at least *hint* at their content.

**Comment by scovetta** [comment]
Hmm, so for cases where there's an external assessment, something like `trail-of-bits-zlib-assessment-2016.md`. How about when it's a security review done for the purposes of publishing it? (Our team has struggled with a meaningful title, after a while, they're all just "security review".)

What type of content would be meaningful in the title?

* Who did it?
* What the scope was?
* What the opinion was?

Any of these would be duplicative with the metadata in the file, but that wouldn't be the worst thing in the world.

**Comment by dlorenc** [comment]
This seems to be getting a little off-topic from the original CC license question. IMO the license request is fine for two reasons:

-  The charters as they stand currently licensing decisions up to the WGs. 
- We have some proposed charter changes in flight that limit licenses to a GB-approved set, and CC is on that set.

So, either way you should be covered.

**Comment by scovetta** [comment]
Thanks @dlorenc! Closing here, we'll continue the discussion on related things on the project issues pages.
