### ISSUE TITLE
[GitHub org request] Add organization/team

### ISSUE THREAD

**Issue by naveensrinivasan** [ossf/tac#57]
I'd like to add
- [ ] an organization
- [x] an individual

### Organization - create a team

If your organization is a [member of OpenSSF](https://openssf.org/about/members/), we will [create a GitHub team](https://docs.github.com/en/free-pro-team@latest/github/setting-up-and-managing-organizations-and-teams/about-teams) for you to manage individual membership.

Please provide the GitHub handle(s) of your desired team maintainers: 

They will be responsible for adding any new team members to the appropriate team.

### Individual - get access to the org

If you're not part of the OpenSSF GitHub org, you can be added. You do not need to be part of an organization which is a member of OpenSSF.

Please provide your GitHub handle:
naveensrinivasan
https://github.com/ossf/scorecard/graphs/contributors
https://github.com/ossf/scorecard/pulls?q=+is%3Apr+author%3Anaveensrinivasan+

https://github.com/ossf/package-feeds/pulls?q=+is%3Apr+author%3Anaveensrinivasan

If you're part of a member organization of the OpenSSF, please [ask to be added to the appropriate team](https://github.com/orgs/ossf/teams).

**Comment by rhaning** [comment]
Invite has been sent.
