### ISSUE TITLE
metrics.openssf.org DNS name

### ISSUE THREAD

**Issue by scovetta** [ossf/tac#58]
Hi Folks!
 We'd like to launch metrics.openssf.org soon, and was wondering how we can get a DNS entry set up. I can provide the destination IP address, but not sure what the process (approval or technical is) on this. We think LF would do the actual work, but we'd like to make sure you're all on board.

Mike

**Comment by jenniferfernick** [comment]
+1, I am on board and am excited to see this!!

**Comment by david-a-wheeler** [comment]
We (the LF) need to make sure we do stuff on *behalf* of the OpenSSF, so step one is getting an okay (e.g., from the TAC). Which is what you're doing!

Once the OpenSSF approves, I can fill in a form to request certain DNS attributes and values to be set. @scovetta , you'll have to tell me exactly what you want set :-).

**Comment by scovetta** [comment]
Excellent!

While we're at it -- it's probably a good time to kick off a discussion on how to obtain "hardware" for running this. How do other LF projects handle hosting? Is there a central operations team at LF, or would "we" run it and just have LF/OpenSSF pay the bills?

**Comment by jenniferfernick** [comment]
Good question -- @rhaning are you aware of how hosting is done typically within LF and how we'd like to do it for OpenSSF? 

As a parallel note -- the OpenSSF Governing Board yesterday discussed the need for a mechanism to get various compute, etc expenses for working groups paid by OpenSSF, so there should be news on this soon. In particular, I believe the TAC will be asking each Working Group of their needs very soon so we can fund those for the WGs ASAP.

**Comment by david-a-wheeler** [comment]
I asked about this. The very short answer is that the first step is to better understand what the needs are. Sometimes we (the LF) have pre-existing mechanisms or services we can piggy-back on.

The default answer is "yes we can host in a cloud environment" and the "LF can help you figure out the specific details. LF IT doesn't provide support for those cloud instances unless it's a stack the LF supports ( i.e. Wordpress, Jenkins, Confluence ), but we (the LF) can directly handle billing."

**Comment by rhaning** [comment]
I would think that working groups would want to host on whichever 3rd party cloud platform they prefer, handle the config, etc... and have LF/OpenSSF take care of the payments. I believe that the GB budget committee was planning for this scenario (and others). @kaywilliams can you provide details on that?

**Comment by kaywilliams** [comment]
@rhaning, I suggest the TAC discuss at the next TAC meeting (tomorrow, Tuesday April 6).  It would be good to understand more from @david-a-wheeler about what the LF can host. Additionally, OpenSSF can take care of payments for needs that fall beyond the scope of what LF can provide.  The Budget Committee (openssf-gb-budget@lists.openssf.org) will be discussing this topic in upcoming meetings.  They will be looking for the TAC and WGs to provide requirements.

**Comment by scovetta** [comment]
This issue should be good to close.
