### ISSUE TITLE
Budget Vote: Developer Best Practices WG

### ISSUE THREAD

**Issue by rhaning** [ossf/tac#60]
Developer Best Practices WG: $63,100
        Operational:  $30,000
        Development - SKF SSO WebHook: $13,100
        Development - SKF Labs: $20,000

**Comment by jenniferfernick** [comment]
Hi Ryan, can you remind us to what "operational" refers in this case?

**Comment by rhaning** [comment]
> Hi Ryan, can you remind us to what "operational" refers in this case?

@jenniferfernick mostly infra to run the services, hosting, etc.

@crob do you have any additional details?

**Comment by rhaning** [comment]
Approve

**Comment by dlorenc** [comment]
Approve

**Comment by RedHatCRob** [comment]
> > Hi Ryan, can you remind us to what "operational" refers in this case?
> 
> @jenniferfernick mostly infra to run the services, hosting, etc.
> 
> @crob do you have any additional details?

Correct Infra costs and hosting

**Comment by raolakkakula** [comment]
Approve on proposal
For hosting, could we leverage existing Azure credits?

**Comment by SecurityCRob** [comment]
Azure *should* be ok, since we’re all pals under K8s.  Thank you very much from the approval all!  We’re looking forward to expanding our capabilities for developers!

Cheers,

CRob
Director of Security Communications
Intel Product Assurance and Security

**Comment by estesp** [comment]
Approve

**Comment by jenniferfernick** [comment]
Approve
