### ISSUE TITLE
The OpenSSF Slack link no longer works

### ISSUE THREAD

**Issue by mrparkers** [ossf/tac#63]
Hello, it appears that the link to join the Slack workspace in the README is no longer working: https://slack.openssf.org/

I saw this was recently fixed in #46 too.

Thanks

**Comment by JamieMagee** [comment]
@LindsayLF you fixed the Slack link in the other issue, could you please update it? Thank you 😄

**Comment by JamieMagee** [comment]
I was able to join via the link today. I think this issue can be closed. Thanks!
