### ISSUE TITLE
TAC Election: Process & Tools

### ISSUE THREAD

**Issue by rhaning** [ossf/tac#67]
- Utilize OpaVote with "meek stv" ranked-choice voting
- Election Officials will announce the timeline for nominations and election via the TAC mailing list and Slack channel
- At the conclusion of the nomination period, the Election Officials will publish the complete list of candidates. Publishing options include, email, doc, and/or TAC repo.
- Election Officials will validate the eligibility of voters before the election.

**Comment by jenniferfernick** [comment]
Point of clarification @rhaning : TAC mailing list, OpenSSF-announcements, both/neither/other?

**Comment by jaltman** [comment]
Am I correct in believing that all eligible voters are not subscribed to the TAC mailing list and/or Slack channel?  If so, I suggest distributing announcements of the election procedures through the working group mailing lists and other channels where eligible voters (aka contributors) might be present.

**Comment by AevaOnline** [comment]
Especially given that this is the first election and folks who aren't "deep" in the org may not know to expect it, I'd suggest sending the announcement a little more broadly than just the TAC mailing list.

Other than that, +1 from me to all of this.

**Comment by jenniferfernick** [comment]
Perhaps to ensure we don't miss anyone:

- OpenSSF announcements mailing list
- OpenSSF TAC mailing list 
- OpenSSF WG-specific mailing lists
- OpenSSF Twitter account 

?

**Comment by jaltman** [comment]
and OpenSSF LinkedIn page

**Comment by jhutchings1** [comment]
@rhaning do we have a proposed timeline on the elections? I may have missed that in one of the other issues.

**Comment by estesp** [comment]
agree on process with the addition of communication avenues in prior comments

**Comment by joshbressers** [comment]
> @rhaning do we have a proposed timeline on the elections? I may have missed that in one of the other issues.

I want to bump this question. I've not seen anything public announced regarding this election.

**Comment by dlorenc** [comment]
Closing as the election is finished.
