### ISSUE TITLE
TAC Election: Should we increase the size of the TAC?

### ISSUE THREAD

**Issue by rhaning** [ossf/tac#68]
Currently the TAC is comprised of 7 seats. It has been suggested that increasing the size of the TAC could improve effectiveness by increasing diversity and varying view points. It has also been mention that too large of a TAC could hamper progress, but also that no one had directly observed this.
Suggestion: Increase to 7 or 9 seats for the next year and revisit before the next election.

**Comment by jaltman** [comment]
Odd numbers are important to avoid ties when voting.  An alternative to odd numbers is to give the chair an extra half vote.

Some of the fears of larger committees are associated with the increased time it would take for everyone to express their opinion in meetings, potential challenges associated with obtaining opinions/votes from larger numbers, and a dilution of responsibility.   Some of these potential issues can be mitigated by organizational processes.   In the end, whether or not there is an issue will be determined by the elected members.

One observation about human behavior in meetings is that as the group size increases it is often the case that fewer people are willing to speak.   Something to consider.

**Comment by AevaOnline** [comment]
I generally like 7 as a committee size, but for an organization as broad as the OpenSSF, I could easily make a case for a larger TAC; that case would pivot based on whether the TAC were expected to be directly engaged in the projects (representational body) or only supervisorily engaged (advisory body).

If the desired structure is direct-engagement by TAC members in project(s), I'd suggest a larger group; if the desired structure is for the TAC to only advise / approve / review, then I'd suggest a smaller group.

**Comment by jhutchings1** [comment]
7 definitely seems like a good size.

**Comment by estesp** [comment]
I think I'm good with 7 for now; given @AevaOnline's comment (which I think is a great point), if we decide that the TAC continues to be more advisory and the working groups to be where most contributors/work is accomplished, then I think 7 is plenty for handling that level of activity, and keeps us from some of the complexity (per @dlorenc) of trying to herd a larger group.

**Comment by david-a-wheeler** [comment]
@lehors - you're right, this is obviously OBE for this round. For convenience I'll close this obsolete comment, if that's an error, someone please re-open it!

I wouldn't be surprised if it gets re-opened for a future TAC, but I'm guessing that should be a separate issue.
