### ISSUE TITLE
TAC Election: Officials

### ISSUE THREAD

**Issue by rhaning** [ossf/tac#69]
Who should be the Election Officials?

Suggestion: 
- OpenSSF General Manager
- OpenSSF Program Director
- OpenSSF TAC Chair
- OpenSSF TAC rep from an org that is not the same org as the TAC Chair

**Comment by jaltman** [comment]
I think you can add one or more OpenSSF Governing Board members to the potential pool.   I'm willing to serve as a TAC election official assuming I am re-elected to the GB this week.

**Comment by AevaOnline** [comment]
For point of comparison, here is the document guiding the Kubernetes' community selection of Election Officials - https://github.com/kubernetes/steering/blob/main/elections.md#election-officer-selection 

Akin to that, I suggest the following criteria be adopted here:
- number of election officials: 3
- eligibility: each election official must be eligible to vote in the election
- maximal representation: no two officials may be employed by the same entity (this includes subsidiaries and affiliates, to ensure the perception of open and fair elections)

**Comment by naveensrinivasan** [comment]
> Who should be the Election Officials?
> 
> Suggestion:
> 
> * OpenSSF General Manager
> * OpenSSF Program Director
> * OpenSSF TAC Chair
> * OpenSSF TAC rep from an org that is not the same org as the TAC Chair

Is there a specific reason for the above suggestions?

I would suggest OpenSSF member!

**Comment by dlorenc** [comment]
I think this can be closed now right?
