### ISSUE TITLE
Syft and Grype project donation request

### ISSUE THREAD

**Issue by joshbressers** [ossf/tac#70]
Hello,

As noted in this message
https://lists.openssf.org/g/openssf-tac/message/370

I am opening this issue to discuss the topic of Anchore donating Syft and Grype to the OpenSSF

https://github.com/anchore/syft/
https://github.com/anchore/grype

Both projects are Apache 2 licensed and widely used.

Please let me know what other information is needed to move this process along.

**Comment by dlorenc** [comment]
This would be amazing!

**Comment by inferno-chromium** [comment]
I am not a TAC member, but strongly support this move.

**Comment by lukehinds** [comment]
STGM

**Comment by justaugustus** [comment]
Very exciting to see this proposed!

**Comment by hectorj2f** [comment]
This would be awesome for the community!

**Comment by samj1912** [comment]
+1 (not that my vote counts) but both syft and grype are really amazing projects and I can see the hard-work and forward thinking insight that has gone around designing and creating them by the folks at @anchore. Would be amazing to see these become a part of openssf 🙏

**Comment by joshbressers** [comment]
I want to add some clarification to this issue. The intent of my question is to gather more details from the OpenSSF about the process and expectations. This is not a final decision at this time. I think there are a lot of gaps in how donation works in the OpenSSF. Dan started a thread about this here
https://lists.openssf.org/g/openssf-tac/message/374

**Comment by marcelamelara** [comment]
hello @joshbressers ! It looks like there was a lot of interest in this project donation back in late 2021, though we haven't seen much movement since. Is there still interest in donating Syft and Grype to the OpenSSF? If so, we can get that process started.

**Comment by joshbressers** [comment]
@marcelamelara This isn't a priority for us at this time, I'll close this
