### ISSUE TITLE
Component Detection joining as a project under the OpenSSF 

### ISSUE THREAD

**Issue by JamieMagee** [ossf/tac#74]
Hi all 👋 

I presented Component Detection in the most recent TAC meeting, December 14th 2021, and expressed our interest in joining as a project under the OpenSSF.

I am opening this issue to track discussions and progress.

Links:

- https://github.com/microsoft/component-detection
- [Initial email to the TAC](https://lists.openssf.org/g/openssf-tac/message/367)
- [OpenSSF Tac Meeting - December 14th 2021](https://youtu.be/JsGPRkB2IPs?t=2026) (Starts at 33:46)
- [Component Detection Presentation](https://github.com/ossf/tac/files/7738323/Component.Detection.OpenSSF.pptx)

We'll be working towards the requirements listed [here](https://github.com/ossf/tac/blob/main/working-group-lifecycle.md#to-become-incubating)

**Comment by marcelamelara** [comment]
hello @JamieMagee ! It looks like there was interest in this project donation back in late 2021, though we haven't seen much movement since. Is there still interest in donating Component Detection to the OpenSSF? If so, we can get the process going again.

**Comment by JamieMagee** [comment]
Thanks for reaching out Marcela. I'll check-in with my team on this and get back to you.

**Comment by JamieMagee** [comment]
@marcelamelara we don't plan to proceed with the donation at the moment, so I'll close out the issue. I'll reopen it if that changes.
