### ISSUE TITLE
Proposal: New working group for source package ecosystems

### ISSUE THREAD

**Issue by jchestershopify** [ossf/tac#79]
Folks involved in RubyGems, PyPI and npm have been informally swapping notes over the past few months as we have each pursued our own goals. After some back and forth, we joined a single call and began to more seriously compare experiences and problems.

From that meeting has arisen the idea that we would like to form a proper working group, in order to maintain momentum on sharing ideas, designs and solutions to obstacles. This seems to be a good fit for the OpenSSF, as source package systems represent a very large fraction of the overall software supply chain.

I see this working group being less about end-to-end security (for which Supply Chain Integrity WG is already responsible) and more specifically scoped to source package managers. We have a lot of nitty gritty details to discuss that would bog down existing working groups, but which nonetheless are profitable to discuss regularly.

My request is:
1. TAC signals whether or not such a working group would be acceptable in principle, and
2. What conditions or requirements must first be met in order to adopt such a working group into the OpenSSF's oversight.

**Comment by dlorenc** [comment]
I am strongly in favor of this! The process is documented roughly here: https://github.com/ossf/tac/blob/main/working-group-lifecycle.md#to-become-incubating

In short, you can just get going with public meetings and notes. I'm happy to help "host" it under the Supply Chain Integrity WG until you get the five meetings done and are ready to propose the actual group.

**Comment by jchestershopify** [comment]
I think there's enough to discuss that we might need our own dedicated time. From my reading that means we go ahead and keep meeting, and then when we reach 5 meetings we come back and bump this issue.

**Comment by dlorenc** [comment]
> I think there's enough to discuss that we might need our own dedicated time. From my reading that means we go ahead and keep meeting, and then when we reach 5 meetings we come back and bump this issue.

Yeah sorry - I didn't mean to cover it in the existing meeting, just from the OSSF "sponsorship" angle if you'd like to use the shared calendar, slack and zoom while you make it through those 5 meetings.

**Comment by lukehinds** [comment]
Would be nice to see a problem statement come out of this and what the call to action would be. What are the pain points the group would seek to address.

**Comment by AevaOnline** [comment]
I'm also in support of encouraging collaboration between package manager ecosystems.

I'd like to see a "mission statement" or "scope" for this effort, and then see how it grows over the next few meetings, to help figure out where to locate the work within the OpenSSF.

**Comment by Eh2406** [comment]
I would love to know when meetings are. I will do my best to attend. I am on the Cargo Team helping to maintain Rusts package manager.

**Comment by betarelease** [comment]
+1 I would love to join meetings and share what we are learning as well. Please share engagement details here.

**Comment by MylesBorins** [comment]
Speaking to @AevaOnline's ask

> I'd like to see a "mission statement" or "scope" for this effort, and then see how it grows over the next few meetings, to help figure out where to locate the work within the OpenSSF.

I'd like to propose a mission of

"A vendor neutral space for the stewards of source package ecosystems to collaborate and share learnings and roadmaps to better align."

For scope I think it would be good to stick to:

* Sharing of roadmap and implementation specifics
* Identifying problem spaces and planned solutions the registries are facing
* Identifying opportunities for shared infrastructure or implementation
* Identifying opportunities to align on policies and the "role" of the ecosystem steward
* Ensuring that the "last mile" of software distribution is secure.

What I would like us to avoid is "design by committee" solutions to problems.

**Comment by trevrosen** [comment]
+1 have been in the informal meetings and happy to join formalized group as a representative of GitHub.

**Comment by pete2160** [comment]
Would like to attend one of the informal meetings to see how we can participate / contribute from a ProdSec perspective and if it is corresponding to / with other working groups.

**Comment by simi** [comment]
Hello, I'm contributor to RubyGems/RubyGems.org projects. I can attend one of the initial meetings to evaluate my usefulness as well.

**Comment by trishankatdatadog** [comment]
Very cool! So how should we go about the first meeting?

**Comment by di** [comment]
I can just make our recent call a recurring meeting if that sounds good to everyone.

**Comment by jchestershopify** [comment]
For context, that first meeting was 9am-10am North American Eastern Time, or 3pm-4pm CET.

**Comment by MylesBorins** [comment]
What day would the meeting be planned for?

**Comment by dlorenc** [comment]
I think we need to ask the LF staff to create it correctly. I'll start a slack thread.

**Comment by joshuagl** [comment]
For folks following this thread, it looks like the first meeting is scheduled for tomorrow March 2nd at 7am Pacific.

**Comment by jchestershopify** [comment]
My calendar shows it as 9am-10am ET, which would be 6am-7am PT in my reckoning. 2pm-3pm GMT and 3pm-4pm CET.

**Comment by MylesBorins** [comment]
Is there a public calendar I can reference for details and to confirm time?

**Comment by jchestershopify** [comment]
It looks like it was added to the OpenSSF calendar, which you [can get from here](https://openssf.org/getinvolved/).

**Comment by joshuagl** [comment]
> My calendar shows it as 9am-10am ET, which would be 6am-7am PT in my reckoning. 2pm-3pm GMT and 3pm-4pm CET.

Thank you

**Comment by di** [comment]
We also have a `#securing_software_repos` channel in the OpenSSF slack as well (https://slack.openssf.org/).

**Comment by david-a-wheeler** [comment]
Figuring out a scope/mission is an important step. I suggest that the first meetings work out, in part, at least one specific result the nascent group wants to accomplish.

Don't get me wrong, I think discussion & coordination is important! But having something concrete to work on is also important. We don't want this to just be "jawing with no action".

For example: The group could create a combined list of security mechanisms or properties that at least one repo or package manager has, determine which other ones have/don't have the mechanism/property, and then propose adding those mechanisms to the other ones where appropriate. It doesn't have to be that specifically, but I'd like to see a concrete result eventually getting produced.

**Comment by trishankatdatadog** [comment]
Hmm, this is a difficult one: while we don't want to force repositories what to do, I think we should at least agree on things like common signing formats (e.g., DSSE) and solutions so that there is some interoperability, not to mention ultimately shared strengths. While each repo can begin with different solutions as they see fit, I think some level of shared convergence is important so that, for example, we can write open source tooling that can access supply chain security for packages without resorting to different logic for each repo. Imagine if each website implemented TLS differently, so that browsers had to write different logic for different websites: it would be undesirable to have that situation for codesigning. Perhaps this is something we should discuss in the first few meetings.

**Comment by brianf** [comment]
Jumping in from the Maven Central & Sonatype side...

**Comment by iamwillbar** [comment]
I think this a great proposal and fully support it. When I was at GitHub we hosted a PackCon event and invited package manager/registry maintainers to discuss common issues and approaches. Security was a large part of this discussion and despite the significant implementation differences between package managers there was a significant overlap in the underlying problems trying to be solved.

**Comment by bobcallaway** [comment]
FYI - a new repo for the proposed WG has been created at https://github.com/ossf/wg-securing-software-repos

**Comment by MylesBorins** [comment]
thanks @bobcallaway. How do folks go about requesting membership? Is the membership list of working groups displayed publicly anywhere?

To be clear I think it is good to document this kind of stuff publicly, just curious process as I'm unfamiliar

**Comment by dlorenc** [comment]
> thanks @bobcallaway. How do folks go about requesting membership? Is the membership list of working groups displayed publicly anywhere?

Since meetings are open to the public there's no real concept of a "member". Some WGs choose to maintain a list of participants which are basically just people that choose to add their name to a public list.

**Comment by jchestershopify** [comment]
It's open in practice, but the proposed `CHARTER.md` does require a named list of "Maintainers" in order to function. One of my action items for this week is to pull out attendees of >2 meetings from the minutes to form the basis for that list.

**Comment by di** [comment]
@simi There's an [invite link](https://openssf.slack.com/join/shared_invite/zt-xoktwsef-VzM~b22G2gfT_~4woTTsQA#/shared-invite/email), I've made a PR to add it to the WG README: https://github.com/ossf/wg-securing-software-repos/pull/5

**Comment by bobcallaway** [comment]
The creation of the WG was approved on April 13, 2022, so closing this :)
