### ISSUE TITLE
Any global organizational framework for OpenSSF?

### ISSUE THREAD

**Issue by fredgan** [ossf/tac#84]
Hi all. Recently I study OpenSSF a lot. I read many pages from the official website and github workgroups. I get a vague framework for what OpenSSF do in my head.

But can the offical provide a organizational framework? Including all the groups/work/plans/logic etc, so that the newbie can get the panorama. Thanks!

**Comment by SecurityCRob** [comment]
I propose that the TAC creates a reference architecture diagram showing all the components and related activities of the foundation and how they interact with each other, with links to the assorted projects and working groups so that newcomers (and long-time participants) can more easily see the full scope of the OSSF and jump in where they have interest.

**Comment by AevaOnline** [comment]
I second @SecurityCRob 's proposal - and would like to add, that I suggest such a document or diagram live in the (new) [ossf/community](https://github.com/ossf/community) repo. 

I would like for us to have both a document describing our "governance principles" as well as the "component architecture": the former describing relationships between GB, TAC, WG, Project, SIF, Committee, etc ; the latter describing the relative boundaries between different instances of each type, for instance naming each Working Group and summarizing its charter, with some described relationship between them. 

There are some examples in other foundations, for instance in [Kubernetes](https://github.com/kubernetes/community/blob/master/governance.md)

I've started a draft in [this pull request](https://github.com/ossf/community/pull/4), though it is far from complete today.

**Comment by jorydotcom** [comment]
@AevaOnline @SecurityCRob we can use the Landscape tool to generate this visual and embed it on the website, /community repo, etc. It would be great to have the TAC work on something of an architecture paper that would go with this, and provide more depth

**Comment by marcelamelara** [comment]
hello! I wanted to ping this issue. Is this possibly addressed by [this organizational overview](https://github.com/ossf/tac/blob/main/organizational-structure-overview.md)?
