### ISSUE TITLE
Tracking: what is a "SIF"?

### ISSUE THREAD

**Issue by AevaOnline** [ossf/tac#85]
This Term came up in a few conversations recently, so I want to capture the working definition as I understand it, until we can incorporate this somewhere more formal. The below explanation is copied with permission from a private conversation -
> A SIF is a "Specific Initiative Fund" and it's not called out in the charter specifically. A SIF is a "directed fund" under the OpenSSF that members can contribute to in addition to their membership dues, to fund specific initiatives like sigstore/Project A-O.
> Before the "relaunch" of the OpenSSF, folks wanted to call out the opportunities to fund specific projects via a sub-directed fund and they decided to call that a SIF to avoid confusion with crowdfunding projects or the membership fund.

There are a few clauses [within the Charter](https://cdn.platform.linuxfoundation.org/agreements/openssf.pdf) that appear (to my non-lawyerly eyes) to cover this scenario, even though it is not named:

3(j)(viii):
> The Governing Board will be responsible for overall management of the OpenSSF, including ... approve directed fundraising proposals for specific Working Groups or Projects that will raise and spend funds within the Working Group or Project

13(b):
> Individual Technical Initiative funding arrangements may be setup under alternative arrangements by approval of the Governing Board and the Linux Foundation

**Comment by lehors** [comment]
I only know of one organization that has a structure that resembles what I understand this SIF is meant to be: OASIS. I highly recommend everyone interested in this question to read about the OASIS Member Sections. This is a structure that has been in place for many years and that is very well documented. It works and I think it addresses many of the questions that were raised during the Planning Committee meeting of 03/28/2022. See: https://www.oasis-open.org/policies-guidelines/member-sections/

**Comment by lehors** [comment]
I think fundamentally we have two possible options: either SIFs are managed by the existing GB or there needs to be a dedicated body that manages each SIF and reports to the GB. Similarly on the technical side, SIF projects can either report directly to the TAC or have their own dedicated Technical Steering Committee (TSC) which reports to the TAC.

**Comment by SecurityCRob** [comment]
SIF is no longer part of our item types from the Charter.  If we find an effort that would meet this criteria again, we can reopen this issue.  Closing for now.
