### ISSUE TITLE
Post permission issues here

### ISSUE THREAD

**Issue by david-a-wheeler** [ossf/tac#90]
If you can't do something in OpenSSF that you think you should be able to do, or CAN do something you DON'T think you should do, reply to this issue (per TAC discusion).

**Comment by annabellegoth2boss** [comment]
I do not have a seat on the TAC (who would be the project approvers) but I can make repos for new projects (or anything else) :) 

I can also see private repos that have been created.

cc @strawberry-baked-alaska @bobcallaway @AevaOnline from today's TAC call where this came up

I imagine there are some cases to fine tune like WGs needing to start a new repo (maybe a chair has those perms?), but seems like a sensible place would be to lock repo-creation down for now and increase permissions as use cases emerge.

**Comment by JanZerebecki** [comment]
Technical a permission issue: https://github.com/ossf/tac/issues/110

**Comment by SecurityCRob** [comment]
Is this issue still needed?  Can we close and open new issues for any future issues?

**Comment by SecurityCRob** [comment]
Staff has process for permissions & Dana is working up better definition of roles.  Closing.
